### ISSUE TITLE
Path penetration

### ISSUE THREAD

**Issue by 360CodeSafe** [oracle/weblogic-kubernetes-operator#1024]
Hello
I am a 360 code security team staff member who found a path traversal vulnerability in weblogic-kubernetes-operator in our open source code detection project.Details are as follows：
weblogic-kubernetes-operator-master\integration-tests\src\test\java\oracle\kubernetes\operator\utils\PersistentVolume.java
![图片](https://user-images.githubusercontent.com/39950310/55926117-a9549380-5c42-11e9-9ebe-ca05a84f48ee.png)
When the domainUID is controlled by the user, the path may be created by "../" to create a file in any folder.

**Comment by russgold** [comment]
You do recognize that this is an integration test, right? It's not production code.

**Comment by rjeberhard** [comment]
We are grateful for your scan, but as Russ noted, this code point is in functional test setup logic that is not part of production code. Please limit your scans to production code.
