### ISSUE TITLE
Logstash config map

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-kubernetes-operator#104]
Hello,
currently logstash can be configured just rebuilding the operator image everytime.

I think that it would be nice to decouple the two things and have a config map to setup the logstash.conf.

The user could want to add different filters, save the logs also to file or send to a private ES instance and so on. 

For this you could provide a template with parametrized basic configuration. In the input parameter file let the users decide if deploy the whole ES stack or just logstash.

**Comment by mriccell** [comment]
@antonionappi88 I have added this requirement to be tracked post GA of Operator 2.0.
Thanks
Monica

**Comment by tbarnes-us** [comment]
Assigning to Monica for triage. Perhaps this work is already done?

**Comment by robertpatrick** [comment]
Tracked by internal Oracle JIRA OWLS-94850
