### ISSUE TITLE
Managed Sever failed to start : Boot identity not valid

### ISSUE THREAD

**Issue by shaunxa** [oracle/weblogic-kubernetes-operator#1056]

**Comment by mriccell** [comment]
@shaunxa How did you build your domain?  Is this a domain-home in image or on PV?

**Comment by shaunxa** [comment]
Hi All,

I created the domain 'sample-domain1' following the quick start procedure @ https://oracle.github.io/weblogic-kubernetes-operator/quickstart/ and using oracle/weblogic-kubernetes-operator   2.1. The managed servers failed to start. I recreated the domain a few times while no luck.

I did some troubleshooting and found the encrypted username and password in boot.properties of the managed servers was different from the ones in boot.properties of admin-server. See below.

bash-4.2# cat /u01/oracle/user_projects/domains/sample-domain1/servers/managed-server2/security/boot.properties
username={AES}yW8GbBiJQ/OCK9/CTSzT52gQJdQELiREe1s74NGvN3o=
password={AES}qYMjSSZB4WXLVXJTvPvsk9t5pUXX8xyniUDmTmPxz4I=

bash-4.2# cat /u01/oracle/user_projects/domains/sample-domain1/servers/admin-server/security/boot.properties
# Generated by Configuration Wizard on Sun Apr 28 10:05:14 GMT 2019
username={AES}4/NSgptFlnhgpzUfV9xc5d9OjOPeqFnmb2Wnng9GlN8=
password={AES}Eyf0O6d8n01/J2a3J/OrA5nLVGlRx7I565EvTNdvNi0=
bash-4.2#

Appreciate if you could give any advise. Thanks.

Cheers,
Shaun

**Comment by shaunxa** [comment]
@mriccell It is domain-home-in-image.

**Comment by shean-guangchang** [comment]
Could you share the exact steps you took to follow the quick start quide? I assume you are using the operator 2.1 and what version of k8s you are using?

**Comment by shaunxa** [comment]
@shean-guangchang shean, thank you for your help. Here are the product versions and the the procedure.

[opc@centos7-ad3-1 ~]$ kubectl get nodes
NAME            STATUS   ROLES    AGE   VERSION
centos7-ad3-1   Ready    master   45h   v1.14.1
centos7-ad3-2   Ready    <none>   45h   v1.14.1
centos7-ad3-3   Ready    <none>   43h   v1.14.1
[opc@centos7-ad3-1 ~]$



[opc@centos7-ad3-1 domain-home-in-image]$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
domain-home-in-image                  12.2.1.3            e62d28737407        40 hours ago        1.19GB
k8s.gcr.io/kube-proxy                 v1.14.1             20a2d7035165        3 weeks ago         82.1MB
k8s.gcr.io/kube-apiserver             v1.14.1             cfaa4ad74c37        3 weeks ago         210MB
k8s.gcr.io/kube-controller-manager    v1.14.1             efb3887b411d        3 weeks ago         158MB
k8s.gcr.io/kube-scheduler             v1.14.1             8931473d5bdb        3 weeks ago         81.6MB
oracle/weblogic-kubernetes-operator   2.1                 93bc4db27b5d        3 weeks ago         527MB
quay.io/coreos/flannel                v0.11.0-amd64       ff281650a721        3 months ago        52.6MB
k8s.gcr.io/coredns                    1.3.1               eb516548c180        3 months ago        40.3MB
store/oracle/weblogic                 12.2.1.3            d58f0d158db5        3 months ago        1.19GB
hello-world                           latest              fce289e99eb9        3 months ago        1.84kB
traefik                               1.7.6               b0a0d7271403        4 months ago        69.3MB
k8s.gcr.io/etcd                       3.3.10              2c4adeb21b4f        5 months ago        258MB
k8s.gcr.io/pause                      3.1                 da86e6ba6ca1        16 months ago       742kB
[opc@centos7-ad3-1 domain-home-in-image]$


In the master node
=======================================================
cd /home/opc/wls-k8s-operator
git clone https://github.com/oracle/weblogic-kubernetes-operator.git


Followed exact procedure @ https://oracle.github.io/weblogic-kubernetes-operator/quickstart/prerequisites/ to
https://oracle.github.io/weblogic-kubernetes-operator/quickstart/create-domain/
except the following ./create-domain.sh command with the custom input file
---------------------------------------------------------------------------------------------

[opc@centos7-ad3-1 domain-home-in-image]$ pwd
/home/opc/wls-k8s-operator/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image
[opc@centos7-ad3-1 domain-home-in-image]$ diff create-domain-inputs.yaml create-domain-inputs.yaml.orig
16c16
< domainUID: sample-domain1
---
> domainUID: domain1
70c70
< weblogicCredentialsSecretName: sample-domain1-weblogic-credentials
---
> weblogicCredentialsSecretName: domain1-weblogic-credentials
86c86
< logHome: /shared/logs/sample-domain1
---
> logHome: /shared/logs/domain1
104c104
< exposeAdminNodePort: true
---
> exposeAdminNodePort: false
107c107
< namespace: sample-domain1-ns
---
> namespace: default
116c116
< persistentVolumeClaimName: sample-domain1-weblogic-sample-pvc
---
> persistentVolumeClaimName: domain1-weblogic-sample-pvc
[opc@centos7-ad3-1 domain-home-in-image]$


$ cd kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image
$ ./create-domain.sh -i create-domain-inputs.yaml -o /home/opc/wls-k8s-operator/sample-domain1 -u weblogic -p welcome1 -e


$ kubectl apply -f /home/opc/wls-k8s-operator/sample-domain1/weblogic-domains/sample-domain1/domain.yaml

**Comment by shean-guangchang** [comment]
Does the steps you took work in a single node env?

**Comment by vanajamukkara** [comment]
Is admin server starting up fine?

For a multi-node Kubernetes cluster, make sure that the generated image is available on all nodes before creating the domain resource using the kubectl apply -f command.

https://oracle.github.io/weblogic-kubernetes-operator/quickstart/create-domain/
If you run the sample from a machine that is remote to the Kubernetes cluster, and you need to push the new image to a registry that is local to the cluster, you need to do the following:

   Set the image property in the inputs file to the target image name (including the registry hostname/port, and the tag if needed).
   If you want Kubernetes to pull the image from a private registry, create a Kubernetes secret to hold your credentials and set the imagePullSecretName property in the inputs file to the name of the secret.

**Comment by shaunxa** [comment]
@shean-guangchang @vanajamukkara It is multi-node cluster (1 master and 2 worker nodes). For the images built in the master node, I save them to tar files and load them to the worker nodes. Here are the details of the cluster and the images in the mater and worker nodes.

[opc@centos7-ad3-1 ~]$ kubectl get nodes
NAME            STATUS   ROLES    AGE    VERSION
centos7-ad3-1   Ready    master   3d7h   v1.14.1
centos7-ad3-2   Ready    <none>   3d7h   v1.14.1
centos7-ad3-3   Ready    <none>   3d5h   v1.14.1

===========
master
===========
[opc@centos7-ad3-1 ~]$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
domain-home-in-image                  12.2.1.3            e62d28737407        3 days ago          1.19GB
k8s.gcr.io/kube-proxy                 v1.14.1             20a2d7035165        3 weeks ago         82.1MB
k8s.gcr.io/kube-apiserver             v1.14.1             cfaa4ad74c37        3 weeks ago         210MB
k8s.gcr.io/kube-controller-manager    v1.14.1             efb3887b411d        3 weeks ago         158MB
k8s.gcr.io/kube-scheduler             v1.14.1             8931473d5bdb        3 weeks ago         81.6MB
oracle/weblogic-kubernetes-operator   2.1                 93bc4db27b5d        3 weeks ago         527MB
quay.io/coreos/flannel                v0.11.0-amd64       ff281650a721        3 months ago        52.6MB
k8s.gcr.io/coredns                    1.3.1               eb516548c180        3 months ago        40.3MB
store/oracle/weblogic                 12.2.1.3            d58f0d158db5        3 months ago        1.19GB
hello-world                           latest              fce289e99eb9        4 months ago        1.84kB
traefik                               1.7.6               b0a0d7271403        4 months ago        69.3MB
k8s.gcr.io/etcd                       3.3.10              2c4adeb21b4f        5 months ago        258MB
k8s.gcr.io/pause                      3.1                 da86e6ba6ca1        16 months ago       742kB
[opc@centos7-ad3-1 ~]$

===========
workers
===========
[opc@centos7-ad3-2 ~]$ docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
domain-home-in-image                    12.2.1.3            e62d28737407        3 days ago          1.19GB
k8s.gcr.io/kube-proxy                   v1.14.1             20a2d7035165        3 weeks ago         82.1MB
oracle/weblogic-kubernetes-operator     2.1                 93bc4db27b5d        3 weeks ago         527MB
kibana                                  5                   62079cf74c23        5 weeks ago         396MB
traefik                                 1.7.9               98768a8bf3fe        2 months ago        70.2MB
quay.io/coreos/flannel                  v0.11.0-amd64       ff281650a721        3 months ago        52.6MB
store/oracle/weblogic                   12.2.1.3            d58f0d158db5        3 months ago        1.19GB
k8s.gcr.io/kubernetes-dashboard-amd64   v1.10.1             f9aed6605b81        4 months ago        122MB
traefik                                 1.7.6               b0a0d7271403        4 months ago        69.3MB
k8s.gcr.io/pause                        3.1                 da86e6ba6ca1        16 months ago       742kB
[opc@centos7-ad3-2 ~]$


[opc@centos7-ad3-3 ~]$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
domain-home-in-image                  12.2.1.3            e62d28737407        3 days ago          1.19GB
k8s.gcr.io/kube-proxy                 v1.14.1             20a2d7035165        3 weeks ago         82.1MB
oracle/weblogic-kubernetes-operator   2.1                 93bc4db27b5d        3 weeks ago         527MB
elasticsearch                         5                   752be83a5396        4 weeks ago         486MB
gcr.io/kubernetes-helm/tiller         v2.13.1             cb5aea7d0466        5 weeks ago         82.1MB
traefik                               1.7.9               98768a8bf3fe        2 months ago        70.2MB
quay.io/coreos/flannel                v0.11.0-amd64       ff281650a721        3 months ago        52.6MB
store/oracle/weblogic                 12.2.1.3            d58f0d158db5        3 months ago        1.19GB
traefik                               1.7.6               b0a0d7271403        4 months ago        69.3MB
k8s.gcr.io/pause                      3.1                 da86e6ba6ca1        16 months ago       742kB
[opc@centos7-ad3-3 ~]$

**Comment by vanajamukkara** [comment]
I am trying to follow quickstart and try to reproduce the issue..

**Comment by vanajamukkara** [comment]
@shaunxa Do you load the domain image in the worker nodes before you create the domain?

Also in the below commands you used to create domain, you should **not** use "-e" in the create-domain.sh command. 
$ cd kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image
$ ./create-domain.sh -i create-domain-inputs.yaml -o /home/opc/wls-k8s-operator/sample-domain1 -u weblogic -p welcome1 -e
$ kubectl apply -f /home/opc/wls-k8s-operator/sample-domain1/weblogic-domains/sample-domain1/domain.yaml

Correct steps are 
$ ./create-domain.sh -i create-domain-inputs.yaml -o /home/opc/wls-k8s-operator/sample-domain1 -u weblogic -p welcome1
load domain image on all worker nodes
$ kubectl apply -f /home/opc/wls-k8s-operator/sample-domain1/weblogic-domains/sample-domain1/domain.yaml

**Comment by vanajamukkara** [comment]
I followed quickstart and able to bring up the domain on multi node cluster. I am pushing domain image to OCIR, so had to change the image and imagePullSecretName attributes and create secret in domain namespace. As you are saving the image to tar and loading on worker nodes, you don't have to these things. Please check my above comment for the correct steps.

**Comment by shaunxa** [comment]
Hi All, I recreated the domain using 'root' user and all the admin and managed servers started running. Many thanks for your advise.

[root@centos7-ad3-1 domain-home-in-image]# kubectl get po -n sample-domain1-ns
NAME                             READY   STATUS    RESTARTS   AGE
sample-domain1-admin-server      1/1     Running   0          73s
sample-domain1-managed-server1   1/1     Running   0          41s
sample-domain1-managed-server2   1/1     Running   0          41s
[root@centos7-ad3-1 domain-home-in-image]#

Cheers,
Shaun

**Comment by shean-guangchang** [comment]
If it is the same process except the user' privilege then did you run into any error prior that you can share?

**Comment by shaunxa** [comment]
@shean-guangchang Yes.
