### ISSUE TITLE
Simple overrride made admin server CrashLoopBackOff

### ISSUE THREAD

**Issue by shaunxa** [oracle/weblogic-kubernetes-operator#1063]
Simple Override
-------------------------------------------------------------------
[root@centos7-ad3-1 wls-k8s-operator]# vi override.yaml
[root@centos7-ad3-1 wls-k8s-operator]# kubectl -n sample-domain1-ns create cm sample-domain1-cm --from-file /opt/wls-k8s-operator/simpleoverride
configmap/sample-domain1-cm created
[root@centos7-ad3-1 wls-k8s-operator]# kubectl -n sample-domain1-ns label cm sample-domain1-cm weblogic.domainUID=sample-domain1
configmap/sample-domain1-cm labeled
[root@centos7-ad3-1 wls-k8s-operator]#
[root@centos7-ad3-1 wls-k8s-operator]# kubectl apply -f override.yaml
domain.weblogic.oracle/sample-domain1 configured
[root@centos7-ad3-1 wls-k8s-operator]#
[root@centos7-ad3-1 wls-k8s-operator]# cat override.yaml
apiVersion: "weblogic.oracle/v2"
kind: Domain
metadata:
  name: sample-domain1
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: sample-domain1
spec:
  webLogicCredentialsSecret:
    name: sample-domain1-weblogic-credentials
  configOverrides: sample-domain1-cm

[root@centos7-ad3-1 wls-k8s-operator]#
[root@centos7-ad3-1 wls-k8s-operator]# cd simpleoverride/
[root@centos7-ad3-1 simpleoverride]# ls -ltr
total 4
-rw-r--r--. 1 root root 370 May  2 11:33 config.xml
[root@centos7-ad3-1 simpleoverride]# cat config.xml
<?xml version='1.0' encoding='UTF-8'?>
<d:domain xmlns:d="http://xmlns.oracle.com/weblogic/domain"
          xmlns:f="http://xmlns.oracle.com/weblogic/domain-fragment"
          xmlns:s="http://xmlns.oracle.com/weblogic/situational-config" >
  <d:log>
    <d:name>sample-domain1</d:name>
    <d:file-name>sample-domain1-override.log</d:file-name>
  </d:log>
</d:domain>
[root@centos7-ad3-1 simpleoverride]#

After applying the simple overrride
----------------------------------------
[root@centos7-ad3-1 wls-k8s-operator]# kubectl get po -n sample-domain1-ns
NAME                             READY   STATUS             RESTARTS   AGE
sample-domain1-admin-server      0/1     CrashLoopBackOff   1          11s
sample-domain1-managed-server1   1/1     Running            0          80m
sample-domain1-managed-server2   1/1     Running            0          80m
[root@centos7-ad3-1 wls-k8s-operator]#
[root@centos7-ad3-1 wls-k8s-operator]#

[root@centos7-ad3-1 wls-k8s-operator]# kubectl log sample-domain1-admin-server -n sample-domain1-ns
log is DEPRECATED and will be removed in a future version. Use logs instead.
@[2019-05-02T08:01:53.334 UTC][startServer.sh:16] Starting WebLogic Server 'admin-server'.
@[2019-05-02T08:01:53.349 UTC][startServer.sh:96] Info: DOMAIN_UID='sample-domain1'
@[2019-05-02T08:01:53.364 UTC][startServer.sh:96] Info: DOMAIN_NAME='sample-domain1'
@[2019-05-02T08:01:53.378 UTC][startServer.sh:96] Info: DOMAIN_HOME='/u01/oracle/user_projects/domains'
@[2019-05-02T08:01:53.392 UTC][startServer.sh:96] Info: NODEMGR_HOME='/u01/nodemanager'
@[2019-05-02T08:01:53.405 UTC][startServer.sh:96] Info: SERVER_NAME='admin-server'
@[2019-05-02T08:01:53.419 UTC][startServer.sh:96] Info: SERVICE_NAME='sample-domain1-admin-server'
@[2019-05-02T08:01:53.432 UTC][startServer.sh:96] Info: ADMIN_NAME='admin-server'
@[2019-05-02T08:01:53.446 UTC][startServer.sh:96] Info: ADMIN_PORT='7001'
@[2019-05-02T08:01:53.460 UTC][startServer.sh:96] Info: SERVER_OUT_IN_POD_LOG='true'
@[2019-05-02T08:01:53.475 UTC][startServer.sh:96] Info: AS_SERVICE_NAME='sample-domain1-admin-server'
@[2019-05-02T08:01:53.489 UTC][startServer.sh:172] LOG_HOME=
@[2019-05-02T08:01:53.504 UTC][startServer.sh:173] SERVER_OUT_IN_POD_LOG=true
@[2019-05-02T08:01:53.518 UTC][startServer.sh:174] USER_MEM_ARGS=-Djava.security.egd=file:/dev/./urandom
@[2019-05-02T08:01:53.533 UTC][startServer.sh:175] JAVA_OPTIONS=
ls: cannot access /u01/oracle/user_projects/domains: No such file or directory
ls: cannot access /u01/oracle/user_projects/domains/*: No such file or directory
@[2019-05-02T08:01:53.557 UTC][startServer.sh:159] Error: No config.xml found at DOMAIN_HOME/config/config.xml or DOMAIN_HOME/*/config/config.xml, DOMAIN_HOME='/u01/oracle/user_projects/domains'. Check your 'domainHome' setting in your WebLogic Operator Domain resource, and your pv/pvc mount location (if any).
[root@centos7-ad3-1 wls-k8s-operator]#

**Comment by shean-guangchang** [comment]
Please describe what is the objective above? Are you following any doc or using any sample scripts?
 Is this in a multi-node env like before?

**Comment by shaunxa** [comment]
The simple objective is to get familiarize override and I started with the simplest thing first. I follow the user guide which is not as good as the quick start. Please kindly share some handy sample. And yes, I used the  multi-node env like before and execute all the steps under 'root'. Thanks.

**Comment by shean-guangchang** [comment]
What is the domain.yaml look like before the override?  Can you share your override.yaml?

**Comment by mriccell** [comment]
@shaunxa what configuration filed are you overriding?

**Comment by shaunxa** [comment]
Here is the domain.yaml

[root@centos7-ad3-1 sample-domain1]# cat domain.yaml | grep -v '#'

apiVersion: "weblogic.oracle/v3"
kind: Domain
metadata:
  name: sample-domain1
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: sample-domain1
spec:
  domainHome: /u01/oracle/user_projects/domains/sample-domain1
  domainHomeInImage: true
  image: "domain-home-in-image:12.2.1.3"
  imagePullPolicy: "IfNotPresent"
  webLogicCredentialsSecret:
    name: sample-domain1-weblogic-credentials
  includeServerOutInPodLog: true
  serverStartPolicy: "IF_NEEDED"
  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m "
  adminServer:
    serverStartState: "RUNNING"
    adminService:
      channels:
       - channelName: default
         nodePort: 30701
  clusters:
  - clusterName: cluster-1
    serverStartState: "RUNNING"
    replicas: 2
[root@centos7-ad3-1 sample-domain1]#

**Comment by shaunxa** [comment]
and config override file

[root@centos7-ad3-1 simpleoverride]# cat config.xml
<?xml version='1.0' encoding='UTF-8'?>
<d:domain xmlns:d="http://xmlns.oracle.com/weblogic/domain"
          xmlns:f="http://xmlns.oracle.com/weblogic/domain-fragment"
          xmlns:s="http://xmlns.oracle.com/weblogic/situational-config" >
  <d:log>
    <d:name>sample-domain1</d:name>
    <d:file-name>sample-domain1-override.log</d:file-name>
  </d:log>
</d:domain>
[root@centos7-ad3-1 simpleoverride]#

**Comment by shaunxa** [comment]
and config override file - to override the log file of the admin server

[root@centos7-ad3-1 simpleoverride]# cat config.xml
<?xml version='1.0' encoding='UTF-8'?>
<d:domain xmlns:d="http://xmlns.oracle.com/weblogic/domain"
          xmlns:f="http://xmlns.oracle.com/weblogic/domain-fragment"
          xmlns:s="http://xmlns.oracle.com/weblogic/situational-config" >
  <d:log>
    <d:name>sample-domain1</d:name>
    <d:file-name>sample-domain1-override.log</d:file-name>
  </d:log>
</d:domain>
[root@centos7-ad3-1 simpleoverride]#
[root@centos7-ad3-1 simpleoverride]#

**Comment by shaunxa** [comment]
[root@centos7-ad3-1 wls-k8s-operator]# cat override.yaml
apiVersion: "weblogic.oracle/v2"
kind: Domain
metadata:
  name: sample-domain1
  namespace: sample-domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: sample-domain1
spec:
  webLogicCredentialsSecret:
    name: sample-domain1-weblogic-credentials
  configOverrides: sample-domain1-cm

[root@centos7-ad3-1 wls-k8s-operator]#

**Comment by tbarnes-us** [comment]
Overriding a log file name isn't supported since log file locations are controlled by the domain yaml configuration. Instead, you can set log locations using the domain yaml (which in turn happens cause the Operator to generate an internal override file).  

See the '[configuration overrides documentation](https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/configoverrides/)' for a discussion of supported and unsupported overrides.  Also, since you're first learning, I strongly recommend following each step in this documentation's 'step-by-step' guide.

Hope this helps,
Tom

**Comment by shaunxa** [comment]
@tbarnes-us Thank you for your advise. I will take the approach and do it again. Thanks.

Cheers,
Shaun

**Comment by rjeberhard** [comment]
Did this resolve your issue?

**Comment by shaunxa** [comment]
@rjeberhard Thank you for your follow-up. Apparently it was my mistake. Changing log file is not supported. I will close it. Thanks.
