### ISSUE TITLE
JConsole connection fails

### ISSUE THREAD

**Issue by lurodrig** [oracle/weblogic-kubernetes-operator#107]
Hello there,

Has anybody tried to connect jconsole, or any other monitoring tool jmx compliant, to your servers?

My **client** startup command line looks like this:

`$JAVA_HOME/bin/jconsole -J-Djava.class.path=$JAVA_HOME/lib/jconsole.jar:$JAVA_HOME/lib/tools.jar:$WLS_HOME/wlserver/server/lib/wljmxclient.jar:$WLS_HOME/wlserver/server/lib/wlclient.jar -J-Djmx.remote.protocol.provider.pkgs=weblogic.management.remote -debug`

The remote **URL** process:

`service:jmx:t3://public_address:30012/jndi/weblogic.management.mbeanservers.runtime`

The **K8S setup** (big thanks @antonionappi88 !) looks like [this one](https://cdn.app.compendium.com/uploads/user/e7c690e8-6ff9-102a-ac6d-e4aebca50425/d7eaeb73-4b9e-4764-ad10-b5785d99d114/Image/4b0755417a0ada6fb9f167175cda3365/figure3.png)

`svc/domain1-admin-server-extchannel-t3channel   10.21.247.112   <nodes>       30012:30012/TCP     2d`

In the **AdminServer** there is a **custom channel** configured (At the end of the issue you can find its full configuration):

`[MBeanServerInvocationHandler]com.bea:Name=T3Channel,Type=NetworkAccessPoint,Server=admin-server`

The good and old **jconsole output** tells me something like this:

`Feb 21, 2018 6:30:31 PM com.sun.corba.se.impl.orb.ORBImpl checkShutdownState
WARNING: "IOP01600004: (BAD_INV_ORDER) ORB has shutdown"
org.omg.CORBA.BAD_INV_ORDER:   vmcid: OMG  minor code: 4  completed: No
.../...
Caused by: javax.naming.NamingException: Couldn't resolve initial reference: NameService after 1 failures [Root exception is org.omg.CORBA.COMM_FAILURE:   vmcid: SUN  minor code: 208 completed: Maybe]
.../...
Caused by: java.io.IOException: End-of-stream`

In the other hand I can connect with **wlst**:

`wls:/offline> connect('weblogic','welcome1','t3://public_address:30012');
Connecting to t3://130.61.34.144:30012 with userid weblogic ...
Successfully connected to Admin Server "admin-server" that belongs to domain "base_domain".`
 
Any thoughts on this?

Thanks in advance,

Luis

```
 wls:/base_domain/serverConfig/Servers/admin-server/NetworkAccessPoints/T3Channel> ls()

-r--   AcceptBacklog                                300
-r--   AllowUnencryptedNullCipher                   false
-r--   ChannelIdentityCustomized                    false
-r--   ChannelWeight                                50
-r--   Ciphersuites                                 null
-r--   ClientCertificateEnforced                    false
-r--   ClientInitSecureRenegotiationAccepted        false
-r--   ClusterAddress                               130.61.34.144
-r--   CompleteMessageTimeout                       60
-r--   ConnectTimeout                               0
-r--   CustomIdentityKeyStoreFileName               /shared/domain/base_domain/security/ITDB.jks
-r--   CustomIdentityKeyStorePassPhrase             ******
-r--   CustomIdentityKeyStorePassPhraseEncrypted    ******
-r--   CustomIdentityKeyStoreType                   jks
-r--   CustomPrivateKeyAlias                        null
-r--   CustomPrivateKeyPassPhrase                   ******
-r--   CustomPrivateKeyPassPhraseEncrypted          ******
-r--   DynamicallyCreated                           false
-r--   Enabled                                      true
-r--   HostnameVerificationIgnored                  false
-r--   HostnameVerifier                             null
-r--   HttpEnabledForThisProtocol                   true
-r--   Id                                           0
-r--   IdleConnectionTimeout                        65
-r--   InboundCertificateValidation                 BuiltinSSLValidationOnly
-r--   ListenAddress                                domain1-admin-server
-r--   ListenPort                                   30012
-r--   LoginTimeoutMillis                           5000
-r--   MaxBackoffBetweenFailures                    10000
-r--   MaxConnectedClients                          2147483647
-r--   MaxMessageSize                               10000000
-r--   MinimumTLSProtocolVersion                    null
-r--   Name                                         T3Channel
-r--   Notes                                        null
-r--   OutboundCertificateValidation                BuiltinSSLValidationOnly
-r--   OutboundEnabled                              false
-r--   OutboundPrivateKeyAlias                      null
-r--   OutboundPrivateKeyEnabled                    false
-r--   OutboundPrivateKeyPassPhrase                 null
-r--   PrivateKeyAlias                              null
-r--   PrivateKeyPassPhrase                         null
-r--   Protocol                                     t3
-r--   ProxyAddress                                 null
-r--   ProxyPort                                    80
-r--   PublicAddress                                130.61.34.144
-r--   PublicPort                                   30012
-r--   ResolveDNSName                               false
-r--   SDPEnabled                                   false
-r--   SSLv2HelloEnabled                            true
-r--   Tags                                         null
-r--   TimeoutConnectionWithPendingResponses        false
-r--   TunnelingClientPingSecs                      45
-r--   TunnelingClientTimeoutSecs                   40
-r--   TunnelingEnabled                             false
-r--   TwoWaySSLEnabled                             false
-r--   Type                                         NetworkAccessPoint
-r--   UseFastSerialization                         false

-r-x   freezeCurrentValue                           Void : String(attributeName)
-r-x   getInheritedProperties                       String[] : String[](propertyNames)
-r-x   isInherited                                  Boolean : String(propertyName)
-r-x   isSet                                        Boolean : String(propertyName)
-r-x   unSet                                        Void : String(propertyName)
```

**Comment by tbarnes-us** [comment]
Hi Luis,

The `$WLS_HOME/wlserver/server/lib/wlclient.jar` is deprecated as of 12.2.1.3.   It's called the "WebLogic thin IIOP client jar", and uses IIOP over the network even when you specify a T3 URL.    I suspect there's a way to make it work (I vaguely recall there's a WebLogic RMI command line system property that modifies IIOP behavior to make it easier for it to punch through firewalls - something to do with preventing the server from attempting to connect back to the client), but vetting it is currently a lower priority since its deprecated.    

So would you be fine with trying out the "thin t3 jar" instead?    To use it, set your classpath to `$WLS_HOME/wlserver/server/lib/wlthint3client.jar`.     (Don't also include the wljmxclient.jar in the same classpath as the t3-thin-client jar -- that's already embedded in the the t3 jar IIRC.)      If you're concerned about the size of the t3 jar, the t3 thin jars from pre-12.2.1 WL should also work and should be much smaller - IIRC the jar expanded hugely in 12.2.1 when it pulled in a ton of open source classes...

For thin client details see [Overview of Standalone Clients](https://docs.oracle.com/middleware/12213/wls/SACLT/basics.htm#SACLT117).

Hope this helps,
Tom

**Comment by lurodrig** [comment]
Hello @tbarnes-us ,

Thank you very much, `$WLS_HOME/wlserver/server/lib/wlthint3client.jar` works like a charm, great!

My command line now looks like this:

`$JAVA_HOME/bin/jconsole -J-Djava.class.path=$JAVA_HOME/lib/jconsole.jar:$JAVA_HOME/lib/tools.jar:$WLS_HOME/wlserver/server/lib/wlthint3client.jar -J-Djmx.remote.protocol.provider.pkgs=weblogic.management.remote -debug`

Thanks!

Cheers,

Luis
