### ISSUE TITLE
How to add a new cluster to an active domain that the operator can manage?

### ISSUE THREAD

**Issue by creativefre** [oracle/weblogic-kubernetes-operator#1070]
Hi,
I've setup kubernetes weblogic with the sample domain-home-on-pv. There is now one cluster active, "cluster-1" and 5 managed servers can be activated by changing the domain.yaml.

It's possible to add a new cluster or managed server resource by using the admin console or wlst online edit. But when I change the general domain.yaml file of the domain to activate the new cluster, the operator does not know the cluster and does not activate the new created server.

When you setup everything with the sample script, It is possible to change the wlst create-domain.py script in the beginning and adding new clusters/managed servers so the operator knows the changes, so it's possible to activate these clusters when you change the domain.yaml.

Now my question is, What's the best way to add a new cluster without restarting your admin server or reinstalling everything with a different configuration? How to let the operator know that I've added a new cluster so he can manage it?

**Comment by tbarnes-us** [comment]
Hi,

There's no Operator support for dynamically adding a cluster without restarting the entire domain.  As an alternative, it's often viable to simply pre-configure resources and simply choose not to activate them until you need them.

Can you describe your use case in detail?  It's been my assumption that there's a fairly common request to improve operator support for dynamic 'minor' changes (set or an attribute, etc), but this is the first I've heard of a desire to support adding entire clusters to an existing running domain dynamically.

For more information see:

- https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/configoverrides/ 

- https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-lifecycle/
 
- https://oracle.github.io/weblogic-kubernetes-operator/userguide/cicd/

**Comment by creativefre** [comment]
Hello, thanks for the reply.

I'm currently doing an internship for a company (Cronos) in Belgium. We are researching the possibilities around running weblogic in kubernetes. This company also want to use this feature in the future. The operator already has great functionality and support. But our use case is running and configuring even after the domain is setup, for example adding a new cluster or added a standalone managed server, without downtime. (Like the classical way it's possible by weblogic). 
It's important for the company because they have clients running weblogic that maybe after a month want a different configuration. So it would be useful if you don't know the right setup from the beginning to dynamically configure it after a certain time.

So this would be a great and highly demandable enhancement request for the future.
