### ISSUE TITLE
remove the limitation to set 777 mode for host folder of PV

### ISSUE THREAD

**Issue by lilyhe123** [oracle/weblogic-kubernetes-operator#1083]
This step can be easily missing by customer and results in errors and it raises a security risk with a 777-mode host folder. So it's better we can remove this step.

To achieve this, we can first use root user to create the domainHome and then change the proper owner and mode for the domainHome. This can be done both via `docker run` or a k8s job.

**Comment by anpanigr** [comment]
We can use the restrictive permission 770 if we annotate pv as follows 
kubectl annotate pv -n domain-namesapce  $pv_name pv.beta.kubernetes.io/gid=$gid

where gid (`id -g`) refer to Group ID of the current user

Refer  to https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/persistent-storage/#persistent-volume-gid-annotation

**Comment by lilyhe123** [comment]
imho, 770 is still a kind of compromise and it's not preferable in many case, e.g. sometimes we wants 755 or even 700.
Ideally we want to remove the dependency on the permission setting of the host folder.

**Comment by tbarnes-us** [comment]
@TheFrogPad FYI Hi Craig, I recall that you've looked into this?

**Comment by TheFrogPad** [comment]
Hi @lilyhe123, the file permissions have much to do with the overall setup an may involve the way the volume is handled in Kubernetes. I would not suggest any world permissions for a domain home in a production environment and as for user or group permission, the way the docker image is built has impact as well.

You can look at https://github.com/oracle/weblogic-kubernetes-operator/pull/1054#discussion_r279071200 for some context. These came when @tbarnes-us inquired about the documentation that @anpanigr references was being added.

In a nutshell, even if you use the Kubernetes security context to change UID or even GID you run up against how the WebLogic Docker image protects files to UID 1000 only. As such the file permission handling is really not something the operator alone can address and assuming the volumes/images are created as desired then the Domain CRD allows specifying the Kubernetes security context.

More information on the security context see https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#discussion in the Kubernetes documentation.

**Comment by lilyhe123** [comment]
The common approach is via `initContainer`.

Add an init container as below in the domain creation job to set the proper file permission, instead of the manual step.

```
initContainers:
  - name: init-chown-data
    image: busybox:1.30
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'chown -R 1000:1000 /shared']
...
```

**Comment by TheFrogPad** [comment]
The use of `initContainers` may be fine for some environments but will likely be ineffective if your cluster does not allow containers to run as `root` or if `root` does not have permissions with NFS volume mounts.

Another reasonable alternative that customers have used is the Kubernetes annotation `pv.beta.kubernetes.io/gid` for the `PersistentVolume` as this will establish a GID for file access.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control

**Comment by lilyhe123** [comment]
@TheFrogPad you are right. It's better to let customer choose whatever they want.
