### ISSUE TITLE
Managed Servers fail to start with weblogic.descriptor.BeanAlreadyExistsException: Bean already exists

### ISSUE THREAD

**Issue by bikramjeet77** [oracle/weblogic-kubernetes-operator#1091]
Hi,

I  have been testing the k8 weblogic operator and have been running into the following issue.

Any help will be greatly appreciated.

I used the create_domain.sh script at kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image as per the quickstart instructions documented at https://oracle.github.io/weblogic-kubernetes-operator/quickstart/get-images/.

The weblogic operator was installed successfully. I was also able to run the create-domain.sh script and applied the yaml config to create servers and domains.

Admin server is running successfully and I can even open the admin console url fine.

The managed servers are failing with the following error.

The following is from one of the managed servers logs:

<May 30, 2019 3:52:57 PM GMT> <INFO> <NodeManager> <Starting WebLogic server with command line: /usr/java/default/bin/java -Dweblogic.Name=managed-server1 -Dbea.home=/u01/oracle/wlserver/.. -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy -Dweblogic.management.server=http://sample-domain1-admin-server:7001 -Djava.library.path=::/u01/oracle/wlserver/server/native/linux/x86_64:/u01/oracle/wlserver/server/native/linux/x86_64/oci920_8:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -Djava.class.path=/usr/java/default/lib/tools.jar:/u01/oracle/wlserver/server/lib/weblogic.jar:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/ant-contrib-1.0b3.jar:/u01/oracle/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/u01/oracle/wlserver/..:/u01/oracle/wlserver/modules/features/oracle.wls.common.grizzly.jar -Dweblogic.system.BootIdentityFile=/u01/oracle/user_projects/domains/sample-domain1/servers/managed-server1/security/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -Dweblogic.nmservice.RotationEnabled=true -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dweblogic.Stdout=/u01/oracle/user_projects/domains/sample-domain1/servers/managed-server1/logs/managed-server1.out -Dweblogic.StdoutDebugEnabled=false weblogic.Server >

<May 30, 2019 3:52:57 PM GMT> <INFO> <NodeManager> <Working directory is '/u01/oracle/user_projects/domains/sample-domain1'>

<May 30, 2019 3:52:57 PM GMT> <INFO> <NodeManager> <Server output log file is '/u01/oracle/user_projects/domains/sample-domain1/servers/managed-server1/logs/managed-server1.out'>

<May 30, 2019 3:52:58 PM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.> 

<May 30, 2019 3:52:58 PM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>

<May 30, 2019 3:52:59 PM GMT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.211-b12 from Oracle Corporation.>

<May 30, 2019 3:52:59 PM GMT> <Info> <RCM> <BEA-2165021> <\"ResourceManagement\" is not enabled in this JVM. Enable \"ResourceManagement\" to use the WebLogic Server \"Resource Consumption Management\" feature. To enable \"ResourceManagement\", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.> 

<May 30, 2019 3:52:59 PM GMT> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.3.0 Thu Aug 17 13:39:49 PDT 2017 1882952>

<May 30, 2019 3:52:59 PM GMT> <Warning> <Management> <BEA-141286> The creation of the dynamic server failed with an exception.

weblogic.descriptor.BeanAlreadyExistsException: Bean already exists: \"weblogic.management.configuration.ServerMBeanImpl@4ff6b97e([sample-domain1]/Servers[managed-server1])\".\n\tat weblogic.descriptor.internal.ReferenceManager.registerBean(ReferenceManager.java:322)\n\tat weblogic.management.configuration.DomainMBeanImpl.setServers(DomainMBeanImpl.java:1737)\n\tat weblogic.management.configuration.DomainMBeanImpl.addServer(DomainMBeanImpl.java:1672)\n\tat weblogic.management.configuration.DomainMBeanImpl.createServer(DomainMBeanImpl.java:1763)\n\tat weblogic.management.provider.internal.DynamicServersProcessor.updateConfiguration(DynamicServersProcessor.java:92)\n\tat weblogic.management.provider.internal.RuntimeAccessImpl.initialize(RuntimeAccessImpl.java:430)\n\tat weblogic.management.provider.internal.RuntimeAccessService.start(RuntimeAccessService.java:72)\n\tat weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)\n\tat org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)\n\tat org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)\n\tat org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)\n\tat org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)\n\tat org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)\n\tat org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)\n\tat org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)\n\tat org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:698)\n\tat org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:78)\n\tat org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:212)\n\tat org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:235)\n\tat org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)\n\tat org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)\n\tat org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)\n\tat org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)\n\tat org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)\n\tat org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)\n\tat org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)\n\tat org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)\n\tat org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748

**Comment by bikramjeet77** [comment]
I also see that even though I chose to configure to create only 1 managed server in the domain.properties config file, weblogic operator still tries to configure and create all the 5 managed servers. I made sure that I set configuredManagedServerCount: 1 and  initialManagedServerReplicas: 1.

**Comment by bikramjeet77** [comment]
After recreating domain and keeping both configuredManagedServerCount: and initialManagedServerReplicas  the same made it to work.

**Comment by senthil13** [comment]
+1 I too have the same issue. (weblogic.descriptor.BeanAlreadyExistsException: Bean already exists:  )

**Comment by lennyphan** [comment]
@bikramjeet77 and @senthil13 I'm investigating and am trying to reproduce this issue.

**Comment by lennyphan** [comment]
@bikramjeet77 and @senthil13   can you tell me what weblogic image you are using?  e.g.

bash-3.2$ docker images
REPOSITORY                            TAG                   IMAGE ID            CREATED             SIZE

store/oracle/weblogic                 12.2.1.3              12c456a86afb        4 months ago        1GB

**Comment by lennyphan** [comment]
@bikramjeet77 and @senthil13  can you also verify that the WebLogic docker image you're using is the 'latest' from the Oracle Container Registry?  The latest image has the necessary patches needed to run with WebLogic Operator.  More information on how to pull the latest WebLogic docker image and to verify the necessary patches can be found in https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-in-image/base-images/#obtaining-standard-images-from-the-oracle-container-registry

The patch list should contain the following:

29135930;One-off
27117282;One-off
26355633;One-off
26287183;One-off
26261906;One-off
26051289;One-off

**Comment by senthil13** [comment]
@lennyphan - thanks for the response. Please find the details

Weblogic version

```
WebLogic Server 12.2.1.3.0 Thu Aug 17 13:39:49 PDT 2017 1882952

Use 'weblogic.version -verbose' to get subsystem information

Use 'weblogic.utils.Versions' to get version information for all modules

```

Patches list 

```
29016089;WLS PATCH SET UPDATE 12.2.1.3.190416
26355633;One-off
26287183;One-off
26261906;One-off
26051289;One-off

OPatch succeeded.
```
I guess we are missing these two patches, but we have super set of this 29016089, does this make any different. 

29135930;One-off
27117282;One-off

So not using the correct version of patches causing the bean already exist issue ?

**Comment by lennyphan** [comment]
@bikramjeet77 and @senthil13,  yes these are all individual (one-off) patches that are necessary as the Operator can dynamically apply property updates (customizations) to WLS managed servers using a feature called 'config overrides': 

https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/configoverrides/

The missing patches resolve the "weblogic.descriptor.BeanAlreadyExistsException: Bean already exists: " exceptions during startup.

Please pull the latest WebLogic docker image and give it a try.

**Comment by mriccell** [comment]
The pre-built WebLogic images in Oracle Container Registry or Docker Store are already patched.  Please take a look at the documentation of how to pull the WebLogic image from OCR  https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-in-image/base-images/.

**Comment by senthil13** [comment]
@mriccell @lennyphan  - My issue issue is resolved and thanks to both. I only installed `29135930;One-off`
as the other patch is a subset.
```OPatch found that the following patch(es) are not required.
They are either subset of the patches in Oracle Home (or) subset of the patches in the given list:
 [ 27117282 ]```

My current path level is 

```29135930;One-off
29016089;WLS PATCH SET UPDATE 12.2.1.3.190416
26355633;One-off
26287183;One-off
26261906;One-off
26051289;One-off````
