### ISSUE TITLE
What is the expected behavior of the pods of admin-server and managed-server when the worker node stopped / crashed?

### ISSUE THREAD

**Issue by shaunxa** [oracle/weblogic-kubernetes-operator#1098]
I tried to understand the behavior of the wls domain in the production incidents like the worker compute crash. I simulated the situation by stopping the compute in oci console. I observed different behavior between admin-server and managed-server pods and others like traefik, weblogic-operator and mysql. Here are their behaviors:

1. admin-server and managed-server pods changed to 'Unknown' about 5 minutes after the computed stopped. They remained at 'Unknown' state until the compute restarted. After the compute restarted and the node became 'Ready', the pods changed to 'Terminating' and then 'Running' on the same node.  

2. While others, like traefik, weblogic-operator and mysql pods, changed to 'Unknown' about 5 minutes after the computed stopped and a new pod started on an available nodes. The initial pods remained at 'Unknown' state until the compute restarted. After the compute restarted and the node became 'Ready', the initial pods changed to 'Terminating' and then disappeared (Terminated).  

I am wondering that is the expected behavior of admin-server and managed-server pods in k8s. Please help advise and confirm.

Here is the details of the setup and let me know if more details needed. Thanks.

(managed) k8s with 3 nodes on OCI and the end-to-end weblogic app deployment including traefik as reverse proxy and mysql.

$ kubectl get nodes
NAME        STATUS   ROLES   AGE   VERSION
10.0.10.2   Ready    node    20d   v1.12.7
10.0.11.2   Ready    node    20d   v1.12.7
10.0.12.2   Ready    node    20d   v1.12.7

wls domain (domain1) on pv using NFS. The operator is oracle/weblogic-kubernetes-operator:2.1.

$ kubectl get pods -n domain1-ns -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP            NODE        NOMINATED NODE
domain1-admin-server      1/1     Running   5          10h   10.244.1.71   10.0.12.2   <none>
domain1-managed-server1   1/1     Running   0          9h    10.244.2.50   10.0.11.2   <none>
domain1-managed-server2   1/1     Running   0          9h    10.244.0.81   10.0.10.2   <none>
domain1-managed-server3   1/1     Running   0          9h    10.244.1.72   10.0.12.2   <none>

$ kubectl get po --all-namespaces -o wide | grep -e 'mysql' -e 'domain1' -e 'traefik' -e 'operator'
default                       mysql-6b698dfcbb-cts8f                    1/1     Running   0          10h   10.244.0.80   10.0.10.2   <none>
domain1-ns                    domain1-admin-server                      1/1     Running   5          10h   10.244.1.71   10.0.12.2   <none>
domain1-ns                    domain1-managed-server1                   1/1     Running   0          10h   10.244.2.50   10.0.11.2   <none>
domain1-ns                    domain1-managed-server2                   1/1     Running   0          10h   10.244.0.81   10.0.10.2   <none>
domain1-ns                    domain1-managed-server3                   1/1     Running   0          10h   10.244.1.72   10.0.12.2   <none>
sample-weblogic-operator-ns   weblogic-operator-587fb5c45-6b7z6         2/2     Running   0          24h   10.244.0.70   10.0.10.2   <none>
traefik                       traefik-operator-799844bff7-6zcgv         1/1     Running   0          22h   10.244.2.48   10.0.11.2   <none>
traefik                       traefik-operator-799844bff7-b9xq6         1/1     Running   0          24h   10.244.0.72   10.0.10.2   <none>
[opc@centos7-ad1-ws ~]$

**Comment by bryantidd** [comment]
This is a great question and one that I've been working on as well. The answer is just as you described, It's application specific. This is because node outage, storage outage, etc. will affect each application differently. The application may still be working and making a blanket policy of restarting the workloads of that failed node could cause a split-brain scenario. The application owner has to decide how best to resolve such matters. This may include force detachment of volumes, and force deletion of pods on failed nodes. In that case workloads will be rescheduled, etc. This is important if the node will not be recovered.

**Comment by shaunxa** [comment]
@bryantidd agree with you and thank you for your comments.
