### ISSUE TITLE
Templatized cluster members

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#1108]
The requirement is to allow specification at the cluster level for templatized configuration of member servers.  The initial request was for a use case like as for Kubernetes StatefulSets, where each member server would mount its own persistent volume and where the relationship between a certain member and the persistent volume / claim would be stable over time (e.g. managed server "managed-server5" would mount "persistent-volume-5" consistently.)

We now believe that persistent volumes (and claims and mounts) are only the initial use case and that templatization was desirable for other features, including node selectors, labels, or possibly for any string-typed field.

The current support is not templatized and includes:

- Cluster level configuration of volumes (claims, mounts) and other features (labels, annotations, resources, node selectors, etc.)
- Managed-server level configuration of the same items with case-by-case merging with or overriding of the cluster level configuration.

The initial customer suggestion was for new fields, such as `.spec.clusters.[<cluster-name>.persistentvolumetemplates]`.  This is most similar to StatefulSets, which have a field for volumeClaimTemplates, where the volume claim template specifies a base name that is always used to build a volume claim name of `<base-name>-<replica-ordinal>`.  We propose preserving the existing domain resource schema, but allow for the use of `"$<variable-name>"` type entries on a string-typed field, with support for a constrained set of variables names, such as SERVER_NAME, DOMAINUID, DOMAIN_NAME, etc.  Since Kubernetes names can only include lowercase characters, `"."`, and `"."`, we know that `"$"` and uppercase characters will always represent an intentional variable replacement.

This feature is ready when:

    The changes to schema, including semantic details as described here, are reviewed and agreed
    Implementation including unit-tests
    User documentation updated

**Comment by bryantidd** [comment]
This requirement reads as suggested in previous discussions. Would you mind supplying an example or two of how the "$<variable-name>" would be used. Thank you.

**Comment by rjeberhard** [comment]
@bryantidd, there is some other support currently limited to env. variables where variables can contain a "$(<variable-name>)" value, where the variable name has to come from a pre-defined set, such as DOMAIN_NAME or SERVER_NAME.  If we say that the format for this issue is also "$(<variable-name>)" then I could extend the current functionality to cover more or all string-typed fields.  This would let you have something like this:

spec:
  clusters:
  - name: cluster-1
    serverPod:
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: myclaim-$(SERVER_NAME)

Thoughts?

**Comment by bryantidd** [comment]
Looks great. I like that it would provide a clear understanding of what should be expected for PVCs created, etc.
