### ISSUE TITLE
Cluster and member startup ordering

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#1109]
The requirement is to allow specification of a startup ordering for clusters and managed servers, similar in intent to "deployment ordering" of applications.  For instance, customers may deploy a JMS store targeted to one cluster while the MDB's are deployed targeted to another cluster.  It's important in such a case that the first cluster is up and running before the second cluster begins to initialize.  This is an example of operational details that customers have had to implement themselves prior to the existence of tools such as this operator.

Our analysis of this requirement suggests that dependent clusters (such as the cluster with deployed MDB's) may either only need at least one cluster member available from the cluster on which is depends or may need all intended cluster members available.  This needs to be configured on the dependent cluster or server instance.

The current support does not include any such ordering configuration or guarantees:
- Admin server is presently started and operator waits until the admin server is ready before starting other servers
- Any other cluster member or managed server that is set to start will be started in parallel

The proposal is for two new fields, including "startupOrder", that is integer typed and "requireEarlierStartupOrderComplete", that is Boolean typed.  Just like deployment order, items with lower numbers are started and later items do not start until lower numbered items are ready, per the flag.

This story is done when:

    Implementation including unit-tests
    User documentation updated

**Comment by bryantidd** [comment]
As this reads the inheritance model for resources and ability to define these value at cluster, server, server instance level is still maintained. Is this correct? Thank you.

**Comment by tbarnes-us** [comment]
Interesting idea. 

See #operator slack thread https://oracle-weblogic.slack.com/archives/CE3M9DGSY/p1589297030185700 for where this has come up again.

Note that this naturally would also need a corresponding controlled _shutdown ordering_.

**Comment by tbarnes-us** [comment]
@rjeberhard Is this still an open issue?

**Comment by robertpatrick** [comment]
It seems to me that the primary use case for this requirement is to deal with cross application dependencies.  As such, I would propose a simpler model that simply allows the user to tell us what depends on what (e.g., startup order) and that we treat these all as `requireEarlierStartupOrderComplete=true` (and eliminate the ability to configure this).  I cannot think of a use case that requires startup ordering but where the earlier server/cluster does not need to be "available" before starting the next.

**Comment by tbarnes-us** [comment]
Hmmm. Some idle thoughts:

A more general solution would be an order between domains "inter domain", instead of clusters within a domain "intra domain". This strikes me as a fine way to handle the requirement, as it handles the more general case and, with acceptable difficulty, the "intra cluster" case (the presumably few customers that really need the feature to work "intra-domain" could break their domains up into multiple domains).

If we accept my premise that this Issue can be resolved with an "inter domain" feature, then this makes me wonder if this is Verrazzono project's territory. If I understand VZ correctly, one of its goals is to centrally handle the life-cycle of multiple related domains. Perhaps VZ already solves this problem?

**Comment by robertpatrick** [comment]
@tbarnes-us I think that the cross-domain scenario is out of WKO territory, as you point out.  I believe that we should support this cross-cluster functionality within a single domain.
