### ISSUE TITLE
Changes for configOverrides to domain object do not take affect without recreating domain object

### ISSUE THREAD

**Issue by bikramjeet77** [oracle/weblogic-kubernetes-operator#1139]
Hello,

We tried creating a new configmap and set that to the configOverrides property in the domain yaml config. We then applied those changes to the domain object (kubectl apply -f domain.yaml).

We also force restarted servers by updating the restartVersion field in the domain yaml config.

When admin server got restarted, it still did not have the configOverrides xml file deployed at optconfig subdir.

We had to recreate weblogic domain object by running,

kubectl delete domain foo -n bar
kubectl apply -f domain.yaml

Then the configOverrides changes take affect.

But this is not a good experience since we do not want to affect managed servers when making changes to admin server only but recreating weblogic domain object recreates domain and recreates admin server and managed server pods. 

Could we be missing something in how we are configuring this change or is it that the weblogic operator might be reading domain config from cache ??

**Comment by bikramjeet77** [comment]
Pinging to see if you have any comments/suggestions ?

**Comment by tbarnes-us** [comment]
Hi - 

You're not missing anything - if a domain is running, then a domain restart is required for the operator to load new/changed configuration overrides.  This requirement is documented in the operator's override's documentation ([https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/configoverrides/)](https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/configoverrides/)), and it's also mentioned in the recent overrides blog  ([https://blogs.oracle.com/weblogicserver/portable-weblogic-domains-using-kubernetes-operator-configuration-overrides](https://blogs.oracle.com/weblogicserver/portable-weblogic-domains-using-kubernetes-operator-configuration-overrides)).

Note that there are less cumbersome ways to restart a domain other than deleting and recreating a domain resource.  For example, you can use 'kubectl patch' to change the Domain resources 'serverStartPolicy' to 'NEVER', which shuts down the domain, and then use it again to bring it back to 'IF_NEEDED'.  For example ```kubectl patch domain $name -n $namespace -p '{"spec":{"serverStartPolicy":"NEVER"}}' --type merge```.   See the operator's server life cycle documentation for more info ([https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-lifecycle/](https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-lifecycle/)).

As for having the operator help with dynamic WebLogic configuration changes to a running WL domain, the operator dev team is currently working on enhancements in this area. In the mean-time, you can still leverage WebLogic's existing dynamic configuration change support that doesn't depend on the Operator.  E.g. use standard long existing approaches such as the WebLogic admin console or on-line WLST to make the change.  But note that there are a number of (hopefully fairly intuitive) caveats:
- If you're domain home is stored in an image, then these changes will disappear if/when you cycle you're admin pod.
- As usual, WL will only dynamically handle console/WLST-on-line changes that it can normally handle dynamically when the operator isn't involved.  For example, an mbean attribute for a resource on a running WL server won't change dynamically unless it's already documented as dynamic.
- The operator won't detect and handle WL configuration changes that affect the domain topology as it currently only 'introspects' configuration just before it starts the first server in a domain.  This means that on-line WLST/console changes that add or remove servers/clusters/network-channels won't be handles, and the operator won't know that it needs to support new pods/services for added resources or that it needs to delete services for removed resources.
- You should not make dynamic changes to configuration that the operator is going to override for you.   E.g. your custom situational configuration, network addresses, log home location, etc.

Hope this helps!

**Comment by bikramjeet77** [comment]
Thanks for a very detailed explanation. This was very helpful.
