### ISSUE TITLE
apache-webtier charts do not handle imagePullSecret

### ISSUE THREAD

**Issue by sczachariah** [oracle/weblogic-kubernetes-operator#1158]
apache-webtier charts present here - "https://github.com/oracle/weblogic-kubernetes-operator/tree/release/2.2.1/kubernetes/samples/charts/apache-webtier" do not handle "imagePullSecrets" in the deployment.yaml template file.

Kindly let know if this can be fixed.

**Comment by simon-meng-cn** [comment]
Yes. It can be fixed.

**Comment by sczachariah** [comment]
Let me know if I can raise a PR for the same.

**Comment by markxnelson** [comment]
Yes please do

⁣
Mark Nelson
Architect
https://weblogic.cafe
1 (972) 963-9435

Visit https://bit.ly/2QwRWZY to join our public WebLogic slack​
