### ISSUE TITLE
 permission denied

### ISSUE THREAD

**Issue by mnemonic01** [oracle/weblogic-kubernetes-operator#1161]
I still have this issue when rolling out a WebLogic or FMW domain, that when creating it uses uid 1000, the same as the cloud OPC user, so pod creating ends up in permission denied. Do you have solution for this?

Michel

**Comment by mnemonic01** [comment]
Still no solution for this?

**Comment by markxnelson** [comment]
You might need to provide just a little more detail in order for us to help you.  Like what version of the operator are you using, what version of Kubernetes, what kind of domain, and so on.
From what you have said, I would guess that your Kubernetes is set up with a pod security policy that is causing the pod to be run with a different UID, and that is why it cannot read the files owned by UID 1000.

**Comment by mnemonic01** [comment]
Hi Mark
I use OKE so version of k8s is v1.12.7, what OCI provides when I use OKE
Try to set up a SOA Suite domain on OKE. I use the official Oracle SOA Suite 12.2.1.3 from Oracle's container registry container-registry.oracle.com/middleware/soasuite:12.2.1.3
in this image the UID and GID are set to 1000 for oracle user, which is the similar UID for the OPC user on OCI. I suspect this is why I get permission denied when the phase of directiry creation is executed.
Is there a way to solve this?
Thanks

**Comment by markxnelson** [comment]
I would add a securityContext with user=1000 and fsGroup=1000 (or whatever the oracle user's default group is) -- see details here https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by rjeberhard** [comment]
@mnemonic01, the domain resource (domain.yaml) has an element, "serverPod", which lets you specify a select set of elements that will be added to the pods the operator makes for WebLogic server instances.  The serverPod element supports the security context field that Mark mentioned.  So, your domain.yaml might have content like:

```
spec:
  serverPod:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
```

**Comment by mnemonic01** [comment]
> 
> 
> @mnemonic01, the domain resource (domain.yaml) has an element, "serverPod", which lets you specify a select set of elements that will be added to the pods the operator makes for WebLogic server instances. The serverPod element supports the security context field that Mark mentioned. So, your domain.yaml might have content like:
> 
> ```
> spec:
>   serverPod:
>     securityContext:
>       runAsUser: 1000
>       runAsGroup: 1000
>       fsGroup: 1000
> ```

Thanks, already tried it :)
