### ISSUE TITLE
Operator to watch ImageStream for new :latest tag

### ISSUE THREAD

**Issue by volkermauel** [oracle/weblogic-kubernetes-operator#1172]
Hey,

first of all, thanks for the project, so far it works really smoothly for me.
I'm trying to setup a CD-Pipeline with the operator in an OKD-Cluster (switching to OpenShift soon). The Building+Pushing part is handled by GitLab fine now, but I was wondering if a change to the ImageStreams :latest tag shouldn't cause a stopping of all pods and starting with the newest version of the Image.

If not, is this a planned change, or what would be the suggested path to go here?

My understanding was to keep the Image immutable, so i was going to build my domain in one layer with my desired settings and references to apps to deploy, then in the next layer, copy my ear-files into the image and finally, tag it twice, once with latest and once with a unique job-id so i can manually chose a time when to deploy my changes to production, but keep my test-environment at the newest version of my master-branch.

Thanks for your help!

**Comment by russgold** [comment]
If you change the image reference in the domain resource, the pods should do a rolling restart. Is this not happening for you? But if you are keeping the same image name, and replacing the image itself in docker, the operator will not notice.

**Comment by volkermauel** [comment]
That works correctly.
i switched my CI-pipeline to use 
`oc patch domain domain1 -p '{"spec":{"image":"docker-registry.default.svc:5000/my-weblogic-namespace/gitlab-master:${CI_JOB_ID}"}}' -v 100 --type=merge`

Thanks for your help!
