### ISSUE TITLE
helm install weblogic-operator failed with exception 

### ISSUE THREAD

**Issue by huxiaodongsjtu** [oracle/weblogic-kubernetes-operator#1187]
When we try to install weblogic-operator on openshift，got this exception below：
(Can you tell us what cause the exception? and how to fix it?)
{"timestamp":"08-15-2019T03:41:07.050+0000","thread":11,"fiber":"","domainUID":"","level":"WARNING","class":"oracle.kubernetes.operator.helpers.ClientPool","method":"getApiClient","timeInMillis":1565840467050,"message":"Exception thrown: {0}","exception":"\njava.lang.RuntimeException: java.security.cert.CertificateParsingException: java.io.IOException: Invalid encoded CertificateValidity, starting sequence tag missing.\n\tat io.kubernetes.client.ApiClient.applySslSettings(ApiClient.java:1153)\n\tat io.kubernetes.client.ApiClient.setSslCaCert(ApiClient.java:203)\n\tat io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:313)\n\tat io.kubernetes.client.util.Config.defaultClient(Config.java:107)\n\tat oracle.kubernetes.operator.helpers.ClientPool$DefaultClientFactory.get(ClientPool.java:102)\n\tat oracle.kubernetes.operator.helpers.ClientPool$DefaultClientFactory.get(ClientPool.java:95)\n\tat oracle.kubernetes.operator.helpers.ClientPool.getApiClient(ClientPool.java:75)\n\tat oracle.kubernetes.operator.helpers.ClientPool.create(ClientPool.java:57)\n\tat oracle.kubernetes.operator.helpers.ClientPool.create(ClientPool.java:24)\n\tat oracle.kubernetes.operator.helpers.Pool.take(Pool.java:28)\n\tat oracle.kubernetes.operator.helpers.CallBuilder$1.execute(CallBuilder.java:69)\n\tat oracle.kubernetes.operator.helpers.CallBuilder.executeSynchronousCall(CallBuilder.java:168)\n\tat oracle.kubernetes.operator.helpers.CallBuilder.readVersionCode(CallBuilder.java:162)\n\tat

**Comment by markxnelson** [comment]
We will look into it. What version of openshift are you using?

**Comment by rjeberhard** [comment]
We will also need to please know the version of the WebLogic operator.

**Comment by huxiaodongsjtu** [comment]
openshift version: v3.11.82, kubernetes version: v1.11.0+d4cacc0, WebLogic operator version: 2.2.1

**Comment by markxnelson** [comment]
Hi, Would it be possible to share the command you used to install the operator please, then helm command?  And/or the values.yaml file that you used.  I have not been able to reproduce this issue on our OpenShift 3.11 system.
