### ISSUE TITLE
Issue with Environment variables

### ISSUE THREAD

**Issue by Hawk-360** [oracle/weblogic-kubernetes-operator#1198]
Hi,

While looking at different ways I can get dynamic values inside domain I was trying to use Environment variable using value tag which worked flawlessly, Next in agenda was to try valueFrom tag so that I can use configmaps or Secrets as source of values but sadly it didn't work,

Looking at the Domain definition it looks like valueFrom should be picked if value tag is undefined or empty.
URL : https://github.com/oracle/weblogic-kubernetes-operator/blob/master/docs/domains/k8s1.13.5.md#env-var

Going through the code we discovered that following code only caters for value tags and ignores valueFrom

> class :- oracle.kubernetes.operator.helpers.PodHelper.java

 static List<V1EnvVar> createCopy(List<V1EnvVar> envVars) {
    ArrayList<V1EnvVar> copy = new ArrayList<>();
    if (envVars != null) {
      for (V1EnvVar envVar : envVars) {
        **copy.add(new V1EnvVar().name(envVar.getName()).value(envVar.getValue()));**
      }
    }
    return copy;
  }

Can you please suggest if this is a bug, or support is only limited to values tag at the moment.
Also it will be great if any one can suggest a way to access configmap( if that is not related to jdbc, jms, config.xml etc. ) or Secret inside the pods.

Regards,
Ishan.

**Comment by rjeberhard** [comment]
This was an oversight in that logic (read, "bug").  I'll make sure it gets corrected.

**Comment by rjeberhard** [comment]
Oh, you can also mount configmaps as volumes/volume mounts.  The keys will show up as files in the directory at the mount point with the files containing the values.
