### ISSUE TITLE
WebLogic Admin Console doesn't allow login via Traefik ingress

### ISSUE THREAD

**Issue by kavicse87** [oracle/weblogic-kubernetes-operator#1203]
Traefik ingress weblogic console doesn't allow me logging in.

1)Configured traefik igress for weblogic console  and I'm able to hit the console page from internet. 
2)But I couldn't logging into the console used the credentials that I've supplied through the domain.properties "myuser" "admin123".The default username "weblogic" and password "weblogic" also not working.
3) Attached the ingress file for admin service external url and the screenshot of the admin console page.

Note: I've created the domain image using WDT. So I had to use the domain.properties to the pass the user credentials while building the image.
---
admin-server-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: adminserver-service
  namespace: domain1-ns
spec:
  rules:
  - host: domain1.org.labs-babpip.walmartdigital.cl
    http:
      paths:
      - path: /console
        backend:
          serviceName: domain1-admin-server-external
          servicePort: 7001
========================================
ingress url : https://domain1.org.labs-babpip.walmartdigital.cl/console
===================================================
<img width="1233" alt="Screenshot 2019-08-21 at 3 12 34 PM" src="https://user-images.githubusercontent.com/37696884/63461396-8c1ca680-c426-11e9-8f4e-13c71f2f0b72.png">

**Comment by markxnelson** [comment]
HI, I think we need some extra config to make the console work through an ingress, I will ask the team for details, but in the mean time, are you sure you want to expose the console to the public internet? Have you considered using `kubectl port-forward` instead? So that you console access would be over an encrypted channel, and the console would only be available to people with access to your cluster?

**Comment by kavicse87** [comment]
Hi Mark, Thanks for your quick response. For the experiment purpose I wanna check this and I would do kubectl port-forward before I move it to pre prod and prod. First I want this should work so that we can do the demonstration with the stake holders. your help on this would be much appreciable and helpful too.

**Comment by markxnelson** [comment]
OK I understand.  I would say that using a node port is much easier to configure... is that an option?  If your worker nodes don't have public IP's then let me know.  I am trying to get in touch with our engineer who worked on setting this up with another customer a few months ago.

**Comment by markxnelson** [comment]
[console through traefik ingress.zip](https://github.com/oracle/weblogic-kubernetes-operator/files/3527278/console.through.traefik.ingress.zip)

**Comment by markxnelson** [comment]
ok I think I might see the issue.  I added a video just above of this working for me.

**Comment by kavicse87** [comment]
Yes, my worker nodes doesn't have public ips and no internet access too..

**Comment by markxnelson** [comment]
In your ingress you are pointing at the `external` service - in mine I point at the internal one, like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: "2019-04-11T15:55:02Z"
  generation: 2
  labels:
    weblogic.resourceVersion: domain-v2
  name: slim-traefik
  namespace: default
  resourceVersion: "19016233"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/slim-traefik
  uid: 2ad183ae-5c72-11e9-ab7b-000017024fa2
spec:
  rules:
  - host: mark.weblogick8s.org
    http:
      paths:
      - backend:
          serviceName: fat-admin-server
          servicePort: 7001
        path: /console
status:
  loadBalancer: {}
```

**Comment by markxnelson** [comment]
Then I hit it through traefik's node port, which is 30305 in my case - http://mark.weblogick8s.org:30305/console

**Comment by markxnelson** [comment]
```# k get svc | grep fat
fat-admin-server                     ClusterIP   None             <none>           30019/TCP,7001/TCP               43d
fat-admin-server-external            NodePort    10.102.228.136   129.146.29.109   30019:30019/TCP                  64d
fat-cluster-cluster-1                ClusterIP   10.103.190.237   <none>           8001/TCP                         64d
fat-managed-server1                  ClusterIP   None             <none>           8001/TCP                         43d
fat-managed-server2                  ClusterIP   None             <none>           8001/TCP                         43d
```

please excuse the name, i was testing our new "slim" images, and so i had "fat" and "slim" domains....

**Comment by kavicse87** [comment]
Hello Mark,

Thanks for the response! I'm trying this.. I wanted to make it clear.. were you able to login to the console using the domain user name and password credentials.. My issue is I'm able to hit & view the console page but couldn't login to the console using the domain properties credentials which we've used during the domain IMAGE and WDT image built..

**Comment by markxnelson** [comment]
Hi, yes I used those credentials. You need to use the same credentials when you run WDT as when you create the k8s secret. Maybe that is the issue?  You could try using WLST from inside the admin server pod to connect to the server to confirm the credentials work.

Something like: 
```
kubectl -n domain1-ns exec -ti domain1-admin-server /bin/bash 
./oracle_common/common/bin/wlst.sh
connect('weblogic','whatever','t3://localhost:7001')
```

**Comment by kavicse87** [comment]
Thanks for the clarification!!That one thing I should check. But i used
sealed secrests so i think I must try with the credentials which I've used
while creating that secret..

**Comment by markxnelson** [comment]
Yeah, they have to match - if you use different credentials when you create the image than the ones in the secret that are used to start it, you won't be able to get in :)

**Comment by v-2vikc** [comment]
> Hi, yes I used those credentials. You need to use the same credentials when you run WDT as when you create the k8s secret. Maybe that is the issue? You could try using WLST from inside the admin server pod to connect to the server to confirm the credentials work.
> 
> Something like:
> 
> ```
> kubectl -n domain1-ns exec -ti domain1-admin-server /bin/bash 
> ./oracle_common/common/bin/wlst.sh
> connect('weblogic','whatever','t3://localhost:7001')
> ```

I tried with the suggestion, its throwing and exception as below. 

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

wls:/offline>  connect('myuser','admin','t3://localhost:7001')
Connecting to t3://localhost:7001 with userid myuser ...
Traceback (innermost last):
  File "<console>", line 1, in ?
  File "<iostream>", line 19, in connect
  File "<iostream>", line 553, in raiseWLSTException
WLSTException: Error occurred while performing connect : Error getting the initial context. There is no server running at t3://localhost:7001 : Failed to initialize JNDI context, tried 2 time or times totally, the interval of each time is 0ms.
t3://localhost:7001: Destination 127.0.0.1, 7001 unreachable.; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused); No available router to destination.; nested exception is:
	java.rmi.ConnectException: No available router to destination.
Use dumpStack() to view the full stacktrace :

**Comment by markxnelson** [comment]
could you try changing `localhost` to the admin server address, something like `domain1-admin-server`

**Comment by markxnelson** [comment]
for example: 
```
[root@mark ~]# k exec -ti fat-admin-server /bin/bash
[oracle@fat-admin-server ~]$ ./oracle_common/common/bin/wlst.sh

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

wls:/offline> connect('weblogic','mypassword','t3://fat-admin-server:7001')
Connecting to t3://fat-admin-server:7001 with userid weblogic ...
Successfully connected to Admin Server "admin-server" that belongs to domain "fat".

Warning: An insecure protocol was used to connect to the server. 
To ensure on-the-wire security, the SSL port or Admin port should be used instead.

wls:/fat/serverConfig/> 

```

**Comment by markxnelson** [comment]
that should tell us if the domain uid/password is right

**Comment by markxnelson** [comment]
ok, that's progress. did you say you "sealed" your secret? can you tell me more about that? maybe the operator/domain can't decrypt it right...

**Comment by kavicse87** [comment]
Mark, Yes Kubernetes SealedSecret.. I'm just trying it with the general kubernetes secret in this case that should work if there is an issue with decrypting the SealedSecret. Will let you know shortly. Thanks! for your quick response.

**Comment by markxnelson** [comment]
I am not familiar with sealed secrets - is it a third party thing that you added into k8s?  I think our code is assuming it can read the userid and password out of the secret (which is mounted in /var/run/secrets/whatever) in cleartext.  maybe this sealed secrets thing is changing the interface in some way

**Comment by kavicse87** [comment]
Hi Mark,
No luck yet, still authentication failed. I'm wondering because I'm using a domain called walmart in the wdt image. Also in the weblogic cluster creation (domain.txt).  **I used the same domain.I see the admin server connected to domain1.** wasn't supposed to be walmart right ? Also I've labeled the secrets with the domainuid and domainname with the  domain called walmart only.. Looking forward to hear from you.
1) admin server connection output
---------------------------------
wls:/offline> connect('myuser','admin123','t3://walmart-admin-server:7001')
Connecting to t3://walmart-admin-server:7001 with userid myuser ...
Successfully connected to Admin Server "admin-server" that belongs to domain "**domain1**".

Warning: An insecure protocol was used to connect to the server.
To ensure on-the-wire security, the SSL port or Admin port should be used instead.
2) Created the kubernetes secret 

kubectl create secret  generic weblogic-config -n domain1-ns --from-literal=username="myuser" --from-literal=password="admin123"

but I couldn't find it under /var/run/secrets in the pod
                          
                   [oracle@walmart-admin-server kubernetes.io]$ cd ..
[oracle@walmart-admin-server secrets]$ pwd
/var/run/secrets
[oracle@walmart-admin-server secrets]$ ls -al
total 12
drwxr-xr-x 3 root root 4096 Aug 22 22:47 .
drwxr-xr-x 1 root root 4096 Aug 22 22:47 ..
drwxr-xr-x 3 root root 4096 Aug 22 22:47 kubernetes.io
[oracle@walmart-admin-server secrets]$ cd kubernetes.io/
[oracle@walmart-admin-server kubernetes.io]$ ls -al
total 8
drwxr-xr-x 3 root root 4096 Aug 22 22:47 .
drwxr-xr-x 3 root root 4096 Aug 22 22:47 ..
drwxrwxrwt 3 root root  140 Aug 22 22:46 serviceaccount
[oracle@walmart-admin-server kubernetes.io]$ cd serviceaccount/
[oracle@walmart-admin-server serviceaccount]$ ls -al
total 4
drwxrwxrwt 3 root root  140 Aug 22 22:46 .
drwxr-xr-x 3 root root 4096 Aug 22 22:47 ..
drwxr-xr-x 2 root root  100 Aug 22 22:46 ..2019_08_22_22_46_13.477499829
lrwxrwxrwx 1 root root   31 Aug 22 22:46 ..data -> ..2019_08_22_22_46_13.477499829
lrwxrwxrwx 1 root root   13 Aug 22 22:46 ca.crt -> ..data/ca.crt
lrwxrwxrwx 1 root root   16 Aug 22 22:46 namespace -> ..data/namespace
lrwxrwxrwx 1 root root   12 Aug 22 22:46 token -> ..data/token
[oracle@walmart-admin-server serviceaccount]$

3) After the labelled the secret the output as below:
   commands:
          kubectl label secret weblogic-config -n domain1-ns weblogic.domainUID- weblogic.domainName- && kubectl label secret weblogic-config  -n domain1-ns weblogic.domainUID=walmart weblogic.domainName=walmart
            
              kubectl describe secret weblogic-config -n domain1-ns
Name:         weblogic-config
Namespace:    domain1-ns
Labels:       weblogic.domainName=walmart
              weblogic.domainUID=walmart
Annotations:  <none>

Type:  Opaque

Data
====
username:  6 bytes
password:  8 bytes

    4) domain.yaml file and ingress file
[ingressoutput.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/3532519/ingressoutput.txt)
 for your reference..
domain.yaml
[domain.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/3532475/domain.txt)

**Comment by markxnelson** [comment]
ok, sounds like maybe there is something going wrong in the overall process... did you join our public slack? let's start a private chat there so you can share config files and things and we can work out where the problem is  you can ping me with @Mark Nelson there... if you need a slack invite, go to https://weblogic-slack-inviter.herokuapp.com/
