### ISSUE TITLE
WL-Operator not creating the shared domain directory under the Kubernetes node its trying to spawn the pod

### ISSUE THREAD

**Issue by lightistor** [oracle/weblogic-kubernetes-operator#1218]
**Setup:**
I am using the "$WLOP_SAMPLE_SCRIPTS/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml" input file (modified accordingly) and "$WLOP_SAMPLE_SCRIPTS/create-weblogic-domain/domain-home-on-pv/create-domain.sh" to create our weblogic domain.

Docker: 18.03.1-ce
K8S-Cluster: kubeadm, kubelet and kubectl versions are v1.12.9 (We've had major stability issues with k8s cluster in recommended 1.8.4), kubernetes-cni is 0.7.5
CNI Plug-in: Using Weave instead of Flannel as it would cause cascade crashes.
Topology: 1xMaster (Tainted as recommended) and 1xWorker
user home has the $HOME/shared directory with full ownership and 777 rights on folders (Insecure but no possibility to get permission denied for any reason)

**Failure Case:**
The domain creation on PVC is successful and directory for the domain gets created under worker's **$HOME/shared**. The topology creation starts (Initial replica count 2 for managed-server) and first admin then a managed server pod gets created in worker node. However, the other pod is attempted to be created under the master (As it was tainted) and as the initial domain object creation was under the worker there are no issues with the pods being spinned-up under it.
However, the pod that is being created fails with "[2019-08-25T17:58:57.028 UTC][startServer.sh:69] Error: '/home/oracle/shared/domains/domain0/config/config.xml' not found." as the directory is not present under the node.

Per what I am seeing with the generated job.yaml, the targeting for pod claim is on direct storage instead of a Stateful set and I am suspecting that this might be the culprit.

Anyone to provide any suggestions?

**Comment by markxnelson** [comment]
Sounds like you are using a HostPath PV. If that is the case, then that directory must be available on every node where pods can be scheduled.

**Comment by lightistor** [comment]
Hello Mark, it is available on both master and worker. But as the first time the job pod gets created the files are generated but never get replicated back under the master node where another pod would get created.

**Comment by markxnelson** [comment]
Not sure what you mean by replicated, it has to be the same storage, shared, not just two directories with the same name. You need to use something like NFS to mount the same storage on all nodes

**Comment by TheFrogPad** [comment]
Is $HOME really a shared volume or `HostPath` that is seen by both nodes?

Have you double checked that the `PersistentVolume` and `PersistentVolumeClaim` are correct and that there are no POD errors obtaining the claim and/or mounting the volume?

**Comment by lightistor** [comment]
@FrogPad the issue was not with PVC allocation but due to the PV hostpath being a local directory for both master and worker nodes with the provisioning happening on either when the first time the domain got created on an initial node whereas the other node not having access to domain files. Setting up another droplet (setup is on digital ocean which does not have a managed service for shared volumes) as an NFS node and mounting the share from it to both nodes resolved it.

@markxnelson Thank you for the heads-up. The deployment is now complete with the admin and managed server pods running (Will setup the ingress and test out the auto-scale now).

_Regarding the whole topic of replicas (After having gone through https://blogs.oracle.com/weblogicserver/patching-weblogic-server-in-a-kubernetes-environment and https://akomljen.com/kubernetes-persistent-volumes-with-deployment-and-statefulset ) I might have gone too wild with my imagination to make use of Stateful Sets for managing the domain home directory._
