### ISSUE TITLE
Error in Creating Domain: missing DOMAIN_HOME directory '/u01/oracle/user_projects/domains/sample-domain1'

### ISSUE THREAD

**Issue by sibendu** [oracle/weblogic-kubernetes-operator#1222]
Hi,
I am following "Quick Start" in the documentation https://oracle.github.io/weblogic-kubernetes-operator/quickstart/
All the steps till "Prepare for a Domain" works fine.
During "Create a Domain", I am getting error. When I see "sample-domain1-ns", the pod sample-domain1-introspect-domain-job-xxxx  showing status as "Terminated: Error"
In the logs, I find following line at the end:
Error: missing DOMAIN_HOME directory '/u01/oracle/user_projects/domains/sample-domain1'.

To investigate, I have run the build.sh separately to create and tag the image. By adding extra commands in Dockerfile, I see that the above domain directory is created and there in the image. 

Please advise how to make it work. 
I am running the steps from a OEL7 vm on OCI.

Regards.
sibendu

**Comment by sibendu** [comment]
Here is the my-input.yaml. I had built the image separately by running  ./docker-images/OracleWebLogic/samples/domain-home-in-image/build.sh and pushed to my docker hub account.  

# Copyright 2018, 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

# The version of this inputs file.  Do not modify.
version: create-weblogic-sample-domain-inputs-v1

# Port number for admin server
adminPort: 7001

# Name of the Admin Server
adminServerName: admin-server

# Unique ID identifying a domain.
# This ID must not contain an underscope ("_"), and must be lowercase and unique across all domains
# in a Kubernetes cluster.
domainUID: sample-domain1

# Determines which WebLogic Servers the operator will start up
# Legal values are "NEVER", "IF_NEEDED", or "ADMIN_ONLY"
serverStartPolicy: IF_NEEDED

# Cluster name
clusterName: cluster-1

# Number of managed servers to generate for the domain
configuredManagedServerCount: 5

# Number of managed servers to initially start for the domain
initialManagedServerReplicas: 2

# Base string used to generate managed server names
managedServerNameBase: managed-server

# Port number for each managed server
managedServerPort: 8001

# Boolean indicating if production mode is enabled for the domain
productionModeEnabled: true

# WebLogic Server Docker image that the operator uses to start the domain.
#
# The create domain scripts generate a WebLogic Server Docker image with a domain home in it.
# By default, the scripts tag the generated WebLogic server Docker image as either
# `domain-home-in-image` or `domain-home-in-image-wdt` based on the `domainHomeImageBuildPath`
# property, and use it to set the `image` element in the generated domain YAML file.
#
# If this property is set, the create domain scripts will use the value specified, instead of the
# default value, to tag the generated image and set the `image` in the domain YAML file.
#
# A unique value is required for each domain that is created using the scripts.
#
# If you are running the sample scripts from a machine that is remote to the Kubernetes cluster where
# the domain is going to be running, you need to set this property to the image name that is intended
# to be used in a registry local to that Kubernetes cluster. You also need to push the `image` to
# that registry before starting the domain using the `kubectl create -f` or `kubectl apply -f` command.
# See README.md for more help.
image: sibendudas/weblogic:12.2.1.3

# Image pull policy
# Legal values are "IfNotPresent", "Always", or "Never"
imagePullPolicy: IfNotPresent

# Name of the Kubernetes secret to access the Docker Store to pull the WebLogic Server Docker image
# The presence of the secret will be validated when this parameter is enabled.
#imagePullSecretName:

# Name of the Kubernetes secret for the Admin Server's username and password
# The name must be lowercase.
# If not specified, the value is derived from the domainUID as <domainUID>-weblogic-credentials
weblogicCredentialsSecretName: sample-domain1-weblogic-credentials

# Whether to include server .out to the pod's stdout.
# The default is true.
includeServerOutInPodLog: true

# Specifies whether the log home is stored on the persistent volume.
# If set to true, then you must specify the 'logHome', 'persistentVolumeClaimName'
# and 'domainPVMountPath' properties.
# The default is false.
logHomeOnPV: false

# The in-pod location for domain log, server logs, server out, and node manager log files
# If not specified, the value is derived from the domainUID as /shared/logs/<domainUID>
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
logHome: /shared/logs/domain1

# Port for the T3Channel of the NetworkAccessPoint
t3ChannelPort: 30012

# Public address for T3Channel of the NetworkAccessPoint.  This value should be set to the
# kubernetes server address, which you can get by running "kubectl cluster-info".  If this
# value is not set to that address, WLST will not be able to connect from outside the
# kubernetes cluster.
#t3PublicAddress: 

# Boolean to indicate if the channel should be exposed as a service
exposeAdminT3Channel: false

# NodePort to expose for the admin server
adminNodePort: 30701

# Boolean to indicate if the adminNodePort will be exposed
exposeAdminNodePort: false

# Name of the domain namespace
namespace: sample-domain1-ns

# Java Option for WebLogic Server
javaOptions: -Dweblogic.StdoutDebugEnabled=false

# Name of the persistent volume claim
# If not specified, the value is derived from the domainUID as <domainUID>-weblogic-sample-pvc
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
persistentVolumeClaimName: domain1-weblogic-sample-pvc

# Mount path of the domain persistent volume.
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
domainPVMountPath: /shared

# Base WebLogic binary image used to build the WebLogic domain image
# The operator requires WebLogic Server 12.2.1.3.0 with patch 29135930 applied.
# The WebLogic Docker image, `weblogic:12.2.1.3`, has all the necessary patches applied.
# Refer to [WebLogic Docker images](../../../../../site/weblogic-docker-images.md) for details on how
# to obtain or create the image.
# See README.md for more help.
domainHomeImageBase: container-registry.oracle.com/middleware/weblogic:12.2.1.3

# Location of the WebLogic "domain home in image" Docker image sample in the
# `https://github.com/oracle/docker-images.git` project.
# If not specified, use "./docker-images/OracleWebLogic/samples/12213-domain-home-in-image".
# Another possible value is "./docker-images/OracleWebLogic/samples/12213-domain-home-in-image-wdt",
# which uses WDT, instead of WLST, to generate the domain configuration.
domainHomeImageBuildPath: ./docker-images/OracleWebLogic/samples/12213-domain-home-in-image

**Comment by sibendu** [comment]
Here is the my-input.yaml. I had built the image separately by running ./docker-images/OracleWebLogic/samples/domain-home-in-image/build.sh and pushed to my docker hub account.

**Comment by sibendu** [comment]
Here is the my-input.yaml  (extension changed to .txt). 
I had built the image separately by running ./docker-images/OracleWebLogic/samples/domain-home-in-image/build.sh and pushed to my docker hub account. During docker build, it seems the domain_home folder is present in the image. 

[my-inputs.yaml.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/3549190/my-inputs.yaml.txt)

**Comment by sibendu** [comment]
Thank you. The image and other details in domain.yaml is correct. As I restart the domian with kubectl apply -f domaijn.yaml; the pods are up and running. 
However I am unable to access the WLS console.  I tried by port-forward the admin server pod for 7001/ 30701 , but none of this seems working.

**Comment by alai8** [comment]
Are you not able to bring up the WLS console login page at all? Please check that you have created your domain with `exposedAdminNodePort: true` in your my-inputs.yaml. After the domain has started, verify that a node port type service has been created for the admin server, such as:

sample-domain1-admin-server-external   NodePort    10.111.222.223   <none>        7001:30701/TCP       29s

Could you provide more details on the environment and network setup that you kubernetes cluster is running on so we could provide better help? Thanks!

**Comment by sibendu** [comment]
I am using OKE. With exposedAdminNodePort: true, it exposed the NodePort; and I am able to configure Load balancer to access the console. Thank you. I am closing this.

**Comment by sibendu** [comment]
I am using OKE. With exposedAdminNodePort: true, it exposed the NodePort; and I am able to configure Load balancer to access the console. Thank you. I am closing this.
