### ISSUE TITLE
Introspector pod not picking up the container context from the domain resource

### ISSUE THREAD

**Issue by TheFrogPad** [oracle/weblogic-kubernetes-operator#1228]
https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-resource/#pod-generation

"The job pod for the introspector is generated using the serverPod entries for the administration server", however, the `containerSecurityContext` from the `serverPod` is not being applied to the introspector pod where it is applied to the admin and managed servers.

**Comment by tbarnes-us** [comment]
Related pull:  #1247
