### ISSUE TITLE
create-fmw-infrastructure-domain/domain-home-on-pv/create-domain.sh failure cases.

### ISSUE THREAD

**Issue by lightistor** [oracle/weblogic-kubernetes-operator#1257]
Hello,
Thanks for the help in [Issue-1218](https://github.com/oracle/weblogic-kubernetes-operator/issues/1218 ) @markxnelson it did help me in having a stable environment to play with the operator. Though as standard wls was not I set my eyes on fmw and beyond with which I have encountered further issues and would like your opinion on it.

I have encountered the two following scenarios when trying to setup a domain cluster for fmw-infra (and soasuite image based soa and osb domains):
- The job gets stuck at "Writing base domain" and after a while another job pod gets spawned without even the script being executed again which in turn fails the job. Afterwards, if the "delete-domain/delete-weblogic-domain-resources.sh" is not invoked immediately, a new job pod is launched every 5 minutes .
- The job is completed successfully with the admin-server pod as well as the domain pod are running but initial managed-server pods as per the initial replica count and the domain service resources are never created.

Did anyone stumble upon a similar issue?

As a premise, following is the information on our setup (We haven't had an issue with this setup as we were playing with the wls setup which is configured **create-weblogic-domain**/domain-home-on-pv/create-domain.sh**):

**Docker:** 18.06.2-ce
**K8S-Cluster:** kubeadm, kubelet and kubectl versions are v1.14.6 , kubernetes-cni is 0.7.5
**CNI** Plug-in: Using Weave instead of Flannel as it would cause cascade crashes.
**Topology:** 1xMaster (Tainted as recommended) and 1xWorker
user home has the $HOME/shared directory with full ownership and 777 rights on folders (Insecure but no possibility to get permission denied for any reason)

 - **fmw-infrastructure** container image is **container-registry.oracle.com/middleware/fmw-infrastructure:12.2.1.3**
 - **shared** directory for PVs are through a CentOS-based nfs accessed via the private subnet used by the k8s cluster

**Comment by TheFrogPad** [comment]
Hi @lightistor, can you help gather more information as it is not clear what your issues might be?

1) For your first item about the job getting stuck writing the domain, can you obtain the logs from the job/pod that is creating the domain? An example of using `kubectl` would be:

`kubectl logs job/domain1-create-fmw-infra-sample-domain-job -n domain1-ns`
or
`kubectl logs domain1-create-fmw-infra-sample-domain-job-vtxwq -n domain1-ns`

It's possible that some timeout event might be occurring given the various actions taken to setup and persist the FMW based domain with your PV setup?

2) For your second item about the manged servers and domain service not being created, can you obtain the operator pod logs and also `kubectl describe` the domain resource? For example:

`kubectl describe domain domain1 -n domain1-ns`

Also, what do you mean by the `domain pod running`? Can you please `kubectl describe` this `domain pod` and also `kubectl describe` the running admin server pod?

Thanks

**Comment by TheFrogPad** [comment]
One other item to check is your `PersistentVolume` definition and check the documentation around NFS that we have at https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/persistent-storage/#storage-locations

**Comment by lightistor** [comment]
Apologies for not replying back. This issue seems to span from overall cluster connectivity (Running the setup on digital ocean droplets to mirror an on-premise scenario. I might be wrong regarding this observation)
Out of 50 trials in doing deployment for FMW-I, SOA and OSB (Total of 150 or even more), I had a success rate of 40% with either of the aforementioned scenarios occuring in the rest of the 60% (The culprit for this is repo-db connectivity for 30% even after updating listener timeouts).

I will try to compile down the details to open-up more relevant issues. 

Thanks for the attention.
