### ISSUE TITLE
how to deploy app source on git repo (gitlab or githut,,) when WLS start

### ISSUE THREAD

**Issue by labster97** [oracle/weblogic-kubernetes-operator#1260]
WLS domain was created on PV and /shared is PV and source code is located on /shared. 
customer deployed an application using WLS console. 

My customer wants to store source code on git repository and want to deploy the application to WLS Server when the WLS start. 
in my idea, I need to modify domain.yaml and then kubectl apply -f domain.yaml.

But I don't know how to input the parameter and value to domain.yaml.

please share for customer requirement if you have any idea or documentation.

**Comment by anpanigr** [comment]
In current form domain.yaml does not support any application deployment.

You may consider domain-in-image model as an alternative, where the application archive is available inside the domain image.

**Comment by labster97** [comment]
Hi Antaryami
 
Thanks for your guidance. 
 
I have some question for the domain-in-image model. please advice for my question. 
 
1. Is it supported Github (or Gitlab) for application deployment when image build? 
2. If not support #1, the application archive should be located on PV (persistent volume) or docker image or others? 
3. If the customer uses the domain-in-image model, can they use PV for log repository? 
 
Thanks, 
 
-----Original Message-----
