### ISSUE TITLE
Customer request: Support authentication on elasticsearch host operator sends logs to

### ISSUE THREAD

**Issue by markxnelson** [oracle/weblogic-kubernetes-operator#1293]
Requested by @Vikram in our public slack today 10/8/2019

Customer would like us to enhance the operator to allow them to provide credentials for the elasticsearch server that the operator sends its logs to.

Shadow of OWLS-77204

**Comment by tbarnes-us** [comment]
OWLS-77204 is still open.   Assigning to Ryan for triage.

**Comment by robertpatrick** [comment]
@markxnelson Elasticsearch supports multiple authentication mechanisms (e.g., Basic Auth, OIDC, PKI) so in order to consider this ER, we need to understand the authentication mechanism(s) required by the customer.
