### ISSUE TITLE
Upgrade apiVersions for Kubernetes 1.16

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#1303]
From a customer:

Note that Kubernetes 1.16 deprecates apiVersions for v1beta1 for deployments and other resources, etc. So the current Helm chart for the Operator fails. Not sure yet the extent of what needs to be changed yet.

There are likely runtime changes needed as well.

**Comment by mnemonic01** [comment]
All to apps/v1
See https://github.com/helm/charts/pull/17343

**Comment by rjeberhard** [comment]
Yes, the changes needed are straight-forward for working with Kubernetes 1.16.  However, it's more complex in that I would like to support an upgrade across 1.14 through 1.16.  @mnemonic01, do you have a particular feature or requirement that requires Kubernetes 1.16 or are you just trying to work with latest out of good practice?

**Comment by mnemonic01** [comment]
Not specific, like to keep up with the most recent ones
