### ISSUE TITLE
Checksum fails in a Docker image

### ISSUE THREAD

**Issue by fpacilio** [oracle/weblogic-kubernetes-operator#1330]
Hi all,
I created a WebLogic domain home in a Docker image using one of the domain home in image samples.
Since I run the sample from a machine that is remote to the Kubernetes cluster, I need to push the new image to a registry that is local to the cluster. The image is built successfully but when I push the image in a docker registry, I get this error:
file integrity checksum failed for "u01/oracle/oracle_common/modules/thirdparty/org.apache.ant/1.9.8.0.0/apache-ant-1.9.8/manual/api/org/apache/tools/ant/util/ScriptRunner.html"
![image](https://user-images.githubusercontent.com/12696646/68940554-c1c1f900-07a3-11ea-8ea7-2b87d343f123.png)
The image is created with the script:
./create-domain.sh -i create-domain-inputs.yaml -o <output_dir> -u <user>-p <pwd>
Please, could you help me?
Regards,
Francesco

**Comment by mriccell** [comment]
@fpacilio could you tell me which of the samples you are running?

**Comment by TheFrogPad** [comment]
@fpacilio You may want to try the sample and/or docker build steps again from another machine/node or simply clean up the local docker registry and try again ensuring that `--no-cache` is used by the underlying scripts.

It's likely something might be up with your local registry or file system and there is a closed issue on this topic from Docker at https://github.com/moby/moby/issues/33991

**Comment by fpacilio** [comment]
@mriccell I'm running https://github.com/oracle/weblogic-kubernetes-operator/tree/master/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image.

@TheFrogPad the build already use --no-cache: 
docker build --force-rm=true --no-cache=true $BUILD_ARG -t  ${tagName}  ${scriptDir}
I am going to check the memory used.

**Comment by fpacilio** [comment]
Using 'docker system prune -a', I solved the problem.
thanks.
