### ISSUE TITLE
Adding to system class path

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#136]
Customers want to be able to add jars to the system class path of started servers.

**Comment by rjeberhard** [comment]
This functionality probably depends on #135.

**Comment by tbarnes-us** [comment]
#135 has been addressed to allow for arbitrary pv/c mounts (which can in turn hold jars), and users are free to pass in PRE/POST/CLASSPATH env vars to modify the system classpath to reference any such jars.
