### ISSUE TITLE
Erro in create-domain.sh script - domain-home-in-image

### ISSUE THREAD

**Issue by luizooliveira** [oracle/weblogic-kubernetes-operator#1360]
I'm getting this error when I try to create my domain:

```
Step 19/22 : RUN /u01/oracle/createWLSDomain.sh &&     echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     chmod -R a+x $DOMAIN_HOME/bin/*.sh  &&     rm ${PROPERTIES_FILE_DIR}/*.properties
 ---> Running in 80ca2200cc60
Domain Home is:  /u01/oracle/user_projects/domains/domain-01

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/create-wls-domain.py", line 26, in ?
NameError: SSL_ENABLED

Removing intermediate container 80ca2200cc60
The command '/bin/sh -c /u01/oracle/createWLSDomain.sh &&     echo ". $DOMAIN_HOME/bin/setDomainEnv.sh" >> /u01/oracle/.bashrc &&     chmod -R a+x $DOMAIN_HOME/bin/*.sh  &&     rm ${PROPERTIES_FILE_DIR}/*.properties' returned a non-zero code: 1
[ERROR] Create domain domain-01 failed.
```

Does anyone got the same?

**Comment by markxnelson** [comment]
Thanks for reporting this - we will check it out and get back to you - can you confirm which type of domain you are using? WebLogic/FMW Infrastructure; on PV, in image; what version.  Thanks

**Comment by luizooliveira** [comment]
> Thanks for reporting this - we will check it out and get back to you - can you confirm which type of domain you are using? WebLogic/FMW Infrastructure; on PV, in image; what version. Thanks

Thank you for your prompt reply.

It is a WebLogic domain in Image version 12.2.1.3

**Comment by anpanigr** [comment]
The root cause of the issue is due to a recent merge into docker-images repository. A pull request has been opened to resolve the issue.

**Comment by luizooliveira** [comment]
> The root cause of the issue is due to a recent merge into docker-images repository. A pull request has been opened to resolve the issue.

Thank you. Could you reference it here?

**Comment by anpanigr** [comment]
The change has been reverted in docker-images project. Can u try to re-build your domain image now.

**Comment by luizooliveira** [comment]
Now it's working!

Thank you!
