### ISSUE TITLE
Permission denied when creating folders still exists

### ISSUE THREAD

**Issue by mnemonic01** [oracle/weblogic-kubernetes-operator#1380]
Hi
Building a WebLogic Cluster on OKE still results in a permission denied when the create job tries to make the specific directories for the domain.
I used the HOST_PATH value in the input yaml

But where to I set the security context?
spec:
  serverPod:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

In the create-domain-job-inputs.yaml? There is no yaml formatting in there....

**Comment by mnemonic01** [comment]
domain home should is configured on a PV

**Comment by pfmackin** [comment]
Hi, what image are you using?  Also, can you verify the owner of /u01 and the child directories?  The owner should be oracle.

**Comment by mnemonic01** [comment]
The official one from the oracle container registry,.fmw infrastructure 12.2.1.3. owner and group are oracle, uid guid 1000

**Comment by pfmackin** [comment]
Hi, can you please try container-registry.oracle.com//fmw-infrastructure:12.2.1.3  with the default settings and not override the security context just to make sure that is working?

**Comment by mnemonic01** [comment]
I did... That's why it's not working. Either on OKEor AKS, it gets stuck on this

**Comment by pfmackin** [comment]
Are you using operator 2.4.0 ?

**Comment by mnemonic01** [comment]
Yes, the latest,but it also happened in previous versions

**Comment by pfmackin** [comment]
Hi, I just tested OKE domain on PV using HOST_PATH and had no problem.   I followed the instructions in this blog for setting up NFS: https://blogs.oracle.com/weblogicserver/how-to-run-weblogic-clusters-on-the-oracle-cloud-infrastructure-container-engine-for-kubernetes

Can you verify that your shared directory is owned by opc and accessible from all of you K8s nodes?

**Comment by mnemonic01** [comment]
worked for me, thanks
