### ISSUE TITLE
How to create a custom readiness/liveness probe

### ISSUE THREAD

**Issue by volkermauel** [oracle/weblogic-kubernetes-operator#1395]
I tried editing the cluster serverPod in the Domain to reflect a custom live/ready check, but it was not taken into account when creating the managed server pods.

also i'd like to have a longer grace-period before a container is finally killed since i'm using an in-memory database (hazelcast), but that was also not taken over in the final pods.

Thanks for your help!

**Comment by rjeberhard** [comment]
We don't presently have support for custom liveness or readiness checks.  Can you tell me about your use case?

We do have support for configuring graceful shutdown: https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-lifecycle/startup/#shutdown-options.

**Comment by volkermauel** [comment]
Thanks for the quick reply, i'm trying the graceful shutdown right now.

My usecase for custom liveness/readiness checks is that, for some reason, the deployment of my application seems to fail from time to time. Still the weblogic will be available, thus HAproxy is trying to hand off sessions to the not-running application.

With a custom readiness/liveness-check, i could simply try to HTTP-GET the entry-point of my application and remove any non-functioning pods so they can be restarted.

**Comment by rjeberhard** [comment]
You could integrate your application with the server's ready framework: https://docs.oracle.com/middleware/12213/wls/DEPGD/managing.htm#DEPGD-GUID-C98443B1-D368-4CA4-A7A4-97B86FFD3C28

**Comment by volkermauel** [comment]
Didn't know about that, giving that a try now, thanks for your help!
