### ISSUE TITLE
weblogic admin server&managed server can NOT start on OKE after computer instances reboot 

### ISSUE THREAD

**Issue by atjapan2015** [oracle/weblogic-kubernetes-operator#1433]
Hi Experts,

We're using weblogic kubernetes operator v2.4.0 on oke to verify domain-on-pv for Japan users.
We had deployed sample-domain1 on OKE successfully, we stopped the compute instances(for saving money) at night, we started the compute instances next morning, but  weblogic admin server&managed server can NOT start.

We find error message using describe command, are trying to figure out whether it's the problem of OKE or it's the problem of weblogic kubernetes operator. It's appreciated if you can give us some advice.
------
(combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "84e77ec6d0e7f0a80e997d8fd665779132ef424d71f8fdf6e50f3931ddb0065c" network for pod "sample-domain1-admin-server": NetworkPlugin cni failed to set up pod "sample-domain1-admin-server_sample-domain1-ns" network: open /run/flannel/subnet.env: no such file or directory
------

The environment information are as below.
- Region: Japan Tokyo
- OKE version: 1.14.8
- OKE nodes number: 2
- OKE network: private
- OKE nodes compute shape: VM.Standard.E2.1
- PV: oci fss in the same vcn
- weblogic kubernetes operator: v.2.4.0 (git clone https://github.com/oracle/weblogic-kubernetes-operator -b v2.4.0)

What's more, you can find details logs from attached files! Feel free to let me know if you need more information.

Best Regards & Thanks!

**Comment by atjapan2015** [comment]
[kubectl_get_nodes_pods_logs.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/4211640/kubectl_get_nodes_pods_logs.txt)
[kubectl_describe_logs_logs.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/4211641/kubectl_describe_logs_logs.txt)

**Comment by markxnelson** [comment]
That error is a kubernetes problem, your overlay network is not working. It is not weblogic but the underlying infrastructure

**Comment by markxnelson** [comment]
Notice how all your pods, even the system ones, keep restarting

**Comment by atjapan2015** [comment]
@markxnelson 
Thanks for you quick response.
We're using OKE, not customized Kubernetes cluster,  so we did nothing to the original cluster.
We found below messages from slack, it seems in private network, it's using proxymux, so it takes a little time for flannel to create /run/flannel/subnet.env.
-----
So it looks like, post-reboot, /run/flannel/subnet.env isn't showing up as rapidly as we've seen it do so before.
-----
-----
Initial flannel container came up after 50s - howevr it was racing proxymux (which was still starting) and crapped out
A replacement was up and wrote out /run/flannel/subnet.env after 100s.
-----

We're not sure whether it's the responsibility of OKE team to solve this for running weblogic kubernetes operator on itself, of it's the responsibility of weblogic kubernetes operator team to solve this for itself to run on OKE. 
At least, we don't think it's the responsibility for user to solve this.

We'll ask help from OKE team, and it would be appreciated if weblogic kubernetes operator team could also give us more advice.
Best Regards!

**Comment by atjapan2015** [comment]
We tried deploying an nginx image as a statefulsets, it cloud become running after compute instances restart. It's appreciated if weblogic kubernetes operator cloud do the same thing even there is any problem (?)with OKE.

[nginx_service.yaml.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/4217019/nginx_service.yaml.txt)
[20200218_get_pods_after_restarts.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/4217021/20200218_get_pods_after_restarts.txt)
[20200218_get_pods_before_restarts.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/4217022/20200218_get_pods_before_restarts.txt)

**Comment by atjapan2015** [comment]
We've confirmed with OKE team, allow me to share the answer here,
1, We should not stop the compute nodes from OCI console as this could leave them in an unknown state as far as Kubernetes is concerned.
2, If this is something you want to do then you should do this by draining the nodes using kubectl and then scale the node pool to zero. This will ensure that Kubernetes is aware of the state of the nodes in the node pool. if you scale the nodepool to zero, OKE will terminate the compute instances for you.

If we follow case 2, are there any specific Weblogic operator requirements that should be taken into consideration? Will this cause any issues?

Best Regard!

**Comment by markxnelson** [comment]
NO, if you do that you should not have any WebLogic problems

**Comment by atjapan2015** [comment]
Told by one expert and share the method and test result here.
I changed spec.serverStartPolicy to "NEVER" before shutdown OKE work node, then started OKE work node, after that changed spec.serverStartPolicy to "IF_NEEDED".
admin-server and managed-server became "RUNNING" properly.
Best Regard!
