### ISSUE TITLE
Helm error for kubernetes/charts/weblogic-operator

### ISSUE THREAD

**Issue by israelgoracle** [oracle/weblogic-kubernetes-operator#1451]
Hi,
Since yesterday I have been experiencing problems trying to install, update or inspect the "kubernetes/charts/weblogic-operator":

$helm inspect values kubernetes/charts/weblogic-operator
Error: failed to download "kubernetes/charts/weblogic-operator" (hint: running `helm repo update` may help)

$helm --debug inspect values kubernetes/charts/weblogic-operator
Error: repo kubernetes not found

$helm repo list
NAME             	URL
stable           	https://kubernetes-charts.storage.googleapis.com
local            	http://127.0.0.1:8879/charts
bitnami          	https://charts.bitnami.com/bitnami
coherence        	https://oracle.github.io/coherence-operator/charts
weblogic-operator	https://oracle.github.io/weblogic-kubernetes-operator/charts

I've tried it from windows, macos and oci cloud shell

Could you help me?

**Comment by israelgoracle** [comment]
From 2.4 to 2.5 version, to install the operator Helm chart from GitHub chart repository, repo is different: weblogic-operator/weblogic-operator

**Comment by rjeberhard** [comment]
I see that you closed this, but then your message suggests you are still having an issue.  We just tried this with both helm 2.14.3 and helm 3.0.3 and all was working.
