### ISSUE TITLE
sysctl: error setting key 'vm.max_map_count': Read-only file system

### ISSUE THREAD

**Issue by sp1d3rino** [oracle/weblogic-kubernetes-operator#1539]
When I try to start elasticsearch-kibana only kibana pod is running and elasticsearch goes in Init Crash Loop Back-off.

I read the pod logs 
`kubectl logs elasticsearch-7fc6f9b9bb-8ffgg --all-containers=true`
and this is the content
`sysctl: error setting key 'vm.max_map_count': Read-only file system
Error from server (BadRequest): container "elasticsearch" in pod "elasticsearch-7fc6f9b9bb-8ffgg" is waiting to start: PodInitializing
`
Any idea?
thx

**Comment by marinakog** [comment]
looks like elastic search related, did you try to resolve following this solution: https://github.com/spujadas/elk-docker/issues/99

**Comment by hzhao-github** [comment]
Hi sp1d3rino,

Can you please try to add the block below to your elk yaml file?

       spec:
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      containers:
      - name: "elasticsearch"
      .....

**Comment by rjeberhard** [comment]
@hzhao-github, I believe that @sp1d3rino needs to make these changes on the host machines.  This initContainer will make the change in that container and then exit without persisting the changes to host machine configuration.

**Comment by hzhao-github** [comment]
@rjeberhard sure, based on @sp1d3rino, either way should work

**Comment by sp1d3rino** [comment]
@hzhao-github  the code block is already present in the elk yaml.

**Comment by hzhao-github** [comment]
@sp1d3rino and it still not working?

**Comment by hzhao-github** [comment]
Have you tried the solution  Marina found, https://github.com/spujadas/elk-docker/issues/99?

**Comment by sp1d3rino** [comment]
@hzhao-github yes I just tried also to set vm.max_map_count=262144 on the hosting OS but it doen't work yet

**Comment by hzhao-github** [comment]
@sp1d3rino I didn't do it on machine, but from the config in the container, "command: ['sysctl', '-w', 'vm.max_map_count=262144']", try giving a write permission when setting it

**Comment by sp1d3rino** [comment]
@hzhao-github how to give write permission? 
I needed to change this

```
securityContext:
          privileged: true

```
setting to false because I get this 
`Error creating: pods "elasticsearch-6f4d6b7b4c-" is forbidden: unable to validate against any security context constraint: [spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]`

**Comment by hzhao-github** [comment]
@sp1d3rino do you need to make changes on the host machines or in the container?

**Comment by sp1d3rino** [comment]
@hzhao-github In the container. but as I notice at the beginning of this thread this seems not possible due to read only file system error...

**Comment by sp1d3rino** [comment]
I solved.
1) from the host I ran 
`sudo sysctl -w vm.max_map_count=262144`

2) from the elk yaml I removed this line
 `decommand: ['sysctl', '-w', 'vm.max_map_count=262144']`
  and I put privileged: false

deleted the elasticsearch deployment and applied one more time.

**Comment by y-tee** [comment]
I am on macOS and i cant do `sudo sysctl -w vm.max_map_count=262144`,
even the solution on docker on mac [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode) is not working for me (says tty file not found)
I am running on docker engine v19.03.13 and Catalina 10.15.7 if anyone could help

**Comment by Vinaum8** [comment]
> I solved.
> 
> 1. from the host I ran
>    `sudo sysctl -w vm.max_map_count=262144`
> 2. from the elk yaml I removed this line
>    `decommand: ['sysctl', '-w', 'vm.max_map_count=262144']`
>    and I put privileged: false
> 
> deleted the elasticsearch deployment and applied one more time.

Thanks for help!

**Comment by Uday-Knetworks** [comment]
"max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]" am facing this issue in windows 10 , 
is that elassandra is working in windows 10 perfectly ??????

**Comment by devopsenggineer** [comment]
facing same issue in GKE auto-pilot mode

```
max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
[2021-03-04T14:27:36,294][INFO ][o.e.n.Node               ] [VNeWui4] stopping ...
[2021-03-04T14:27:36,317][INFO ][o.e.n.Node               ] [VNeWui4] stopped
[2021-03-04T14:27:36,317][INFO ][o.e.n.Node               ] [VNeWui4] closing ...
[2021-03-04T14:27:36,382][INFO ][o.e.n.Node               ] [VNeWui4] closed


```
