### ISSUE TITLE
ServerPod label is not updated after patching the domain resource

### ISSUE THREAD

**Issue by anpanigr** [oracle/weblogic-kubernetes-operator#1618]
Start an Operator (namespace weblogic-operator)  with Domain (namespace weblogic-domain)
Patch the domain CRD with the following kubectl command

$ kubectl patch domain domain1 -n weblogic-domain --type merge --patch --patch $(cat label.server.json)
domain.weblogic.oracle/domain1 patched
$ cat label.server.json
`{"spec":
  {"serverPod":
   { "labels":
     {
      "custom": "LABEL_SERVER"
    }
  }
 }
}`
$ kubectl  get po/domain1-adminserver -n weblogic-domain -o yaml | grep LABEL_SERVER 
$   ( returns no matching string )

**Comment by jshum2479** [comment]
This is fixed in the latest develop branch

**Comment by anpanigr** [comment]
I verified the resolution in the develop branch.  
First, patch the domain and then restart the domain.  Then I can see the label on each server pod
