### ISSUE TITLE
Proposal to introduce an environment variable KUBECTL to support variants of kubectl clients.

### ISSUE THREAD

**Issue by GerthH** [oracle/weblogic-kubernetes-operator#1644]
I propose that an environment variable KUBECTL is introduce to support use of K8s variants like Canonical’s microk8s or Red hats Openshift in WKO and possibly others.

This would allow users to state the kubectl command that is used in their installation of a K8s variant in a manner similar to how *nix commands sudo and crontab allows users to use their favourite editor by setting the environment variable EDITOR. 

For microk8s this would be the setting: KUBECTL=microk8s.kubectl 
for Openshift this: KUBECTL=oc to use the oc cmd line that is a superset of kubectl.

The changes required in the shell scripts in WKO that use kubectl are:

- Test if the KUBECTL variable is set and if it is not set it to todays default “kubectl”  eg like this:

if [ -z $KUBECTL ] ; then
   KUBECTL=kubectl
fi
echo Using as kubectl: $KUBECTL

- Replace all current uses for kubectl to be based on using the value for KUBECTL ie $KUBECTL

- Regressiontest

Environment variable are set from the command line 
export KUBECTL=microk8s.kubectl 
before execution of WKO scripts.

I know that there is no statement that WKO supports anything other than vanilla K8s but this would give adopters a headstart to try it out in their own “lab” environments if they so choose.

**Comment by tbarnes-us** [comment]
Sorry for the late response.

This is a good idea. 

A good many WKO sample shell scripts now allow specifying a different CLI than 'kubectl' using the `KUBERNETES_CLI` env var (perhaps you or this Issue spurred this work!), but there are still more than a few that don't. To find these scripts:

```
grep -c KUBERNETES_CLI `find ./kubernetes/samples -name "*.sh" | xargs grep -l kubectl` | grep ":0$" 
```

OPEN ISSUE:  How about other helper scripts?  For example, those within 'integration-tests"?

I've filed internal Oracle JIRA OWLS-88366 to track the issue.

**Comment by tbarnes-us** [comment]
Assigning to Ryan for triage.

**Comment by tbarnes-us** [comment]
I just noticed that @GerthH also mentioned regression tests, and I agree that those should be included too.  I'll add them to the JIRA.

**Comment by tbarnes-us** [comment]
Also modify "create-domain.sh" etc calls to imagetool.sh commands and add option -b podman

**Comment by tbarnes-us** [comment]
RELATED PUBLIC SLACK THREAD. (Sept 2022): https://oracle-weblogic.slack.com/archives/CE3M9DGSY/p1663968575269959
