### ISSUE TITLE
Oracle weblogic Kubernetes Operator failed to deploy in Pod and returns with openapi.ApiException: javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by ranajoy-paul** [oracle/weblogic-kubernetes-operator#1654]
Was trying Oracle weblogic Kubernetes Operator for setting up Weblogic admin & managed server to run from Cloud following : https://oracle.github.io/weblogic-kubernetes-operator/quickstart/ in IBM cloud using Docker Desktop win windows 10 with kubernetes

The "traefik"application started and running in Remote IBM cloud using below command:
helm install traefik-operator stable/traefik --namespace traefik --values kubernetes/samples/charts/traefik/values.yaml --set "kubernetes.namespaces={traefik}" --wait

Followed the comands from ---https://oracle.github.io/weblogic-kubernetes-operator/quickstart/install/
But the weblogic-operator after deployment failed on IBM Cloud(CrashBack) and Pods are in error.

helm install sample-weblogic-operator kubernetes/charts/weblogic-operator --namespace sample-weblogic-operator-ns --set image=oracle/weblogic-kubernetes-operator:2.5.0 --set serviceAccount=sample-weblogic-operator-sa --set "domainNamespaces={}" --wait

The Major error is :
{0}","exception":"\nio.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request\n\tat

Is it related to my local laptop's Java version or I am missing any configuration? But I have tried with both JDK 9 & 11 with same result.
Please help. Thanks in Advance.

Start LOG------
`Launching Oracle WebLogic Server Kubernetes Operator...
Importing keystore /operator/internal-identity/temp/weblogic-operator.jks to /operator/internal-identity/temp/weblogic-operator.p12...
Entry for alias weblogic-operator-alias successfully imported.
Import command completed: 1 entries successfully imported, 0 entries failed or cancelled
Warning:
The -srcstorepass option is specified multiple times. All except the last one will be ignored.
MAC verified OK
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 4720 0 2777 100 1943 12955 9064 --:--:-- --:--:-- --:--:-- 13037
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 5811 0 3281 100 2530 13838 10671 --:--:-- --:--:-- --:--:-- 13902
OpenJDK 64-Bit Server VM warning: Option MaxRAMFraction was deprecated in version 10.0 and will likely be removed in a future release.
VM settings:
Max. Heap Size (Estimated): 3.73G
Using VM: OpenJDK 64-Bit Server VM
{"timestamp":"05-15-2020T14:05:23.463+0000","thread":1,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.TuningParametersImpl","method":"update","timeInMillis":1589551523463,"message":"Reloading tuning parameters from Operator's config map","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.779+0000","thread":1,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"main","timeInMillis":1589551523779,"message":"Oracle WebLogic Server Kubernetes Operator, version: 2.5.0, implementation: master.b9d4b93, build time: 2020-02-26T11:17:50-0500","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.847+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"begin","timeInMillis":1589551523847,"message":"Operator namespace is: sample-weblogic-operator-ns","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.873+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"begin","timeInMillis":1589551523873,"message":"Operator target namespaces are: sample-weblogic-operator-ns","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.878+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.Main","method":"begin","timeInMillis":1589551523878,"message":"Operator service account is: sample-weblogic-operator-sa","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:23.885+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.helpers.HealthCheckHelper","method":"performK8sVersionCheck","timeInMillis":1589551523885,"message":"Verifying Kubernetes minimum version","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:24.407+0000","thread":11,"fiber":"","domainUID":"","level":"INFO","class":"oracle.kubernetes.operator.helpers.ClientPool","method":"getApiClient","timeInMillis":1589551524407,"message":"The Kuberenetes Master URL is set to https://172.21.0.1:443","exception":"","code":"","headers":{},"body":""}
{"timestamp":"05-15-2020T14:05:24.646+0000","thread":11,"fiber":"","domainUID":"","level":"WARNING","class":"oracle.kubernetes.operator.helpers.HealthCheckHelper","method":"performK8sVersionCheck","timeInMillis":1589551524646,"message":"Failure reading Kubernetes version. Exception thrown: {0}","exception":"\nio.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: extension (5) should not be presented in certificate_request\n\tat io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:898)\n\tat io.kubernetes.client.openapi.apis.VersionApi.getCodeWithHttpInfo(VersionApi.java:139)\n\tat io.kubernetes.client.openapi.apis.VersionApi.getCode(VersionApi.java:120)\n\tat oracle.kubernetes.operator.helpers.CallBuilder.lambda$readVersionCode$47(CallBuilder.java:4`
--------End LOG

Is it related to my local laptop's Java version or I am missing any configuration? But I have tried with both JDK 9 & 11 with same result.
C:\WINDOWS\system32>java -version
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

Please help. Thanks in Advance.

**Comment by rjeberhard** [comment]
The 2.5.0 version of the operator doesn't support Kubernetes version 1.16+, because of a change in the SSL certificate extensions, as you noticed.

We have published a release candidate for operator version 3.0.0 that does support operator 1.16.  Replace "--set image=oracle/weblogic-kubernetes-operator:2.5.0" with "--set image=oracle/weblogic-kubernetes-operator:3.0.0-rc1".

**Comment by ranajoy-paul** [comment]
Thanks Ryan for quick response, I have updated to version 3.0.0 and completed weblogc operator deployment which is fine now. Then I followed remaining steps at :https://oracle.github.io/weblogic-kubernetes-operator/quickstart/create-domain/             The Domain script completed successfully as given below,
Command executed:
$ ./create-domain.sh -i create-domain-inputs.yaml -o /weblogicdomain -u weblogic -p welcomE123@ -e

Which completed successfully as per attached file with command output:

last few lines (for quick reference):
`[Warning] One or more build-args [CUSTOM_CLUSTER_TYPE] were not consumed
Successfully built 158506bf03c2
Successfully tagged de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

Create domain sample-domain1 successfully.
domain.weblogic.oracle/sample-domain1 created

Domain sample-domain1 was created and will be started by the WebLogic Kubernetes Operator

The following files were generated:
  /weblogicdomain/weblogic-domains/sample-domain1/create-domain-inputs.yaml
  /weblogicdomain/weblogic-domains/sample-domain1/domain.yaml

Completed`
[create-domain-sh-script-output.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/4640029/create-domain-sh-script-output.txt)

But then when I check the pods from IBM Cloud, I could see its Crashing with ImagePullBack error:
Error:
Failed to pull image "de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4": rpc error: code = Unknown desc = failed to pull and unpack image "de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4": failed to resolve reference "de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized 

Initially I was keeping this "image" field commented in ....\weblogic-kubernetes-operator\kubernetes\samples\scripts\create-weblogic-domain\domain-home-in-image\create-domain-inputs.yaml file but that time Pod was waiting for an image and failing, so as per the commented suggestion in create-domain-inputs.yaml I tried to push the image(de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4) in a Registry in IBM Cloud from my local docker image (domain-home-in-image                             :12.2.1.4) and set it as below : image: de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4
`
# If you are running the sample scripts from a machine that is remote to the Kubernetes cluster where
# the domain is going to be running, you need to set this property to the image name that is intended
# to be used in a registry local to that Kubernetes cluster. You also need to push the `image` to
# that registry before starting the domain using the `kubectl create -f` or `kubectl apply -f` command.
# See README.md for more help.
image: de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4`

But seems (as per below error), its not able to find the image 

`Failed to pull image "de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4": rpc error: code = Unknown desc = failed to pull and unpack image "de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4": failed to resolve reference "de.icr.io/rp_namespace/domain-home-in-image:12.2.1.4": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized `

Please let me know what all fields I should set in create-domain-inputs.yaml (if I need to set #imagePullSecretName: as well?) . And also do I need to pus the image not in IBM Cloud registry or it should be uplaoded in Oracle Git Hub? Can weblogic kube operator fetch that while deploying the pod using the given command (/create-domain.sh) ?.
Please help. Thanks for your help as always !!! @rjeberhard

**Comment by ranajoy-paul** [comment]
Thanks all, issue resolved as i needed to use my worked nodes public IP which opened the admin console. Thanks @mriccell & Team :-)
