### ISSUE TITLE
SetDomainEnv.sh

### ISSUE THREAD

**Issue by vicicode** [oracle/weblogic-kubernetes-operator#1681]
Hi,
Thank you for preparing and sharing lab materials such as (https://bit.ly/weblogic_lab_steps).

fistful i try to learn Docker and Kubernetes 

i followed steps and run the admin console but just i want to learn how to configure directory paths which i previously do this on SetDomainEnv.sh and directory of Weblogic

Thank in advance

**Comment by doxiao** [comment]
If you follow the instructions in the link that you mentioned, the WebLogic domain home should be created and included in the Docker image that is generated by the create-domain.sh script, and used by the Operator uses to start up  a server inside a Kubernetes pod. 

You can get into the admin server pod by running the following command.
$ kubectl exec -it sample-domain1-admin-server -n sample-domain1-ns /bin/bash

Then you should be able to see setDomainEnv.sh in /u01/oracle/user_projects/domains/sample-domain1/bin.

**Comment by vicicode** [comment]
ツ Thanks

**Comment by tbarnes-us** [comment]
I'm closing because it looks like the re-open was inadvertent (it was done with no other comment than 'Thanks').  Please feel free to re-open if needed.
