### ISSUE TITLE
scalingAction.sh must be copied to $DOMAIN_HOME/bin/scripts on the admin pod

### ISSUE THREAD

**Issue by xiancao** [oracle/weblogic-kubernetes-operator#1718]
When using a WLDF policy rule and script action to scale a cluster in the domain, we need to copy the scalingAction.sh script to $DOMAIN_HOME/bin/scripts. If copied to other location, it will not work. 

According to the WLDF configuration doc:

Configuring Script Actions
You can use the script action to execute an external command line script, which can be written in any language.
To set the execution environment in which the script is run, you can configure the following attributes of the WLDFScriptActionBean:
    PathToScript — The full path to the script, which must be located in the DOMAIN_HOME/bin/scripts directory

We need to update the operator doc ( https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-lifecycle/scaling/#configure-automatic-scaling-of-weblogic-clusters-in-kubernetes-with-wldf ):

from:
Copy the scalingAction.sh script to a directory (such as $DOMAIN_HOME/bin/scripts) so that it’s accessible within the Administration Server pod.
to:
Copy the scalingAction.sh script to $DOMAIN_HOME/bin/scripts so that it’s accessible within the Administration Server pod.

**Comment by tbarnes-us** [comment]
Filed internal tracking JIRA OWLS-82374 to track.

**Comment by tbarnes-us** [comment]
Resolved on June 11, 2020 using https://github.com/oracle/weblogic-kubernetes-operator/pull/1720 .
