### ISSUE TITLE
Release operator 2.6.0: create domain success, but POD error.

### ISSUE THREAD

**Issue by dai0384448** [oracle/weblogic-kubernetes-operator#1761]
An error occurs when creating the admin server after domain creation.

After "create-domain.sh" is executed, the domain becomes "RUNNING".
However, the status of the created pod will be "Error".

Kubernetes Operator:
https://oracle.github.io/weblogic-kubernetes-operator/quickstart/prerequisites/

OS: CentOS Linux release 8.1.1911 (Core) 
Docker Version: 19.03.8
K8S:Version: 1.18.2
Release operator 2.6.0 

Execution command: ./create-domain.sh -i my-inputs2.yaml -o /test0623 -u weblogic -p weblogic$123 -e

[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# pwd
/k8stest/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image
[root@k8s-1 domain-home-in-image]# ll
total 36
-rw-r--r--  1 root root 6433 Jun 22 15:33 create-domain-inputs.yaml
-rwxr-xr-x  1 root root 7578 Jun 22 15:33 create-domain.sh
drwxr-xr-x 25 root root 4096 Jun 23 19:02 docker-images
-rw-r--r--  1 root root  907 Jun 23 18:08 my-inputs2.yaml
-rw-r--r--  1 root root 6433 Jun 23 17:30 my-inputs.yaml
-rw-r--r--  1 root root  544 Jun 22 15:33 properties-template.properties
[root@k8s-1 domain-home-in-image]# cat my-inputs2.yaml 
version: create-weblogic-sample-domain-inputs-v1
adminPort: 7001
adminServerName: admin-server
domainUID: sample-domain1
serverStartPolicy: IF_NEEDED
clusterName: cluster-1
configuredManagedServerCount: 5
initialManagedServerReplicas: 2
managedServerNameBase: managed-server
managedServerPort: 8001
productionModeEnabled: true
imagePullPolicy: IfNotPresent
weblogicCredentialsSecretName: sample-domain1-weblogic-credentials
includeServerOutInPodLog: true
logHomeOnPV: false
logHome: /shared/logs/domain1
t3ChannelPort: 30012
exposeAdminT3Channel: false
adminNodePort: 30701
exposeAdminNodePort: false
namespace: sample-domain1-ns
javaOptions: -Dweblogic.StdoutDebugEnabled=false
persistentVolumeClaimName: domain1-weblogic-sample-pvc
domainPVMountPath: /shared
domainHomeImageBase: oracle/weblogic:12.2.1.3-generic
domainHomeImageBuildPath: ./docker-images/OracleWebLogic/samples/12213-domain-home-in-image
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# kubectl get pod -n sample-domain1-ns 
NAME                                         READY   STATUS   RESTARTS   AGE
sample-domain1-introspect-domain-job-2vzz7   0/1     Error    0          50s
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# kubectl describe pod -n sample-domain1-ns 
Name:         sample-domain1-introspect-domain-job-2vzz7
Namespace:    sample-domain1-ns
Priority:     0
Node:         k8s-1/192.168.1.210
Start Time:   Wed, 24 Jun 2020 09:04:36 +0800
Labels:       controller-uid=6c3bae44-92bd-4d3e-a89c-c4c26ffa478f
              job-name=sample-domain1-introspect-domain-job
              weblogic.createdByOperator=true
              weblogic.domainUID=sample-domain1
Annotations:  <none>
Status:       Failed
IP:           172.31.0.220
IPs:
  IP:           172.31.0.220
Controlled By:  Job/sample-domain1-introspect-domain-job
Containers:
  sample-domain1-introspect-domain-job:
    Container ID:  docker://b08f57f005351afbb5ee302ca7ad5470ae4b241af0436f2406dcdff44ad04979
    Image:         domain-home-in-image:12.2.1.3-generic
    Image ID:      docker://sha256:b2910fc4525ff78bf667bcb6cb40f5087a70ab4f8d7480b82fd116c620d4d559
    Port:          <none>
    Host Port:     <none>
    Command:
      /weblogic-operator/scripts/introspectDomain.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 24 Jun 2020 09:04:37 +0800
      Finished:     Wed, 24 Jun 2020 09:04:37 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      JAVA_OPTIONS:             -Dweblogic.StdoutDebugEnabled=false
      USER_MEM_ARGS:            -Djava.security.egd=file:/dev/./urandom 
      DOMAIN_UID:               sample-domain1
      DOMAIN_HOME:              /u01/oracle/user_projects/domains/sample-domain1
      NODEMGR_HOME:             /u01/nodemanager
      LOG_HOME:                 
      SERVER_OUT_IN_POD_LOG:    true
      ACCESS_LOG_IN_LOG_HOME:   true
      NAMESPACE:                sample-domain1-ns
      INTROSPECT_HOME:          /u01/oracle/user_projects/domains/sample-domain1
      CREDENTIALS_SECRET_NAME:  sample-domain1-weblogic-credentials
      DOMAIN_SOURCE_TYPE:       Image
      ISTIO_ENABLED:            false
      ISTIO_READINESS_PORT:     8888
      ADMIN_USERNAME:           
      ADMIN_PASSWORD:           
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lvsd9 (ro)
      /weblogic-operator/scripts from weblogic-domain-cm-volume (ro)
      /weblogic-operator/secrets from weblogic-credentials-volume (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  weblogic-credentials-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sample-domain1-weblogic-credentials
    Optional:    false
  weblogic-domain-cm-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      weblogic-domain-cm
    Optional:  false
  default-token-lvsd9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lvsd9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned sample-domain1-ns/sample-domain1-introspect-domain-job-2vzz7 to k8s-1
  Normal  Pulled     58s        kubelet, k8s-1     Container image "domain-home-in-image:12.2.1.3-generic" already present on machine
  Normal  Created    58s        kubelet, k8s-1     Created container sample-domain1-introspect-domain-job
  Normal  Started    58s        kubelet, k8s-1     Started container sample-domain1-introspect-domain-job
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# 
[root@k8s-1 domain-home-in-image]# kubectl logs sample-domain1-introspect-domain-job-2vzz7  -n sample-domain1-ns 
@[2020-06-24T01:04:37.647 UTC][introspectDomain.sh:64][FINE] Introspecting the domain
@[2020-06-24T01:04:37.659 UTC][introspectDomain.sh:252][FINE] Env vars before:
    DOMAIN_UID='sample-domain1'
    NAMESPACE='sample-domain1-ns'
    SERVER_NAME=''
    SERVICE_NAME=''
    ADMIN_NAME='admin-server'
    AS_SERVICE_NAME=''
    ADMIN_PORT='7001'
    ADMIN_PORT_SECURE=''
    USER_MEM_ARGS='-Djava.security.egd=file:/dev/./urandom '
    JAVA_OPTIONS='-Dweblogic.StdoutDebugEnabled=false'
    FAIL_BOOT_ON_SITUATIONAL_CONFIG_ERROR=''
    STARTUP_MODE=''
    DOMAIN_HOME='/u01/oracle/user_projects/domains/sample-domain1'
    LOG_HOME=''
    SERVER_OUT_IN_POD_LOG='true'
    DATA_HOME=''
    KEEP_DEFAULT_DATA_HOME=''
    EXPERIMENTAL_LINK_SERVER_DEFAULT_DATA_DIR=''
    JAVA_HOME='/usr/java/jdk-8'
    ORACLE_HOME='/u01/oracle'
    WL_HOME=''
    MW_HOME=''
    NODEMGR_HOME='/u01/nodemanager'
    INTROSPECT_HOME='/u01/oracle/user_projects/domains/sample-domain1'
    PATH='/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk-8/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin::/bin:/u01/oracle'
    TRACE_TIMING=''
@[2020-06-24T01:04:37.672 UTC][introspectDomain.sh:290][FINE] id = 'uid=1000(oracle) gid=1000(oracle) groups=1000(oracle)'
@[2020-06-24T01:04:37.684 UTC][introspectDomain.sh:294][FINE] Directory trace for DOMAIN_HOME=/u01/oracle/user_projects/domains/sample-domain1 (before)
  ls -ld /u01/oracle/user_projects/domains/sample-domain1/*:
    drwxr-x--- 2 oracle oracle   32 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/autodeploy
    drwxr-x--- 2 oracle oracle   39 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/backup_config
    drwxr-x--- 6 oracle oracle 4096 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/bin
    drwxr-x--- 8 oracle oracle  156 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/config
    drwxr-x--- 2 oracle oracle   32 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/console-ext
    -rw-r----- 1 oracle oracle  327 Jul 19  2017 /u01/oracle/user_projects/domains/sample-domain1/fileRealm.properties
    drwxr-x--- 3 oracle oracle 4096 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/init-info
    drwxr-x--- 2 oracle oracle   32 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/lib
    drwxr-x--- 2 oracle oracle   75 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/nodemanager
    drwxr-x--- 2 oracle oracle   10 Jul 19  2017 /u01/oracle/user_projects/domains/sample-domain1/resources
    drwxr-x--- 2 oracle oracle  163 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/security
    drwxr-x--- 3 oracle oracle   34 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/servers
    -rwxr-x--- 1 oracle oracle  264 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/startWebLogic.sh
  ls -ld /u01/oracle/user_projects/domains/sample-domain1:
    drwxrwxrwx 1 oracle oracle 292 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1
  ls -ld /u01/oracle/user_projects/domains:
    drwxrwxrwx 1 oracle oracle 36 Jun 23 11:02 /u01/oracle/user_projects/domains
  ls -ld /u01/oracle/user_projects:
    drwxr-xr-x 1 root root 29 Jun 23 11:02 /u01/oracle/user_projects
  ls -ld /u01/oracle:
    drwx------ 1 oracle oracle 107 Jun 23 11:02 /u01/oracle
  ls -ld /u01:
    drwxr-xr-x 1 oracle oracle 28 May 14 01:14 /u01
  ls -ld /:
    drwxr-xr-x 1 root root 54 Jun 24 01:04 /
@[2020-06-24T01:04:37.713 UTC][introspectDomain.sh:252][FINE] Env vars after:
    DOMAIN_UID='sample-domain1'
    NAMESPACE='sample-domain1-ns'
    SERVER_NAME=''
    SERVICE_NAME=''
    ADMIN_NAME='admin-server'
    AS_SERVICE_NAME=''
    ADMIN_PORT='7001'
    ADMIN_PORT_SECURE=''
    USER_MEM_ARGS='-Djava.security.egd=file:/dev/./urandom '
    JAVA_OPTIONS='-Dweblogic.StdoutDebugEnabled=false'
    FAIL_BOOT_ON_SITUATIONAL_CONFIG_ERROR=''
    STARTUP_MODE=''
    DOMAIN_HOME='/u01/oracle/user_projects/domains/sample-domain1'
    LOG_HOME=''
    SERVER_OUT_IN_POD_LOG='true'
    DATA_HOME=''
    KEEP_DEFAULT_DATA_HOME=''
    EXPERIMENTAL_LINK_SERVER_DEFAULT_DATA_DIR=''
    JAVA_HOME='/usr/java/jdk-8'
    ORACLE_HOME='/u01/oracle'
    WL_HOME='/u01/oracle/wlserver'
    MW_HOME='/u01/oracle'
    NODEMGR_HOME='/u01/nodemanager'
    INTROSPECT_HOME='/u01/oracle/user_projects/domains/sample-domain1'
    PATH='/usr/java/jdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk-8/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin::/bin:/u01/oracle'
    TRACE_TIMING=''
@[2020-06-24T01:04:37.726 UTC][introspectDomain.sh:290][FINE] id = 'uid=1000(oracle) gid=1000(oracle) groups=1000(oracle)'
@[2020-06-24T01:04:37.736 UTC][introspectDomain.sh:294][FINE] Directory trace for DOMAIN_HOME=/u01/oracle/user_projects/domains/sample-domain1 (after)
  ls -ld /u01/oracle/user_projects/domains/sample-domain1/*:
    drwxr-x--- 2 oracle oracle   32 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/autodeploy
    drwxr-x--- 2 oracle oracle   39 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/backup_config
    drwxr-x--- 6 oracle oracle 4096 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/bin
    drwxr-x--- 8 oracle oracle  156 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/config
    drwxr-x--- 2 oracle oracle   32 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/console-ext
    -rw-r----- 1 oracle oracle  327 Jul 19  2017 /u01/oracle/user_projects/domains/sample-domain1/fileRealm.properties
    drwxr-x--- 3 oracle oracle 4096 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/init-info
    drwxr-x--- 2 oracle oracle   32 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/lib
    drwxr-x--- 2 oracle oracle   75 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/nodemanager
    drwxr-x--- 2 oracle oracle   10 Jul 19  2017 /u01/oracle/user_projects/domains/sample-domain1/resources
    drwxr-x--- 2 oracle oracle  163 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/security
    drwxr-x--- 3 oracle oracle   34 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/servers
    -rwxr-x--- 1 oracle oracle  264 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1/startWebLogic.sh
  ls -ld /u01/oracle/user_projects/domains/sample-domain1:
    drwxrwxrwx 1 oracle oracle 292 Jun 23 11:02 /u01/oracle/user_projects/domains/sample-domain1
  ls -ld /u01/oracle/user_projects/domains:
    drwxrwxrwx 1 oracle oracle 36 Jun 23 11:02 /u01/oracle/user_projects/domains
  ls -ld /u01/oracle/user_projects:
    drwxr-xr-x 1 root root 29 Jun 23 11:02 /u01/oracle/user_projects
  ls -ld /u01/oracle:
    drwx------ 1 oracle oracle 107 Jun 23 11:02 /u01/oracle
  ls -ld /u01:
    drwxr-xr-x 1 oracle oracle 28 May 14 01:14 /u01
  ls -ld /:
    drwxr-xr-x 1 root root 54 Jun 24 01:04 /
@[2020-06-24T01:04:37.772 UTC][introspectDomain.sh:522][SEVERE] The Operator requires that WebLogic version '12.2.1.3' have patch '29135930'. To bypass this check, set env var SKIP_WL_VERSION_CHECK to 'true'.

**Comment by rjeberhard** [comment]
For WebLogic 12.2.1.3, the WebLogic installation in your Docker image must have patch 29135930 applied. The pre-built image on the Oracle Container Registry already has this patch applied, but if you build the WebLogic image yourself then you must include this patch. Please see the documentation here: https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/domain-in-image/base-images/#creating-a-custom-image-with-patches-applied.

**Comment by dai0384448** [comment]
Sorry for the late reply. It's settled. thank you
