### ISSUE TITLE
Deployment's api version in 'oracle.db.yaml' should be changed to 'apps/v1' for K8S version 1.18.x

### ISSUE THREAD

**Issue by sbattagi** [oracle/weblogic-kubernetes-operator#1769]
Hi, 

Creating a Database deployment using the file "weblogic-kubernetes-operator/kubernetes/samples/scripts/create-oracle-db-service/common/oracle.db.yaml" throws below error on K8S version 1.18.x.
ERROR:
error: unable to recognize "/scratch/sbattagi/workdir/weblogic-kubernetes-operator-2.6.0/kubernetes/samples/scripts/create-oracle-db-service/common/oracle.db.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

As per the K8S 1.18 release notes shown below, we have to use "apps/v1" instead of "extensions/v1beta1".
"daemonsets, deployments, replicasets resources under extensions/v1beta1 - use apps/v1 instead" 
https://kubernetes.io/docs/setup/release/notes/#kube-apiserver-1

Please review and fix the issue.

Thanks
Samba

**Comment by sbattagi** [comment]
This issue is seen in operator 2.6.0 release branch.

**Comment by rjeberhard** [comment]
Fixed in 3.0.
