### ISSUE TITLE
Please review the copyright in 'domain-template.yaml'

### ISSUE THREAD

**Issue by sbattagi** [oracle/weblogic-kubernetes-operator#1770]
The copyright in 'weblogic-kubernetes-operator/kubernetes/samples/scripts/common/domain-template.yaml' file has the phrase 'All rights reserved.'.  Please review if this is correct ? I see this phrase is removed from other files earlier.

**Comment by sbattagi** [comment]
This issue is seen in operator 2.6.0 release branch.

**Comment by markxnelson** [comment]
Thank you for reporting the issue.  Fixed now.
