### ISSUE TITLE
Document using the Operator on Azure Kubernetes Service

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-kubernetes-operator#1801]

**Comment by edburns** [comment]
@markxnelson Please assign this to me.

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/87356919-f784d080-c530-11ea-8adf-777759412b6c.png)

**Comment by edburns** [comment]
```
docs-source/runlocal.sh
```

**Comment by rjeberhard** [comment]
Hi, Ed. Welcome!

**Comment by edburns** [comment]
@rjeberhard hello, happy to be here.  I will be smoothly applying the excellent work from my team at Microsoft, including @galiacheng.  The credit is all hers.

**Comment by edburns** [comment]
@rjeberhard @jshum2479 @mriccell Here is another revision of this PR.  Thanks for your help.  https://github.com/oracle/weblogic-kubernetes-operator/pull/1873

**Comment by tbarnes-us** [comment]
Hi Ed - 

I'm assuming this can be considered resolved by now.

Feel free to re-open the issue if I'm incorrect.
