### ISSUE TITLE
 Error creating: pods "domain1-introspect-domain-job-" is forbidden: unable to validate against any pod security policy: []

### ISSUE THREAD

**Issue by PieperCH** [oracle/weblogic-kubernetes-operator#1868]
Hi all,

I've a issue creating a new domain following the sample scripts: https://github.com/oracle/weblogic-kubernetes-operator/tree/master/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image 

Operator is running fine:
$ helm get values weblogic-operator
USER-SUPPLIED VALUES:
dedicated: false
domainNamespaces:
- myname-wls
elasticSearchHost: elasticsearch.default.svc.cluster.local
elasticSearchPort: 9200
elkIntegrationEnabled: false
externalDebugHttpPort: 30999
externalRestEnabled: false
externalRestHttpsPort: 31001
image: weblogic-kubernetes-operator:3.0.0
imagePullPolicy: IfNotPresent
internalDebugHttpPort: 30999
istioEnabled: false
javaLoggingLevel: INFO
logStashImage: logstash:6.6.0
remoteDebugNodePortEnabled: false
serviceAccount: default
suspendOnDebugStartup: false

The pod for introspect-domain could not be created based on pod security policy:
$ kubectl describe job domain1-introspect-domain-job -n myname-wls
Name:                     domain1-introspect-domain-job
Namespace:                myname-wls
Selector:                 controller-uid=7e3d8802-2306-4ecd-a632-3f52ba84ec29
Labels:                   weblogic.createdByOperator=true
                          weblogic.domainUID=domain1
Annotations:              <none>
Controlled By:            Domain/domain1
Parallelism:              1
Completions:              1
Active Deadline Seconds:  120s
Pods Statuses:            0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=7e3d8802-2306-4ecd-a632-3f52ba84ec29
           job-name=domain1-introspect-domain-job
           weblogic.createdByOperator=true
           weblogic.domainUID=domain1
  Containers:
   domain1-introspect-domain-job:
    Image:      oracle/weblogic:12.2.1.4
    Port:       <none>
    Host Port:  <none>
    Command:
      /weblogic-operator/scripts/introspectDomain.sh
    Requests:
      cpu:     250m
      memory:  768Mi
    Environment:
      JAVA_OPTIONS:                    -Dweblogic.StdoutDebugEnabled=false
      USER_MEM_ARGS:                   -Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m
      DOMAIN_UID:                      domain1
      DOMAIN_HOME:                     /u01/oracle/user_projects/domains/domain1
      NODEMGR_HOME:                    /u01/nodemanager
      LOG_HOME:
      SERVER_OUT_IN_POD_LOG:           true
      ACCESS_LOG_IN_LOG_HOME:          true
      NAMESPACE:                       myname-wls
      INTROSPECT_HOME:                 /u01/oracle/user_projects/domains/domain1
      CREDENTIALS_SECRET_NAME:         domain1-weblogic-credentials
      OPSS_KEY_SECRET_NAME:
      OPSS_WALLETFILE_SECRET_NAME:
      RUNTIME_ENCRYPTION_SECRET_NAME:
      WDT_DOMAIN_TYPE:                 WLS
      DOMAIN_SOURCE_TYPE:              Image
      ISTIO_ENABLED:                   false
      ISTIO_READINESS_PORT:            8888
      ISTIO_POD_NAMESPACE:             myname-wls
      OPERATOR_ENVVAR_NAMES:           JAVA_OPTIONS,USER_MEM_ARGS,DOMAIN_UID,DOMAIN_HOME,NODEMGR_HOME,LOG_HOME,SERVER_OUT_IN_POD_LOG,ACCESS_LOG_IN_LOG_HOME,NAMESPACE,INTROSPECT_HOME,CREDENTIALS_SECRET_NAME,OPSS_KEY_SECRET_NAME,OPSS_WALLETFILE_SECRET_NAME,RUNTIME_ENCRYPTION_SECRET_NAME,WDT_DOMAIN_TYPE,DOMAIN_SOURCE_TYPE,ISTIO_ENABLED,ISTIO_READINESS_PORT,ISTIO_POD_NAMESPACE
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
    Mounts:
      /weblogic-operator/introspectormii from mii-weblogic-domain-introspect-cm (rw)
      /weblogic-operator/scripts from weblogic-scripts-cm-volume (ro)
      /weblogic-operator/secrets from weblogic-credentials-volume (ro)
  Volumes:
   weblogic-credentials-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  domain1-weblogic-credentials
    Optional:    false
   weblogic-scripts-cm-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      weblogic-scripts-cm
    Optional:  false
   mii-weblogic-domain-introspect-cm:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      domain1-weblogic-domain-introspect-cm
    Optional:  true
Events:
  Type     Reason        Age                 From            Message
  ----     ------        ----                ----            -------
  Warning  FailedCreate  24s (x16 over 24m)  job-controller  Error creating: pods "domain1-introspect-domain-job-" is forbidden: unable to validate against any pod security policy: []

Regards,
Christian

**Comment by rjeberhard** [comment]
Hi Christian,

It seems like your Kubernetes cluster has pod security policies: https://kubernetes.io/docs/concepts/policy/pod-security-policy/

Either the service account that you've selected for the WebLogic pods (including our "introspector" job) to use does not have permission to use the available pod security policies or the pods the operator is creating don't match the expectations of those policies.

We'll need to know the contents of these pod security policies to recommend a next-action. There are many configurations in the Domain YAML that allow you to customize the pods that the operator will create to assist with meeting the requirements of these policies.

Ryan

**Comment by tbarnes-us** [comment]
The discussion continues in the slack weblogic#operato thread https://oracle-weblogic.slack.com/archives/CE3M9DGSY/p1597406265002300

**Comment by tbarnes-us** [comment]
I'm assuming the issue is resolved by now.  If I'm incorrect, feel free to re-open the issue (or better yet, restart the discussion in slack).
