### ISSUE TITLE
WKO 3.0.1 Users Guide Initial use case Model in image example fails with error: unable to convert uid/gid chown string to host mapping: cant find gid for group oracle: no such group: oracle

### ISSUE THREAD

**Issue by GerthH** [oracle/weblogic-kubernetes-operator#1908]
In the sample code for initial use case model in image we have:
$ cd /tmp/mii-sample/model-images
$ ./imagetool/bin/imagetool.sh update \
  --tag model-in-image:WLS-v1 \
  --fromImage container-registry.oracle.com/middleware/weblogic:12.2.1.4 \
...
This fails at 
Step 6/24 : COPY --chown=oracle:oracle weblogic-deploy.zip /tmp/imagetool/
[SEVERE ] Response code: -1, message: docker command failed with error: unable to convert uid/gid chown string to host mapping: cant find gid for group oracle: no such group: oracle

It seems that container-registry.oracle.com/middleware/weblogic:12.2.1.4 is built with different group name than "oracle".
Work around so far is to either 
- use container-registry.oracle.com/middleware/weblogic:12.2.1.3
- or build a local image wls:12.2.1.4.0 using e.g. weblogic image tool with e.g.
$ ./imagetool.sh cache listItems
jdk_8u241=/u01/stage/jdk/8u241/jdk-8u241-linux-x64.tar.gz
wls_12.2.1.4.0-w=/u01/stage/wls/12.2.1.4.0/fmw_12.2.1.4.0_wls_Disk1_1of1.zip 
$ ./imagetool.sh create --type WLS --tag wls:12.2.1.4.0-w --version 12.2.1.4.0 --jdkVersion=8u241

Please rebuild container-registry.oracle.com/middleware/weblogic:12.2.1.4 with group "oracle".
Please synchronize builds and examples so we have a working combination of weblogic kubernetes operator, weblogic image tool and weblogic deploy tooling.

Regards / Gerth

**Comment by mriccell** [comment]
We did push new images where the owner changed to oracle:root to meet a requirement.  We are in the process of making changes to the MII sample to indicate that you must add --chown oracle:root to the imagetool.sh command.  In the future we will make a change to the WebLogic Image Tool so that the chown command is not necessary.
Thanks
Monica

**Comment by tbarnes-us** [comment]
@mriccell I think this issue is addressed in 3.0.2? If so, can you close it out?
