### ISSUE TITLE
Duplicate Name of the Kubernetes Secret in document

### ISSUE THREAD

**Issue by galiacheng** [oracle/weblogic-kubernetes-operator#1915]
There are two docker secret names in this doc: https://oracle.github.io/weblogic-kubernetes-operator/samples/simple/domains/domain-home-on-pv/
`imagePullSecretName`
`weblogicImagePullSecretName`

I didn't find a reference to `weblogicImagePullSecretName` in scripts.

**Comment by tbarnes-us** [comment]
Thanks Galia!  

There's a pending fix in [pull 1920](https://github.com/oracle/weblogic-kubernetes-operator/pull/1920)

**Comment by tbarnes-us** [comment]
The documentation has been fixed. Thanks for letting us know!
