### ISSUE TITLE
NullPointerException in operator when admin server http listening is disabled

### ISSUE THREAD

**Issue by csegedicsaba** [oracle/weblogic-kubernetes-operator#1987]
Disabling admin server http port cause NullPointerException in operator. The admin server starts but the operator can't check the state.

`domainInfo:
  AdminUserName: '@@SECRET:__weblogic-credentials__:username@@'
  AdminPassword: '@@SECRET:__weblogic-credentials__:password@@'

topology:
  Name: 'test-domain'
  AdminServerName: 'admin-server'
  ProductionModeEnabled: 'false'

  Cluster:
    'test-cluster':

      DynamicServers:
        ServerTemplate: 'test-cluster-template'
        CalculatedListenPorts: false
        ServerNamePrefix: 'managed-server-'
        DynamicClusterSize: '2'
        MaxDynamicClusterSize: '4'

  Server:
    'admin-server':
      ListenPort: 7001
      ListenPortEnabled: false
      SSL:
        Enabled: true
        ListenPort: 7002
   
  ServerTemplate:
    'test-cluster-template':
      ListenPort: 8001
      ListenPortEnabled: false
      SSL:
        Enabled: true
        ListenPort: 8002
      Cluster: 'test-cluster'`

Exception in operator log:
`{"timestamp":"10-13-2020T18:50:30.293+0000","thread":13,"fiber":"fiber-900-child-2-child-1","namespace":"default","domainUID":"test-domain","level":"SEVERE","class":"oracle.kubernetes.operator.DomainProcessorImpl","method":"logThrowable","timeInMillis":1602615030293,"message":"Exception thrown","exception":"\njava.lang.NullPointerException\n\tat oracle.kubernetes.operator.helpers.PodStepContext.createMetadata(PodStepContext.java:536)\n\tat oracle.kubernetes.operator.helpers.PodHelper$ManagedPodStepContext.createMetadata(PodHelper.java:510)\n\tat oracle.kubernetes.operator.helpers.PodStepContext.createPodRecipe(PodStepContext.java:505)\n\tat oracle.kubernetes.operator.helpers.PodStepContext.createPodModel(PodStepContext.java:426)\n\tat oracle.kubernetes.operator.helpers.PodStepContext.init(PodStepContext.java:95)\n\tat oracle.kubernetes.operator.helpers.PodHelper$ManagedPodStepContext.<init>(PodHelper.java:417)\n\tat oracle.kubernetes.operator.helpers.PodHelper$ManagedPodStep.apply(PodHelper.java:545)\n\tat oracle.kubernetes.operator.work.Fiber.doRunInternal(Fiber.java:631)\n\tat oracle.kubernetes.operator.work.Fiber.doRun(Fiber.java:555)\n\tat oracle.kubernetes.operator.work.Fiber.run(Fiber.java:491)\n\tat oracle.kubernetes.operator.work.ThreadLocalContainerResolver.lambda$wrapExecutor$0(ThreadLocalContainerResolver.java:87)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\n\tat java.base/java.lang.Thread.run(Thread.java:832)\n","code":"","headers":{},"body":""}`

weblogic operator: 3.0.2
wewblogic base image: store/oracle/weblogic:12.2.1.4-dev-200117

**Comment by tbarnes-us** [comment]
I think https://github.com/oracle/weblogic-kubernetes-operator/pull/1902 would fix this, but I don't think this is included in 3.0.2.

@qvdang Can you confirm?

**Comment by qvdang** [comment]
I ran into similar NPE recently and I believe #1902 would resolve it.

**Comment by csegedicsaba** [comment]
Thanks for quick reply!

How can I install the operator from develop branch?
What is the next release date?

**Comment by qvdang** [comment]
I don't know when is the next release but you can build it yourself.  It's straightforward:
https://oracle.github.io/weblogic-kubernetes-operator/developerguide/building/

**Comment by tbarnes-us** [comment]
I'm closing this because I'm pretty sure the fix has made it into a public release branch by now.  

Thank you for filing the Issue!
