### ISSUE TITLE
includeServerOutInPodLog implementation

### ISSUE THREAD

**Issue by csegedicsaba** [oracle/weblogic-kubernetes-operator#1991]
includeServerOutInPodLog is implemented as **tail**ing the file specified in -Dweblogic.Stdout server startup parameter.
Can this be implemented without starting the server with -Dweblogic.Stdout parameter? (no *.out file will be created)

Overriding the -Dweblogic.Stdout with /proc/1/fd/1 (=stdout) (specifying in USER_MEM_ARGS overrides the value generated by nodemanager) works on CRI-O container runtime fine.

On the other hand it would be great a includeServer**Log**InPodLog for including server log too. Sometime mystic error can be found in this log only.

**Comment by tbarnes-us** [comment]
> Can this be implemented without starting the server with -Dweblogic.Stdout parameter? (no *.out file will be created) ... Overriding the -Dweblogic.Stdout with /proc/1/fd/1 (=stdout) (specifying in USER_MEM_ARGS overrides the value generated by nodemanager) works on CRI-O container runtime fine.

Why is this helpful? 

(Side note: the operator defaults USER_MEM_ARGS to `-Djava.security.egd=file:/dev/./urandom`, which can significantly speedup boot time on systems with low entropy.)

> On the other hand it would be great a includeServerLogInPodLog for including server log too. Sometime mystic error can be found in this log only.

WebLogic stdout can be configured to be more verbose via configuration or system properties.  For example pass `-Dweblogic.log.StdoutSeverity=Debug` in JAVA_OPTIONS .  I recall that there's also an additional option to cause stdout so that it doesn't truncate stack dumps in its messasges...

**Comment by tbarnes-us** [comment]
Another side note:  I've been told that verbose pod logs can sometimes be problematic. They take up disk space on the nodes, and so additional "manual" steps at the k8s machine level outside of k8s itself may be needed to keep the files trimmed...

**Comment by csegedicsaba** [comment]
Our original concept was redirecting application logs to stdout too. In this case the server's .out log would be quite big because no rotation can be configured on it. Redirecting stdout direct to container out (without writing the server's .out log and tailing it) would solve this problem.
It is not CRI-O issue only.

Finally we decide to use fluentd as side container for pushing all logs (server's .log/.out/access log, application logs, gc logs) to ELK.

**Comment by tbarnes-us** [comment]
Sounds like a good solution to me - thanks for closing out the issue.

FYI, about:

>  In this case the server's .out log would be quite big because no rotation can be configured on it. 

This isn't true.  See [https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/#log-files](https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-domains/#log-files) for background.  

But note that the minimum amount of time between rotations can be something like a few minutes IIRC -- so if the logging is extremely verbose, then the logs can get grow quite large during this interim before they're rotated.
