### ISSUE TITLE
Error While runing create-domain.sh

### ISSUE THREAD

**Issue by rikumabokss** [oracle/weblogic-kubernetes-operator#2063]
Hi
Getting following Error:

**Comment by rikumabokss** [comment]
[vagrant@master1 domain-home-in-image]$ ./create-domain.sh -i my-inputs.yaml -o /tmp/t -u weblogic -p welcome1 -e -k
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export sslEnabled="false"
export adminPort="7001"
export adminServerSSLPort="7002"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="2"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export managedServerSSLPort="8002"
export productionModeEnabled="true"
export imagePullPolicy="IfNotPresent"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export httpAccessLogInLogHome="true"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="true"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="container-registry.oracle.com/middleware/weblogic:12.2.1.4"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"
export serverPodMemoryRequest="768Mi"
export serverPodCpuRequest="250m"
export istioEnabled="false"
export istioReadinessPort="8888"

Generating /tmp/t/weblogic-domains/sample-domain1/domain.properties
Generating /tmp/t/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /home/vagrant/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
Export environment variables from the /home/vagrant/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image/properties/docker-build/domain.properties properties file
 env_arg: CUSTOM_DOMAIN_NAME=sample-domain1
 env_arg: CUSTOM_SSL_ENABLED=false
 env_arg: CUSTOM_ADMIN_NAME=admin-server
 env_arg: CUSTOM_ADMIN_HOST=wlsadmin
 env_arg: CUSTOM_ADMIN_SERVER_SSL_PORT=7002
 env_arg: CUSTOM_MANAGED_SERVER_SSL_PORT=8002
 env_arg: CUSTOM_DEBUG_PORT=8453
 env_arg: CUSTOM_IMAGE_TAG=domain-home-in-image:12.2.1.4
 env_arg: CUSTOM_CLUSTER_NAME=cluster-1
 env_arg: CUSTOM_CLUSTER_TYPE=DYNAMIC
BUILD_ARG= --build-arg CUSTOM_DOMAIN_NAME=sample-domain1 --build-arg CUSTOM_SSL_ENABLED=false --build-arg CUSTOM_ADMIN_NAME=admin-server --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_SERVER_SSL_PORT=7002 --build-arg CUSTOM_ADMIN_SERVER_SSL_PORT=7002 --build-arg CUSTOM_ADMIN_SERVER_SSL_PORT=7002 --build-arg CUSTOM_MANAGED_SERVER_SSL_PORT=8002 --build-arg CUSTOM_DEBUG_PORT=8453 --build-arg CUSTOM_CLUSTER_NAME=cluster-1 --build-arg CUSTOM_CLUSTER_TYPE=DYNAMIC
CUSTOM_IMAGE_TAG  domain-home-in-image:12.2.1.4 
STEP 1: FROM container-registry.oracle.com/middleware/weblogic:12.2.1.4
STEP 2: MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
af0798f6bd55a597aef33c8be730ac75afc8ba0c01d832e8a82a34d8b6962822
STEP 3: ARG CUSTOM_DOMAIN_NAME="${CUSTOM_DOMAIN_NAME:-domain1}"
0053930826123c066588514d347d3718582da21a27458e047b8cc875197a5012
STEP 4: ARG CUSTOM_ADMIN_PORT="${CUSTOM_ADMIN_PORT:-7001}"  
db8e542c76e06aae37df205bd68767e0e69fccc41209b7b54373bbd171bc8148
STEP 5: ARG CUSTOM_ADMIN_SERVER_SSL_PORT="${CUSTOM_ADMIN_SERVER_SSL_PORT:-7002}"  
a53b8c5b94cee27920a552c6c9c6b632de8ab48c366c518171b1b77bfff8e7cf
STEP 6: ARG CUSTOM_MANAGED_SERVER_PORT="${CUSTOM_MANAGED_SERVER_PORT:-8001}"
e8ec70994cac457883ee3b6a7c955e9aff614ca59d9d5f494ee9b5fd8743b254

STEP 7: ARG CUSTOM_MANAGED_SERVER_SSL_PORT="${CUSTOM_MANAGED_SERVER_SSL_PORT:-8002}"
581f0c74ca23098a75d6522dfdfeaf5f4ac2e321d55b4ab66fa8f530c9f01652
STEP 8: ARG CUSTOM_DEBUG_PORT="${CUSTOM_DEBUG_PORT:-8453}"
7218369aba6b15d848680315b2744f1f96766886c1540a9469cf8d3f69bf98a0
STEP 9: ARG CUSTOM_ADMIN_NAME="${CUSTOM_ADMIN_NAME:-admin-server}"
52f43c6626e8673526d3d88ca60e51eba9f667148df42f01c3ed61666632ac13
STEP 10: ARG CUSTOM_ADMIN_HOST="${CUSTOM_ADMIN_HOST:-wlsadmin}"
1b5906bc4ce93fe62696a9e4ab573003c36ad3dbfb677e0ae9b7896adcbedd46
STEP 11: ARG CUSTOM_CLUSTER_NAME="${CUSTOM_CLUSTER_NAME:-DockerCluster}"
6ff2e8dbaa73f006c0c4243c7e9470a160dcb4a1b20f763e80f1dfec79f2a108
STEP 12: ARG CUSTOM_SSL_ENABLED="${CUSTOM_SSL_ENABLED:-false}"
0d869116f7709ed8de5b0caefd197f88d171f040a239a44d1da97f4fbd8dae05
STEP 13: ENV ORACLE_HOME=/u01/oracle     PROPERTIES_FILE_DIR="/u01/oracle/properties"     SSL_ENABLED="${CUSTOM_SSL_ENABLED}"     DOMAIN_NAME="${CUSTOM_DOMAIN_NAME}"     DOMAIN_HOME="/u01/oracle/user_projects/domains/${CUSTOM_DOMAIN_NAME}"     ADMIN_PORT="${CUSTOM_ADMIN_PORT}"     ADMIN_SERVER_SSL_PORT="${CUSTOM_ADMIN_SERVER_SSL_PORT}"     ADMIN_NAME="${CUSTOM_ADMIN_NAME}"     ADMIN_HOST="${CUSTOM_ADMIN_HOST}"     CLUSTER_NAME="${CUSTOM_CLUSTER_NAME}"     MANAGED_SERVER_PORT="${CUSTOM_MANAGED_SERVER_PORT}"     MANAGED_SERVER_SSL_PORT="${CUSTOM_MANAGED_SERVER_SSL_PORT}"     MANAGED_SERV_NAME="${CUSTOM_MANAGED_SERV_NAME}"     DEBUG_PORT="8453"     PATH=$PATH:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:${DOMAIN_HOME}:${DOMAIN_HOME}/bin:/u01/oracle
7304082e82da2a4981a81d62b9c697a650545a5e4351f193a3f06fda93b25581
STEP 14: COPY --chown=oracle:root container-scripts/* /u01/oracle/
8508afd5471b19378cdbfc06393228956bd5b1e1d81068b44b49cdb7c35fd9e0


STEP 15: USER root
6f9cae0999fb8f17830c6c0dc64a21a98cd0ded9ada8ec57134365952816b2b3

STEP 16: RUN chmod +xw /u01/oracle/*.sh &&     chmod +xw /u01/oracle/*.py &&     mkdir -p ${PROPERTIES_FILE_DIR} &&     mkdir -p $DOMAIN_HOME &&     chown -R oracle:root $DOMAIN_HOME/.. &&     chown -R oracle:root ${PROPERTIES_FILE_DIR}
stat /run/runc/buildah-buildah595899270: permission denied
error running container: error creating container for [/bin/sh -c chmod +xw /u01/oracle/*.sh &&     chmod +xw /u01/oracle/*.py &&     mkdir -p ${PROPERTIES_FILE_DIR} &&     mkdir -p $DOMAIN_HOME &&     chown -R oracle:root $DOMAIN_HOME/.. &&     chown -R oracle:root ${PROPERTIES_FILE_DIR}]: : exit status 1

Error: error building at STEP "RUN chmod +xw /u01/oracle/*.sh &&     chmod +xw /u01/oracle/*.py &&     mkdir -p ${PROPERTIES_FILE_DIR} &&     mkdir -p $DOMAIN_HOME &&     chown -R oracle:root $DOMAIN_HOME/.. &&     chown -R oracle:root ${PROPERTIES_FILE_DIR}": error while running runtime: exit status 1
[ERROR] Create domain sample-domain1 failed.

**Comment by tbarnes-us** [comment]
I'm sorry you didn't get a response to this Issue, but am closing the issue assuming that you have a solution by now.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.
