### ISSUE TITLE
Documentation : Warning about SOA be only supported for non-production use in Kubernetes

### ISSUE THREAD

**Issue by pasimoes** [oracle/weblogic-kubernetes-operator#2110]
After the [public announcement](https://blogs.oracle.com/integration/announcing-oracle-soa-suite-on-containers-kubernetes-for-production-workloads) about the general availability of Oracle SOA Suite on Containers and Kubernetes for Production environments. IMO the [warning message](https://oracle.github.io/weblogic-kubernetes-operator/userguide/managing-fmw-domains/soa-suite/) (box) can be removed from documentation.

**Comment by rosemarymarano** [comment]
@tbarnes-us Documentation for Managing SOA domains was moved out of the Oracle WebLogic Server Kubernetes Operator project to the Oracle Fusion Middleware on Kubernetes project a while ago, https://oracle.github.io/fmw-kubernetes/.
