### ISSUE TITLE
Managed server not connecting to Admin in a weblogic container

### ISSUE THREAD

**Issue by pradeepakiwate** [oracle/weblogic-kubernetes-operator#2116]
Hi All,
I have created a weblogic container with a domain and admin server using the Oracle registry image and the below command

docker run -d -p 7001:7001 -p 9002:9002 --name WLS_CONTAINER -v $PWD:/u01/oracle/properties container-registry.oracle.com/middleware/weblogic:12.2.1.4-dev

My container is up and running. I am able to access the admin console via 9002 port (https).

After creating a node manager and a managed server from the admin console, the attempt to start the managed server is failing.

1. When we attempt to start the managed server from nodemanager, i can see in the debug that it is using startweblogic instead of startManagedWebLogic
2. When i attempt to start the managed server from docker bash, with the command

startManagedWebLogic.sh  ms1 https://adminip:9002, it fails as it is not able to connect to the admin server.

Please advise on solution for the same.

**Comment by mriccell** [comment]
Are you using the WebLogic Operator?

**Comment by tbarnes-us** [comment]
This does not look like a WKO question, feel free to re-open the issue if I'm incorrect.

For future questions of this nature please feel free to use WebLogic's public `#general` slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/).
