### ISSUE TITLE
problems when i try to connecting in the admin server

### ISSUE THREAD

**Issue by joaqquin89** [oracle/weblogic-kubernetes-operator#2172]
Hi everybody

I have a big problem when i try to use weblogic operator , because i did the tutorial(this tutorial https://oracle.github.io/weblogic-kubernetes-operator/samples/simple/domains/domain-home-in-image/ ) step by step  , but when i try to access to the admin console, i have an authentication denied error (below i show the photo)

![image](https://user-images.githubusercontent.com/16735054/106344837-eb711e00-628a-11eb-8d68-b9bfb0ce2bd0.png)

My first thinking was ... oohh maybe i put wrong the credentials when i added the secret in the domain ... but for my surprise  , the username and the password were ok ... my next step in this troubleshooting tasks as try to connecting to the admin server using wlst , i tought ... mm if the credentials are bad ... i could not connecting , but for my surprise again ... i could connecting to the admin server using t3 (below i attached the image)

![image](https://user-images.githubusercontent.com/16735054/106344990-ca5cfd00-628b-11eb-929d-c09c08a17cf9.png)

so i m not shure about.... how could i to solve this problem?

thanks

**Comment by joaqquin89** [comment]
PD: i'm using Weblogic operator 3.0

**Comment by marinakog** [comment]
It looks like you have login info in Spanish on website ,could you please switch to English and use your credentials ?

**Comment by joaqquin89** [comment]
@marinakog  ,the problem is the HTTPS , because i defined an ingress controller (using nginx ) , but today i left the ssl annotations( using http way  ) in my ingress and i could using the console ... maybe the enforce ssl cause the problem.

then ... why activate the ssl cause problems ?

**Comment by marinakog** [comment]
just to verify when you could not connect to console using your credentials you used this url  -https://${HOSTNAME}:${SSLPORT}/console , is it correct?

**Comment by joaqquin89** [comment]
@marinakog  , yes i'm trying to connecting  to https://name-dns/console .., because i'm using nginx ingress controller .

**Comment by marinakog** [comment]
is it possible to share your ingress deployment yaml ? also have you tried to access console via curl?

**Comment by joaqquin89** [comment]
sure , let me share you the deployment domain.yaml and the ingress.yaml

**Comment by joaqquin89** [comment]
`# Copyright (c) 2017, 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
#
# This is an example of how to define a Domain resource.
#
apiVersion: "weblogic.oracle/v8"
kind: Domain
metadata:
  name: sample
  namespace: domain1
  labels:
    weblogic.domainUID: sample
spec:
  # The WebLogic Domain Home
  domainHome: /u01/oracle/user_projects/domains/sample

  # The domain home source type
  # Set to PersistentVolume for domain-in-pv, Image for domain-in-image, or FromModel for model-in-image
  domainHomeSourceType: Image

  # The WebLogic Server image that the Operator uses to start the domain
  image: "iad.ocir.io/falabellaoraclecloud/weblogick8s:2.0.0"

  # imagePullPolicy defaults to "Always" if image version is :latest
  imagePullPolicy: "IfNotPresent"

  # Identify which Secret contains the credentials for pulling an image
  imagePullSecrets:
  - name: oci-registry

  # Identify which Secret contains the WebLogic Admin credentials (note that there is an example of
  # how to create that Secret at the end of this file)
  webLogicCredentialsSecret: 
    name: sample-weblogic-credentials

  # Whether to include the server out file into the pod's stdout, default is true
  includeServerOutInPodLog: true

  # Whether to enable log home
  # logHomeEnabled: false

  # Whether to write HTTP access log file to log home
  # httpAccessLogInLogHome: true

  # The in-pod location for domain log, server logs, server out, introspector out, and Node Manager log files
  # logHome: /shared/logs/domain1
  # An (optional) in-pod location for data storage of default and custom file stores.
  # If not specified or the value is either not set or empty (e.g. dataHome: "") then the
  # data storage directories are determined from the WebLogic domain home configuration.
  dataHome: ""


  # serverStartPolicy legal values are "NEVER", "IF_NEEDED", or "ADMIN_ONLY"
  # This determines which WebLogic Servers the Operator will start up when it discovers this Domain
  # - "NEVER" will not start any server in the domain
  # - "ADMIN_ONLY" will start up only the administration server (no managed servers will be started)
  # - "IF_NEEDED" will start all non-clustered servers, including the administration server and clustered servers up to the replica count
  serverStartPolicy: "IF_NEEDED"

  serverPod:
    # an (optional) list of environment variable to be set on the servers
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m "
    resources:
      requests: 
        memory: "768Mi"
        cpu: "250m"
    # volumes:
    # - name: weblogic-domain-storage-volume
    #   persistentVolumeClaim:
    #     claimName: domain1-weblogic-sample-pvc
    # volumeMounts:
    # - mountPath: /shared
    #   name: weblogic-domain-storage-volume

  # adminServer is used to configure the desired behavior for starting the administration server.
  adminServer:
    # serverStartState legal values are "RUNNING" or "ADMIN"
    # "RUNNING" means the listed server will be started up to "RUNNING" mode
    # "ADMIN" means the listed server will be start up to "ADMIN" mode
    serverStartState: "RUNNING"
    adminService:
      channels:
    # The Admin Server's NodePort
       - channelName: default
         nodePort: 30701
    # Uncomment to export the T3Channel as a service
       - channelName: T3Channel

  # clusters is used to configure the desired behavior for starting member servers of a cluster.  
  # If you use this entry, then the rules will be applied to ALL servers that are members of the named clusters.
  clusters:
  - clusterName: cluster-1
    serverStartState: "RUNNING"
    serverPod:
      # Instructs Kubernetes scheduler to prefer nodes for new cluster members where there are not
      # already members of the same cluster.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "weblogic.clusterName"
                      operator: In
                      values:
                        - $(CLUSTER_NAME)
                topologyKey: "kubernetes.io/hostname"
    replicas: 2
  # The number of managed servers to start for unlisted clusters
  # replicas: 1

  # Istio
  # configuration:
  #   istio:
  #     enabled: false
  #     readinessPort: 8888

`

the ingress is 

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pathrouting
  namespace: domain1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - host: example-core.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-cluster-cluster-1
          servicePort: 8001
      - path: /console
        backend:
          serviceName: sample-admin-server
          servicePort: 7001`

**Comment by joaqquin89** [comment]
`apiVersion: "weblogic.oracle/v8"
kind: Domain
metadata:
  name: sample
  namespace: domain1
  labels:
    weblogic.domainUID: sample
spec:
  domainHome: /u01/oracle/user_projects/domains/sample
  domainHomeSourceType: Image

  image: "iad.ocir.io/falabellaoraclecloud/weblogick8s:2.0.0"

  imagePullPolicy: "IfNotPresent"

  imagePullSecrets:
  - name: oci-registry

  webLogicCredentialsSecret: 
    name: sample-weblogic-credentials

  includeServerOutInPodLog: true

  dataHome: ""

  serverStartPolicy: "IF_NEEDED"

  serverPod:
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m "
    resources:
      requests: 
        memory: "768Mi"
        cpu: "250m"

  adminServer:
    serverStartState: "RUNNING"
    adminService:
      channels:
       - channelName: default
         nodePort: 30701
       - channelName: T3Channel

  clusters:
  - clusterName: cluster-1
    serverStartState: "RUNNING"
    serverPod:

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "weblogic.clusterName"
                      operator: In
                      values:
                        - $(CLUSTER_NAME)
                topologyKey: "kubernetes.io/hostname"
    replicas: 2`

**INGRESS**

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pathrouting
  namespace: domain1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: example-core.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-cluster-cluster-1
          servicePort: 8001
      - path: /console
        backend:
          serviceName: sample-admin-server
          servicePort: 7001

**Comment by marinakog** [comment]
thank you @joaqquin89 , but you also mentioned the issue happened with ssl, what configuration/steps had you performed for that?

**Comment by joaqquin89** [comment]
@marinakog  , yes the problem occur always when i enable the ssl ... in other hand i tried to enable the ssl using the nexts annotations:

    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

and the result was the same , but when i put both annotations in false , i could use the console

![image](https://user-images.githubusercontent.com/16735054/106611937-4a62bb80-6547-11eb-8334-ed0438f1dbd2.png)

thanks for your help

**Comment by joaqquin89** [comment]
@marinakog  , the information attached by my is usefull ??

**Comment by marinakog** [comment]
Hi @joaqquin89 unfortunately can't reproduce your problem, since it is basic auth error, some info should be posted in the admin server log. it feels like some config/env mismatch.

**Comment by joaqquin89** [comment]
hi @marinakog  , thanks for your response... maybe the mismatch is in some config(but i think that i need annotations in the ingress controller ) ... in other hands i will try to use traefik , because the examples are using traefik ... 

thanks for you help

**Comment by joaqquin89** [comment]
i used traefik to reproduce the example in the offcial doc , but i could achieve the https

**Comment by joaqquin89** [comment]
the problem was solved ,  we needed to configure the steps in this doc https://github.com/oracle/weblogic-kubernetes-operator/blob/master/kubernetes/samples/charts/nginx/README.md

regards
