### ISSUE TITLE
Invalid Domain Name

### ISSUE THREAD

**Issue by mjagyo** [oracle/weblogic-kubernetes-operator#2173]
I dont know if this is a newbie question but I could not understand the issue here, I tried removing the hyphens (-), but still doesnt work is this really the issue or I am missing something here.

```
###<Feb 1, 2021 10:00:06 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12205> <Writing base domain sample-domain1 to directory /u01/oracle/user_projects/domains/sample-domain1
com.oracle.cie.domain.script.ScriptException: 60305: Invalid domain name.
60305: The specified domain name is invalid. It must include only alphanumeric characters, hyphens (-) or underscore characters (_) and contain at least one letter but must not start with a number.
60305: Correct the domain name.
```
Here is the domain.properties file sample content:
```
DOMAIN_NAME=sample-domain1
ADMIN_PORT=30701
ADMIN_NAME=admin-server
ADMIN_HOST=255.255.255.255 (sample ip address)
MANAGED_SERVER_PORT=8001
MANAGED_SERVER_NAME_BASE=managed-server
CONFIGURED_MANAGED_SERVER_COUNT=2
CLUSTER_NAME=cluster-1
DEBUG_PORT=8453
...
```

Thanks for the help!

**Comment by markxnelson** [comment]
That domain name looks fine.  Could you please share a little more detail?  Are you creating the domain with WDT?

**Comment by mjagyo** [comment]
@markxnelson I have been deploying this on an aws instance and currently trying to deploy this on a ec2 instance. 

And YES I am deploying using weblogic-deploy-tool, I am also using weblogic-operator version 3.1.1.

**Comment by mjagyo** [comment]
Closing this one, filed the issue on WDT Repository: https://github.com/oracle/weblogic-deploy-tooling/issues/830
