### ISSUE TITLE
Readiness probe failed for both Admin and MS

### ISSUE THREAD

**Issue by abinashkd** [oracle/weblogic-kubernetes-operator#2190]
Upon the deployment of domain, both admin and ms server readiness probe are failing. 
The domain is active but the readiness probe never recovers, thus it is difficult to integrate with Istio.

Warning  Unhealthy  27s (x4 over 42s)  kubelet, 10.215.101.2  Readiness probe failed: Get http://172.30.68.114:8001/weblogic/ready: dial tcp 172.30.68.114:8001: connect: connection refused

 Warning  Unhealthy  4m14s  kubelet, 10.215.101.2  Readiness probe failed: Get http://172.30.68.113:7001/weblogic/ready: dial tcp 172.30.68.113:7001: connect: connection refused

Deployment Type: Model in image (base version: weblogic:12.2.1.4-dev)
Cluster: Openshift Cluster

**Comment by lennyphan** [comment]
Can you take a look at the logs of the pods (admin server and managed servers) to see if the WLS servers have reached RUNNING state.  Would like to see the state of the servers.

**Comment by jshum2479** [comment]
@abinashkd  What version of istio are you using?  istio 1.6.x is broken with headless service and will never work with WKO.

**Comment by abinashkd** [comment]
It was an configuration issue with istio readiness port, which is default to 8888, but I have configured it for 7001. Now pointing to 8888 got it working. Thanks @lennyphan @jshum2479
