### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-kubernetes-operator#2202]
There are some business cases where we are not allowed to move into containers. For example, BPM is not certified on containers, companies that do not want to use containers, etc. Thus, would not it be good to have some of these functionalities for domains running on virtual or physical machines? Executing tasks such as start servers, restart servers, stop servers, etc. on hundreds of domains are complex and prone to generate errors if we rely just on WLST scripts to do so.

Is it possible to standardize tools for cases like this?

**Comment by mriccell** [comment]
Kubernetes infrastructure, APIs, objects, services etc allows us to offer this functionality and offer high availability out of the box. 
WebLogic has functionality such as Node Managers, ZDT for updates, for monitoring you can use OEM etc.  that offers some of these capabilities.
The WebLogic Kubernetes Operator is specific to Kubernetes, the operator  is a controller that invokes K8s APIs, RBAC policies, creates services, etc  to manage the life cycle of the WebLogic domain in Kubernetes. This tool is specific to Kubernetes and can not run on physical machines or VMs.  Some of the tools in the WebLogic Kubernetes ToolKit can be used outside of  Kubernetes such as WebLogic Deploy Tooling, or Monitoring Exporter, Logging Exporter.
Hope this helps

**Comment by textanalyticsman** [comment]
Thanks a lot :)
