### ISSUE TITLE
problems with the service account 

### ISSUE THREAD

**Issue by joaqquin89** [oracle/weblogic-kubernetes-operator#2209]
Hi everybody , 

i have problems in my oke cluster deploying weblogic operator ... i'm using the oficial documentation to install weblogic operator and create an weblogic domain , the problem appear when i tried to start an weblogic domain ... because i could to start and weblogic cluster (admin server and managed servers) ... i applied the domain.yaml file but the operator didin't create the weblogic cluster (admin server and managed servers),  i seen the weblogic operator log and  appears  this message 

![image](https://user-images.githubusercontent.com/16735054/108508691-f112c000-729a-11eb-8c5a-40615bc43012.png)

in think that the reason of this problem is the cluster role and cluster role binding deployed by the weblogic operator.
i am using this operator "ghcr.io/oracle/weblogic-kubernetes-operator:3.1.3"

**Comment by bhavaniravichandran** [comment]
What namespace is the domain running on?
Do you see any errors in kubectl get events -n <domain-namespace>?
Also want to see the output of kubectl describe cm weblogic-operator-cm -n <weblogic-operator-namespace>

**Comment by joaqquin89** [comment]
@bhavaniravichandran  i create 2 domains called "domain1" and  "domain2" in the domain1 i can create a weblogic domain  and those servers works fine ... but in the domain 2 i have the next problem:

![image](https://user-images.githubusercontent.com/16735054/108543744-3ac3d080-72c4-11eb-86fe-af66f1f8191c.png)


the output  in the describe is :

joaquinjachurachavez@MacBook-Pro sample % kubectl describe cm weblogic-operator-cm -n  operator
Name:         weblogic-operator-cm
Namespace:    operator
Labels:       app.kubernetes.io/managed-by=Helm
              weblogic.operatorName=operator
Annotations:  meta.helm.sh/release-name: wl-operator
              meta.helm.sh/release-namespace: operator

Data
====
externalServiceNameSuffix:
----
-ext
internalOperatorCert:
----
LS0tLS.........................
serviceaccount:
----
weblogic-operator-sa
domainNamespaceLabelSelector:
----
weblogic-operator=enabled
domainNamespaceSelectionStrategy:
----
LabelSelector
domainNamespaces:
----
default
externalRestIdentitySecret:
----
https-secret-api
clusterSizePaddingValidationEnabled:
----
true
introspectorJobNameSuffix:
----
-introspector
Events:  <none>


i am very interesting to solve this problem because in my company we want to use in production weblogic operator.
my doubt 

regards

**Comment by bhavaniravichandran** [comment]
Which model are you running - domain-in-image, domain-on-pv or model-in-image?

**Comment by bhavaniravichandran** [comment]
Also, if you run "kubectl describe domain sample -n domain2" you might see error message in the status section

**Comment by joaqquin89** [comment]
i think that i solve this problem .. i enabled the next option : 

![image](https://user-images.githubusercontent.com/16735054/108559401-0e1ab380-72da-11eb-88eb-98631cbbaf63.png)

and i can see the wl infra in the namespaces (everything is ok) , but i have another doubt ... when i deploy the same domain.yml in another namespace (changing the domain name and  namespace ) in wl operator appears the nexts error:

![image](https://user-images.githubusercontent.com/16735054/108560006-db24ef80-72da-11eb-81a5-d48e57b2e934.png)

how can i manage the t3 port from domain.yaml file ?

thanks for your help

**Comment by bhavaniravichandran** [comment]
Can you please tell me what model your are running. I want to test what you are tryign to do first. Are you using domain in image model?

**Comment by bhavaniravichandran** [comment]
You must have to create the weblogic domain first with that domain name.

**Comment by joaqquin89** [comment]
@bhavaniravichandran , i am using the domain in image

**Comment by bhavaniravichandran** [comment]
You have to first create weblogic domain first. so, you have to update the create-domian-inputs.yaml int he samples first and run create-domain.sh. This will create an image with weblogic domain named domain2 and then create pods as well if you use the -e option. Changing the namespace and domain name in the domain.yaml file and apply the yaml file is not sufficient. Let me know if misunderstood your question.

**Comment by joaqquin89** [comment]
the problem was when i trying to bring up 2 domains with the same docker image (t3 port was the problem)
