### ISSUE TITLE
Limit log size

### ISSUE THREAD

**Issue by kenankule** [oracle/weblogic-kubernetes-operator#2220]
Currently the operator is writing its logs to a file and i couldnt find a way to limit the log size. The logs grow in time (especially with higher log levels like FINE) and with or without a PVC in place (mounted under /logs), this is a problem.

Either use log rotation or disable logging to a file if logstash/elk is not enabled.

**Comment by jshum2479** [comment]
Thanks @kenankule ,  we are looking into this.

**Comment by tbarnes-us** [comment]
Issue is resolved by #2229, which will be available in upcoming WKO version 3.2.  @rjeberhard FYI
