### ISSUE TITLE
creating domain-home-image failed with [ERROR] docker is not installed

### ISSUE THREAD

**Issue by shaunxa** [oracle/weblogic-kubernetes-operator#2225]
Hi Team,

I setup up a k8s cluster using https://github.com/oracle/vagrant-projects/tree/main/OLCNE. It uses cri-o instead of docker.

The step of creating domain-home-image failed with [ERROR] docker is not installed. See the details below. Is docker a requirement? and it doesn't support cri-o? or there is some other issue? Let me know if more details required. Thanks.

[vagrant@master1 domain-home-in-image]$ sudo crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.18.3
RuntimeApiVersion:  v1alpha1
[vagrant@master1 domain-home-in-image]$

[vagrant@master1 domain-home-in-image]$ ./create-domain.sh -i create-sample-domain-inputs.yaml -o /vagrant -u weblogic -p Welcome1$ -e
[ERROR] docker is not installed
[ERROR] The errors listed above must be resolved before the script can continue

**Comment by jshum2479** [comment]
This purpose of this script is to create an image using docker,  you will need to have docker installed.

**Comment by tbarnes-us** [comment]
I agree - docker is a pre-requisite for the sample. 

I'm closing this issue as resolved. Feel free to re-open if it's still a problem.  

@rjeberhard FYI
