### ISSUE TITLE
Typo in create-kuberetes-secrets folder name in samples

### ISSUE THREAD

**Issue by ashageetha** [oracle/weblogic-kubernetes-operator#2258]
Hi Team,
There is typo in folder name **create-kuberetes-secrets** present  in samples (weblogic-kubernetes-operator/kubernetes/samples/scripts/create-kuberetes-secrets/).

Typo: 'n' is missing from kuberetes.

**Comment by tbarnes-us** [comment]
I've put out a candidate pull #2287 to fix this.   @rjeberhard FYI

**Comment by tbarnes-us** [comment]
@ashageetha Thank you for pointing out the issue. The fix has been reviewed and merged, and should show up in the next release (3.2).
