### ISSUE TITLE
Update  the image field of the Operator values.yaml in release/3.0.4

### ISSUE THREAD

**Issue by anpanigr** [oracle/weblogic-kubernetes-operator#2264]
The values.yaml in the directory 
https://github.com/oracle/weblogic-kubernetes-operator/tree/release/3.0.4/kubernetes/charts/weblogic-operator

image: "oracle/weblogic-kubernetes-operator:3.0.4"  --> image: "ghcr.io/oracle/weblogic-kubernetes-operator:3.0.4"

**Comment by rjeberhard** [comment]
That chart is now updated.
