### ISSUE TITLE
README.md file is missing from integration-test directory 

### ISSUE THREAD

**Issue by anpanigr** [oracle/weblogic-kubernetes-operator#2266]
README.md file is missing from integration-test directory 
https://github.com/oracle/weblogic-kubernetes-operator/tree/master/integration-tests/

**Comment by ddsharpe** [comment]
The Readme.md file is in 3.0.x branches, but seems to have been lost cutting over to 3.1.x.

**Comment by tbarnes-us** [comment]
I see the integration-tests/README.md in the 'develop' and '3.2' branches.  

If it doesn't show up when 3.2 is cut, please re-open the issue.  @rjeberhard FYI
