### ISSUE TITLE
Voyager version mismatch in the Install and configure Voyager guide

### ISSUE THREAD

**Issue by scbarikGIT** [oracle/weblogic-kubernetes-operator#2349]
Hi Team,
In the Install and configure Voyager document the Voyager version is different in 2 different places.
In "Add the AppsCode chart repository" the Voyager version is 12.0.0 . 
But in the next point "Install the Voyager operator" the Voyager version is 10.0.0 . 
It should be same. 

Thanks!

**Comment by tbarnes-us** [comment]
Thanks for the heads up!

**Comment by tbarnes-us** [comment]
This looks like it has already been fixed in the main branch? See:

https://github.com/oracle/weblogic-kubernetes-operator/blob/main/kubernetes/samples/charts/voyager/README.md

If so, it should show up in the next release (and it might already be in the most recent release - haven't checked).

**Comment by tbarnes-us** [comment]
I'm closing the issue, please re-open if the problem hasn't been fixed.
