### ISSUE TITLE
Update WLS AKS Domain on PV guidance for memory considerations

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-kubernetes-operator#2415]
Consider [Configuring Heap Size](https://oracle.github.io/weblogic-kubernetes-operator/faq/resource-settings/#configuring-heap-size). The guidance should be updated to include the `-Xmx...` and also `serverPodMemoryRequest` and `serverPodMemoryLimit` values so that the problem reported [on slack](https://oracle-weblogic.slack.com/archives/CE3M9DGSY/p1621952312030200) does not manifest after a week of running.

**Comment by edburns** [comment]
Please assign this to @galiacheng .

**Comment by edburns** [comment]
Hello @mriccell please track this for any other manifestations of the problem in any other samples.  Cc: @rjeberhard .

**Comment by robertpatrick** [comment]
@tbarnes-us @ankedia @rosemarymarano It appears as though this issue was addressed by PR #2416 so why is this issue still open?

**Comment by rosemarymarano** [comment]
@robertpatrick I think you're correct. [OWLS-92880](https://jira.oraclecorp.com/jira/browse/OWLS-92880) WKO doc: Update tuning guidance for WLS Domain on Azure, should be closed as well.
