### ISSUE TITLE
MVP Placeholder documentation for WLS on AKS

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-kubernetes-operator#2591]
Per slack:

Put the AKS content 'At the top level between "Manage FMW Infrastructure domains" and "CI/CD Considerations".

Iterating at https://github.com/edburns/weblogic-kubernetes-operator/tree/edburns-msft-dd-1426715-wls-aks-docs .

**Comment by robertpatrick** [comment]
@edburns is this still relevant?
