### ISSUE TITLE
Difference in default values of `domain.spec.adminServer.adminChannelPortForwardingEnabled`

### ISSUE THREAD

**Issue by shashankkumarIITB** [oracle/weblogic-kubernetes-operator#2647]
As per [Domain.md](https://github.com/oracle/weblogic-kubernetes-operator/blob/main/documentation/domains/Domain.md#admin-server), the default value for `adminChannelPortForwardingEnabled` is `true`. 

However, running `kubectl explain domain.spec.adminServer.adminChannelPortForwardingEnabled` shows that the default value is `false`.

I think it is `false` by default.

**Comment by ankedia** [comment]
The default is `true` in Operator 4.0 release (`main` branch) and `false` in Operator 3.3.x release (release/3.3 branch). If you're using Operator version 3.3.x, please see [Domain.md](https://github.com/oracle/weblogic-kubernetes-operator/blob/release/3.3/documentation/domains/Domain.md) .
