### ISSUE TITLE
Document how to Create a Domain when the WebLogic image name is not store/oracle/weblogic:12.2.1.3

### ISSUE THREAD

**Issue by mriccell** [oracle/weblogic-kubernetes-operator#269]
We need to document how to change the WebLogic and Operator image names and generate the correct yaml for the Domain creation job.  This is specially important for OCI and OKE where the image names must be taged to push into OCIR 
docker tag store/oracle/weblogic:12.2.1.3 phx.ocir.io/weblogick8s/weblogic:12.2.1.3
docker tag weblogic-kubernetes-operator:developer phx.ocir.io/weblogick8s/weblogic-kubernetes-operator:developer 

The procedure is to edit the operator yaml create-weblogic-operator-inputs.yaml and change the parameter 
weblogicOperatorImage: phx.ocir.io/weblogick8s/weblogic-kubernetes-operator:developer

For the domain the image name must change in two templates
cd ~/weblogic-kubernetes-operator/kubernetes/internal and 
edit vi create-weblogic-domain-job-template.yaml & domain-custom-resource-template.yaml
Change :  image: "phx.ocir.io/weblogick8s/weblogic:12.2.1.3"

Now when the create-weblogic-domain.sh script is invoked the generated yaml have the correct image name and the domain is created properly.

**Comment by sishbi** [comment]
I have had to do this as well because I want to use a local registry which is accessible by the k8s cluster.  It would be good if you can provide a create-weblogic-domain-inputs.yaml parameter where the image name can be specified.
