### ISSUE TITLE
Using WLS 14c with WLS k8s operator: prone to admin server pod eviction.

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-kubernetes-operator#2693]
See https://github.com/oracle/weblogic-azure/pull/103 for complete details.

# Executive Summary

The WLS14c admin pod become evicted at age 2/3 days with error like Container weblogic-server was using 3300040Ki, which exceeds its request of 1610612736.

**Comment by robertpatrick** [comment]
@edburns After talking with the team that has been working with you on this, we feel that this is almost certainly a WLS 14.1.1 bug.  As such, @mriccell has created WLS Bug 33754157 for this issue.  She will work with the WLS Dev team to get a resolution for you.  At this point, I just don't see anything that the WebLogic Kubernetes Operator development team can do to our software to resolve the issue.
