### ISSUE TITLE
Create prometheus annotations on pods

### ISSUE THREAD

**Issue by markxnelson** [oracle/weblogic-kubernetes-operator#27]
We need to add a parameter that tells the operator that it should add these annotations to pods that it creates when we are using the prometheus integration and WLS Exporter: 

```
	prometheus.io/port: "8001"    # should be the ListenPort of the server in the pod 
	prometheus.io/path: /wls-exporter/metrics
	prometheus.io/scrape: "true"
```

**Comment by tbarnes-us** [comment]
Change merged via #110
