### ISSUE TITLE
Operator 3.3.5 chart version incorrectly mentioned as 4.0.0

### ISSUE THREAD

**Issue by sbattagi** [oracle/weblogic-kubernetes-operator#2718]
Hi,

From the operator 3.3.5 kubernetes charts, I see the chart version is mentioned as 4.0.0 (which looks incorrect) and also the image is set to 4.0.0 in the documentation. The 4.0.0 operator image doesn't exist so far (--set "image=ghcr.io/oracle/weblogic-kubernetes-operator:4.0.0")

Comparison 3.3.4 vs 3.3.5: https://github.com/oracle/weblogic-kubernetes-operator/compare/v3.3.4...v3.3.5

However I have cross-checked the same in 3.3.6 version, there the operator version is mentioned as 3.3.6 (which looks correct).

Kindly review the issue with operator 3.3.5 charts and provide the feedback.

Thanks
Samba

**Comment by rjeberhard** [comment]
The chart has been corrected.
