### ISSUE TITLE
Operator Docker image does not exists with :latest tag

### ISSUE THREAD

**Issue by jwveldhuis** [oracle/weblogic-kubernetes-operator#279]
```
docker pull container-registry-phx.oracle.com/middleware/weblogic-kubernetes-operator:latest
Error response from daemon: manifest for container-registry-phx.oracle.com/middleware/weblogic-kubernetes-operator:latest not found
```
https://github.com/oracle/weblogic-kubernetes-operator/blob/55f0b4695a6f077f5571992118fc4aa809fda266/kubernetes/create-weblogic-operator-inputs.yaml#L23

After updating the input file to fetch tag `0.2` the pull succeeded.

**Comment by rjeberhard** [comment]
We are waiting on the process that will publish the 1.0 image to OCR.  In the meantime, the best suggestion seems to be to update the documentation to not reference pulling the image from OCR, but instead suggesting that customers build the image locally or through Wercker.
