### ISSUE TITLE
Restart Evicted Pods

### ISSUE THREAD

**Issue by volkermauel** [oracle/weblogic-kubernetes-operator#2794]
Hey,

I'm currently using the operator in version 3.3.6 with the Domain-Home-In-Image mode.
I'm running into an issue, where a Pod might get evicted from a Node due to not enough ephemeral storage being available for logging.

The pods are assigned to qosclass guaranteed (so requests == limits for both, cpu and memory).
The issue here is that once pods are evicted by kubernetes, the operator does not seem to care about them anymore, so they stay in an Evicted state, thus the application might get unavailable.

Right now I'm working around this using a serviceaccount and a simple batch-script to manually remove those Pods, so the Operator can take over control again, but I think this is something the Operator should take care of.

Thanks!

**Comment by ankedia** [comment]
As per [this issue](https://github.com/kubernetes/kubernetes/issues/55051), the evicted pods deletion can be controlled through `--terminated-pod-gc-threshold` setting in kube-controller-manager. The recommendation is to update the kube-controller-manager config to set `--terminated-pod-gc-threshold 100` or similar small value.

The WebLogic Kubernetes Operator currently recreates a new pod only when the pod is fully removed. I will file an internal JIRA to track the enhancement to the operator to optionally recreate the evicted pods (for the pods created by the operator). We will let you know once the enhancement is implemented.

**Comment by ankedia** [comment]
Created JIRA OWLS-96896 to track this.

**Comment by tbarnes-us** [comment]
@volkermauel Thank you for taking the time to file the Issue - the operator dev team will look into at least documenting the problem and its work-arounds if it's not practical for the operator to automatically handle it - much appreciated!

**Comment by rjeberhard** [comment]
This fix will be in today's 3.4.0 release.
