### ISSUE TITLE
MinRAMPercentage is not InitialRAMPercentage

### ISSUE THREAD

**Issue by aheritier** [oracle/weblogic-kubernetes-operator#2795]
In many documentations and settings you are using `MinRAMPercentage` while it should be `InitialRAMPercentage`

Ref:
* https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html
* https://www.baeldung.com/java-jvm-parameters-rampercentage

> The MinRAMPercentage parameter, unlike its name, allows setting the maximum heap size for a JVM running with a small amount of memory (less than 200MB).

```
-XX:MinRAMPercentage=percent
Sets the maximum amount of memory that the JVM may use for the Java heap before applying ergonomics heuristics as a percentage of the maximum amount determined as described in the -XX:MaxRAM option for small heaps. A small heap is a heap of approximately 125 MB. The default value is 50 percent.

The following example shows how to set the percentage of the maximum amount of memory used for the Java heap for small heaps:

-XX:MinRAMPercentage=75
```

**Comment by ankedia** [comment]
Yes, we will update the documentaiton to clarify `-XX:MinRAMPercentage` and use -XX:InitialRAMPercentage instead of -XX:MinRAMPercentage . I will file an internal JIRA to track this.

**Comment by ankedia** [comment]
The WKO documentation and sample files have been updated to use `InitialRAMPercentage` instead of `MinRAMPercentage`.
