### ISSUE TITLE
weblogic-kubernetes-operator:3.3.8 create-domain error？？？

### ISSUE THREAD

**Issue by dai0384448** [oracle/weblogic-kubernetes-operator#2800]
ENV：
CentOS Linux release 7.7.1908 (Core)
helm Version:"v3.3.4", 
Docker version 19.03.1, build 74b1e89
 kubectl ：v1.20.15

[issue]
command：./create-domain.sh -i my-inputs.yaml -o /testweb -u weblogic -p Weblogic123 -e
error log：
[信息     ] WebLogic Image Tool version 1.11.0
[信息     ] Image Tool build ID: 7da5a263-76df-482d-b604-025c260483e2
[信息     ] Temporary directory used for image build context: /root/wlsimgbuilder_temp1212033880417942940
[信息     ] Inspecting wls:12.2.1.4.0, this may take a few minutes if the image is not available locally.
[严重     ] The Oracle Home directory in --fromImage=wls:12.2.1.4.0 has an owner and group of oracle:oracle.  You must update the image with the same user and group setting from when it was created. Example: --chown=oracle:oracle
[ERROR] Error: Create domain domain1 failed.

How can I deal with this problem?

**Comment by marinakog** [comment]
could you please list your my-inputs.yaml?  How did you create wls:12.2.1.4.0 ?

**Comment by dai0384448** [comment]
version: create-weblogic-sample-domain-inputs-v1
sslEnabled: false
adminPort: 7001
adminServerSSLPort: 7002
adminServerName: admin-server
domainUID: domain1
domainHome: /u01/oracle/user_projects/domains/domain1
serverStartPolicy: IF_NEEDED
clusterName: cluster-1
configuredManagedServerCount: 5
initialManagedServerReplicas: 2
managedServerNameBase: managed-server
managedServerPort: 8001
managedServerSSLPort: 8002
productionModeEnabled: true
imagePullPolicy: IfNotPresent
weblogicCredentialsSecretName: sample-domain1-weblogic-credentials
includeServerOutInPodLog: true
logHomeOnPV: false
logHome: /shared/logs/domain1
httpAccessLogInLogHome: true
t3ChannelPort: 30012
exposeAdminT3Channel: false
adminNodePort: 30701
exposeAdminNodePort: true
namespace: sample-domain1-ns
javaOptions: -Dweblogic.StdoutDebugEnabled=false
persistentVolumeClaimName: domain1-weblogic-sample-pvc
domainPVMountPath: /shared
domainHomeImageBase: wls:12.2.1.4.0
createDomainWlstScript: wlst/create-wls-domain.py
createDomainWdtModel: wdt/wdt_model_dynamic.yaml
mode: wdt
serverPodMemoryRequest: "768Mi"
serverPodCpuRequest: "250m"
istioEnabled: false
istioReadinessPort: 8888



==========================================
[root@master bin]# 
[root@master bin]# ll
总用量 16
-rwxr-x--- 1 root root  972 1月  31 10:06 imagetool.cmd
-rwxr-x--- 1 root root 1121 1月  31 10:06 imagetool.sh
-rwxr-x--- 1 root root 1132 1月  31 10:06 logging.properties
-rwxr-x--- 1 root root 1216 1月  31 10:06 setup.sh
[root@master bin]# 
[root@master bin]# 
[root@master bin]# ll /root/
总用量 1029972
-rwxr-xr-x   1 root   root        1604 2月  18 22:28 1-ini_linux.sh
-rwxr-xr-x   1 root   root        2254 2月  18 22:42 2-install_docker_k8s.sh
-rwxr-xr-x   1 root   root        2207 2月  18 22:55 3-download_k8s_images.sh
-rw-------.  1 root   root        1283 11月 13 2019 anaconda-ks.cfg
drwxr-xr-x   2 root   root          23 2月  19 00:18 cache
-rw-r--r--   1 root   root   866494253 6月  24 2020 fmw_12.2.1.4.0_wls_Disk1_1of1.zip
-rw-r--r--   1 root   root    12752995 9月  23 2020 helm-v3.3.4-linux-amd64.tar.gz
drwxr-x---   4 root   root          66 1月  31 10:06 imagetool
-rw-r--r--   1 root   root     2121727 2月  16 12:56 imagetool.zip
-rw-r--r--   1 root   root   173271626 1月   7 2019 jdk-8u45-linux-x64.tar.gz
-rw-r--r--   1 root   root        5692 2月  18 23:05 kube-flannel.yml
drwxr-xr-x   2   3434   3434        38 2月  18 23:44 linux-amd64
-rw-r--r--   1 root   root       14216 2月  23 16:11 traefik-9.1.1.tgz
drwxr-xr-x  13 oracle oracle      4096 2月  18 23:35 weblogic-kubernetes-operator
drwxrwxrwx   3 oracle oracle        30 2月  21 09:44 webtest
[root@master bin]# ./imagetool.sh create --tag wls:12.2.1.4.0 --version 12.2.1.4.0 --jdkVersion 8u45

**Comment by marinakog** [comment]
hi @dai0384448 , you have created image wls:12.2.1.4.0 with --chown=oracle:oracle but you used create-domain.sh. script where umagetool tries to update the image with --chown=oracle:root.  You can change the script create-domain.sh to use --chown=oracle:oracle or create image with --chown=oracle:root

**Comment by dai0384448** [comment]
[command]
./imagetool.sh create --tag wls:12.2.1.4.0 --version 12.2.1.4.0 --jdkVersion 8u45 --chown=oracle:root
===================================================================
This issue has been resolved。  thank you so much。
