### ISSUE TITLE
Introspector pod fails initialisation

### ISSUE THREAD

**Issue by th3n3rd** [oracle/weblogic-kubernetes-operator#2819]
## Context
I am using the Model In Image deployment strategy, with auxiliary images, in order to deploy a sample application on k8s via the Oracle WebLogic Operator (v3.3.7).
The auxiliary image currently uses ubuntu bionic as a base image, which default shell is dash as in `/bin/sh -> dash`.
The latter does only support POSIX compliant instructions.

## Problem
When the introspector pod kicks in, the init containers fails to initialise the pod with the following error:

```shell
./auxImage.sh: 25: [: 1: unexpected operator
./auxImage.sh: 27: ./auxImage.sh: source: not found
[SEVERE] Missing file /weblogic-operator/scripts/utils_base.sh
```

The source of the problem seems to be related to the [auxImage](https://github.com/oracle/weblogic-kubernetes-operator/blob/main/operator/src/main/resources/scripts/auxImage.sh#L1) script shebang setup, currently equal to `#!/bin/sh`.
The script currently uses a non portable set of instructions, i.e. non-POSIX compliant, hence if the default shell in the OS is strictly supporting only POSIX instructions (like `dash`) the script does not work as expected.

## Potential solutions
1. Replace the shebang with `#!/bin/bash`, leaving the code as is
2. Replace script instructions with portable POSIX compliant ones, e.g. use `.` instead of `source`, etc

**Comment by robertpatrick** [comment]
This issue should be addressed and available in the upcoming 3.4.0 release.
