### ISSUE TITLE
change the default logger format of the operator

### ISSUE THREAD

**Issue by lilyhe123** [oracle/weblogic-kubernetes-operator#285]
The default logger format 'oracle.kubernetes.operator.logging.LoggingFormatter' is not human-reading-friendly. Can we change it to a simpler format like java.util.logging.SimpleFormatter, in case ELK integration is not enabled, or just for console output. It can make it easier for troubleshooting.

**Comment by simon-meng-cn** [comment]
To replace LoggingFormatter with SimpleFormatter, you need to modify the formatter configuration in abc.properties and operator/src/main/java/oracle/kubernetes/operator/logging/LoggingFacade.java. Then rebuild the operator to make it effective.

**Comment by simon-meng-cn** [comment]
We can configure formatter for ConsoleHander and FileHandler in the configuration file src/scripts/logstash.properties. By default only the configured formatter for FileHandler take effect. Operator restricts the ConsoleHander to only use LoggingFormatter. If developer want to use different formatter for ConsoleHander in experiment. Need change code in operator/src/main/java/oracle/kubernetes/operator/logging/LoggingFacade.java.
