### ISSUE TITLE
Creating more than one cluster in domain on pv

### ISSUE THREAD

**Issue by jdvacasf** [oracle/weblogic-kubernetes-operator#2900]
I have reviewed the examples and I have not seen how to create more than one cluster.
When creating a new fmw domain in pv there is no possibility to create more than one cluster. I have only seen how I manage to modify createFMWDomain.py with the values ​​of the new cluster.

**Comment by anpanigr** [comment]
The example files/directory/scripts  are provided to demonstrate the usage WebLogic Kubernetes Operator to stat a Basic single cluster WebLogic domain. For multi cluster WebLogic domain,  you need to manually modify the createFMWDomain.py and jrf-domain-template.yaml  ( in weblogic-kubernetes-operator/kubernetes/samples/scripts/common directory) to add the the new cluster before running the sample script.

**Comment by robertpatrick** [comment]
@jdvacasf Does this answer your question?

**Comment by jdvacasf** [comment]
Yes, thanks.
