### ISSUE TITLE
Speedup build: speedup HealthCheckHelperTest, or convert to integration test

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-kubernetes-operator#295]
The HeathCheckHelperTest operator build unit test takes over two minutes even when it runs well, and the build takes less than a minute without it.

A slow build lowers developer productivity, so the test should be sped-up to run in seconds at worst or it should be converted to an integration test.

**Comment by russgold** [comment]
Revised pure unit test now tests less than a second.

see change a5c57973fd53cee4f9f9a070ca22a7415
