### ISSUE TITLE
Question about 'Using a WLDF policy rule and script action to call the operator's REST scale API'

### ISSUE THREAD

**Issue by jhzhu89** [oracle/weblogic-kubernetes-operator#298]
Hi,

I need to enable the auto scaling for a cluster, I have watched [the video](https://www.youtube.com/watch?v=Q8iZi2e9HvU&feature=youtu.be), now I am trying to scale up my cluster using scalingAction.sh.

I encountered some problems. I have these questions:

- I deployed the operator into its own namespace, for example, weblogic-operator, and deployed domains into their own namespaces, for example, weblogic-domain1, as mentioned in [Architectural overview](https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/architecture.md). While I found that in this video, the instructor deployed them into one namespace - weblogic-operator, why is that?
- Is the script `$WEBLOGIC_KUBERNETES_OPERATOR_HOME/src/scripts/scaling/scalingAction.sh` the same as the script used by the instructor? I had to provide many params to get it run.
- I tried running this script in domain*-admin-server as the instructor did, why I encountered such error:
```
"status": "Failure",
  "message": "services \"internal-weblogic-operator-svc\" is forbidden: User \"system:serviceaccount:weblogic-domain2:default\" cannot get services/status in the namespace \"weblogic-operator\"",        
  "reason": "Forbidden",
  "details": {
    "name": "internal-weblogic-operator-svc",
    "kind": "services"
  },
  "code": 403
```
So I switched to run this script in weblogic-operator-*, and modified some roles, then the script was able to query weblogic operator service port, etc. While it failed to test the existence of 
`${INTERNAL_OPERATOR_CERT}`. Could you explain what this ENV var is?
- Is there a detailed step by step tutorial about running scalingAction.sh and defining WLDF policy rule and script action?

Thanks.

**Comment by jhzhu89** [comment]
Hi @alai8 ,

Thanks for the new link, I followed it to create the policy and action, but I still cannot make it work.

I was trying running scalingAction.sh on admin-server directly, while I got 403 with no response body.
Here is the request generated by the script:

```
curl -v -k --cacert weblogic_operator.pem -X POST -H 'Content-Type: application/json' -H 'X-Requested-By: WLDF' -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3ZWJsb2dpYy1kb21haW4yIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4taDY3aGYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk4ODhmZTlkLTVkOTItMTFlOC05ZWNhLTBjYzQ3YWIxZjgyNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp3ZWJsb2dpYy1kb21haW4yOmRlZmF1bHQifQ.he_4EaAZSSMIyDvXbUJ8jRPbeBBlzAkcXOTAgEyTulj6JEX4SxvrV7wUAKwfIp03AJsyHYn59de4OvkGtZ_jMoTWxz8oI7mhfq0GhyKVs2pGNrrOc9cBmGPb4zwoSxKHAFW3aWxBxtGAGixJCluMglhGYcI32h5PHTU1yevytZ_8epVIwkrPaMHXUnS0l66h8mz_obqbyLZ-myqKl4Luvm5B1Typ-y0eOZpYpwRvDJj8iRO-gsFsbvP6aalc09Ft_d1Vz3ZgRXRzObYsebWzK_ufOss2ZEsSKQPw026F5UiXmxymtLoOzYd-ooFwtKUtmFOezeDI5U5_MlyRGxLwRw' -d '{ 
    "managedServerCount": 4
}' https://10.10.10.17:8082/operator/v1/domains/domain2/clusters/cluster-1/scale
```

I cannot figure out what happened, the operator just printed out this line in log file:
`{"timestamp":"05-23-2018T05:38:46.974+0000","thread":34,"level":"INFO","class":"oracle.kubernetes.operator.helpers.AuthenticationProxy","method":"check","timeInMillis":1527053926974,"message":"Returned TokenReview","exception":"","code":"","headers":{},"body":""}`

Could you help check this problem? 

Thanks.

**Comment by jhzhu89** [comment]
Hi,

I figured out why I got a 403.

Since my admin-server is running in the namespace weblogic-domain2, and the operator is running in the namespace weblogic-operator. I should have generated the access_token using the service account weblogic-operator's secret, not the service account default in weblogic-domain2.

I have another question about the policy and script action. After we create and active it, the script will be called by WLDF on the admin server, right?

Thanks.
Jiahao

**Comment by alai8** [comment]
Could you verify that the diagnostic system module is targeted to the admin server?

Quote from [Automatic Scaling of WebLogic Clusters on Kubernetes blog](https://blogs.oracle.com/weblogicserver/automatic-scaling-of-weblogic-clusters-on-kubernetes-v2):
The diagnostic system module is targeted to the Administration Server, specified as as_name, which is passed in as a system argument.  This diagnostic system module was targeted to the Administration Server because its policy contains the ClusterGenericMetricRule smart rule, which must be executed from the Administration Server so that it can have visibility across the entire cluster. For more information about smart rules and their targets, see Smart Rule Reference.

**Comment by jhzhu89** [comment]
@alai8 ,

Thanks for the help, I made it by deploying the policy only on admin server.

While I still cannot make the policy work. 
I created the start rule policy thru admin console, filled in the required params the same as posted in that blog, then attached a script action to it. The admin-server log showed that the module was successfully deployed and activated.  Then I curl-ed several times to  /opensessionapp, the cluster was not scaled up. 
Seems that the rules was not evaluated to true. 
How can I debug this issue?

I also created a calender based  policy and attached the script action, it worked properly. So I think, basically, the script action is correct, the only problem is  my smart rule. Could you help check if it is right? Here it is:
```
wls:ClusterGenericMetricRule("cluster-1","com.bea:Type=WebAppComponentRuntime,  ApplicationRuntime=OpenSessionApp,*","OpenSessionsCurrentCount",">=",0.01,2,"2 seconds","10 seconds")
```

Really appreciate your help :)

**Comment by alai8** [comment]
The smart rule looks ok.

Can you check the target servers for the diagnostic module, as shown in the screen shot of admin console:
![screen shot 2018-05-24 at 11 40 51 am](https://user-images.githubusercontent.com/22646587/40505878-7de606a2-5f4a-11e8-8e9c-1d454d7ad64a.png)

It should have checkbox for "admin-server" box checked, and leave the checkbox for "cluster-1" unchecked.

If this still does not work, could you please upload the config.xml and the diagnostic module xml file under config/diagnostics/ and we will help debug it further.

**Comment by alai8** [comment]
You can also add "-Dweblogic.debug.DebugDiagnosticWatch=true -Dweblogic.debug.DebugDiagnosticsExpressionPoller=true" to the value for the JAVA_OPTIONS env
in serverStartup section for the admin-server in domain-custom-resource.yaml. 

  serverStartup:
  # desiredState legal values are "RUNNING" or "ADMIN"
  # "RUNNING" means the listed server will be started up to "RUNNING" mode
  # "ADMIN" means the listed server will be start up to "ADMIN" mode
  - desiredState: "RUNNING"
    # the name of the server to apply these rules to
    serverName: "admin-server"
    # The Admin Server's NodePort
    nodePort: 30701
    # an (optional) list of environment variable to be set on the server
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false -Dweblogic.debug.DebugDiagnosticWatch=true -Dweblogic.debug.DebugDiagnosticsExpressionPoller=true"

That would generate debug information related to the WLDF policy in the admin-server.log file which may help us find the cause of the issue. Thanks.

**Comment by jhzhu89** [comment]
Hi @alai8 ，

For the targets, I only checked the admin-server. 
Here is the config file:
[Module-0-3905.tar.gz](https://github.com/oracle/weblogic-kubernetes-operator/files/2037890/Module-0-3905.tar.gz)

I'll try adding these options.

Thanks!

**Comment by alai8** [comment]
Thanks for uploading the WLDF module config file. Could you try removing the spaces before "ApplicationRuntime=OpenSessionApp,*" in the rule-expression and see if that helps?

**Comment by jhzhu89** [comment]
Hi @alai8 ,

I've added the JAVA options as you suggested, and removed the white spaces, from the log, I saw that this policy was successfully deployed. While I curled many times to the opensessionapp, the policy is always evaluated to false. Could you tell me how to trigger the policy? 
Here is the admin-server log:
[admin-server.log.tar.gz](https://github.com/oracle/weblogic-kubernetes-operator/files/2043875/admin-server.log.tar.gz)

Thanks

**Comment by jhzhu89** [comment]
Hi @alai8 ,

I got the opensessionapp.war from this repo: https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/wls-K8s/wls-12213-domain

I tried this morning, and I've reviewed my config.xml, it is same as yours except some params for scalingAction.sh. Here is all the data about the domain:
[domain2.tar.gz](https://github.com/oracle/weblogic-kubernetes-operator/files/2052564/domain2.tar.gz)
It contains copies of the original opensessionapp I got from that repo. Hope you can help find the route cause with them, thanks!

**Comment by alai8** [comment]
I noticed that the application name in your WLDF rule expression is different from the application name. The case should match too.

Your rule is
      \<rule-expression>wls:ClusterGenericMetricRule("cluster-1","com.bea:Type=WebAppComponentRuntime,ApplicationRuntime=**OpenSessionApp**,*","OpenSessionsCurrentCount","&gt;=",0.01,5,"1 seconds","10 seconds")\</rule-expression>

but your application is
  \<app-deployment>
    \<name>**opensessionapp**\</name>

Could you try making them the same and see if it helps?

**Comment by jhzhu89** [comment]
@alai8 ,

Thank you very much, it works :) 
Really appreciate your help!

Jiahao
