### ISSUE TITLE
JCE Unlimited Strength Jurisdiction Policy Files

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#30]
We received the following request in a comment on a separate issue:

@RisingPhorce 
> Similarly, what about Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files?
> Our standard Weblogic install uses the policy files. I can open a separate issue if needed.
> http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

We'll have to do some research...  I assume we can't distribute these policy files because I think there are import restrictions in certain countries.

**Comment by tbarnes-us** [comment]
Assigning to Ryan for triage. This is an old request that I suspect isn't tracked anywhere else.
