### ISSUE TITLE
Slow response: throughput lower and pod's CPU and memory not utlized

### ISSUE THREAD

**Issue by rsureshbe81** [oracle/weblogic-kubernetes-operator#3026]
Hi,
we recently migrated our application to AKS (Azure kuberntes service) weblogic from VM(IAAS). Below are Cluster specification.  We did load testing and performance is not met existing benchmark, found that  slow response time and throughput is very low compare to weblogic running on VM, main concern is POD CPU and memory are under utilized less than 10% usage but application is very low. Please advise. I raised a ticket with oracle support team, I didn't get any proper response. Please advise. And Is file type is NFS or SMB recommended? We followed all instruction for setup from oracle weblogic site-->https://oracle.github.io/weblogic-kubernetes-operator/userguide/ Please advise

Standard_E8s_v3
Node 2:
Node OS:  Ubuntu
RAM:  64 GB each so total 128GB
File Storage:  Azure File Share, Premium 1 TB
File Type: SMB
WL Version: 12.2.1.4
Total Pod: 4  (4 managed servers)

tag: weblogic:12.2.1.4

Image from 
https://container-registry.oracle.com/ords/f?p=113:4:111464275935351:::RP,4:P4_REPOSITORY,AI_REPOSITORY,P4_REPOSITORY_NAME,AI_REPOSITORY_NAME:5,5,Oracle%20WebLogic%20Server,Oracle%20WebLogic%20Server&cs=3_e8Z5ySSu0DGr_3gxntv5lLSRI0MujTaYGZEkY-57QeAVo5q5OwJLGiiPitqaS0_bZob7EV65IUKkq2CWI0IkQ
 limits:
        cpu: 2000m
        memory: 8Gi
  requests:
        cpu: 400m
        memory: 2Gi
    volumeMounts:

**Comment by sankarpn** [comment]
Hi @rsureshbe81, can you please post your domain configuration details and try tuning the JVM parameters as mentioned in this FAQ? https://oracle.github.io/weblogic-kubernetes-operator/faq/resource-settings/
If you have done any performance profiling with tools such as JFR can you post those logs as well?

Also please post your questions to our "operator" support channel available at https://oracle-weblogic.slack.com/
for a faster response and more help.

**Comment by edburns** [comment]
[MS internal tracking reference](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1535185)

**Comment by mriccell** [comment]
We observed a similar problem during the testing of this offering and documented a solution.  Please take a look at the domain on pv guide: https://oracle.github.io/weblogic-kubernetes-operator/samples/azure-kubernetes-service/domain-on-pv/, search for “limit”.
Let us know if this solves your problem.

Thanks
Monica

**Comment by rsureshbe81** [comment]
We tried all option still not works. Can you please share Oracle Id, I will send meeting invite from company email. we can discuss. I can't share logs file and jfr in this forum.

**Comment by mriccell** [comment]
Can you first send an email to monica.riccelli@oracle.com, I would like for our Microsoft counterpart to be invited as well as other team participants.
Thanks

**Comment by rsureshbe81** [comment]
Thanks Monica. I emailed all the details to your oracle email. We definitely need your core team assistance. Please reply to my office email, I will schedule a meeting.
