### ISSUE TITLE
Weblogic operator fails to perform rolling restart of managed servers.

### ISSUE THREAD

**Issue by Surabhi0709** [oracle/weblogic-kubernetes-operator#3102]
We are currently using weblogic-kubernetes-operator version :3.3.8
Our application is deployed to a  WLS cluster
Problem:
So the whenever a new auxiliary image with the new application binary is deployed the expected behavior is that the WebLogic Kubernetes Operator will do a rolling restart of the individual managed servers to pick up the new version of the application.
However in our case we have observed that the operator is not performing a rolling bounce and the number of active pods drops below 2 causing a potential outage of service for 5-10 mins depending on the number of pods.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/106271544/170330961-774929f3-2cca-4fae-ba5d-4065d0ffb027.png">

Question:
Is there any implementation technique or configuration fields that we can spread out the time period taken by weblogic operator to perform rolling restart of the pods .

**Comment by doxiao** [comment]
@Surabhi0709 just a follow up to our discussions in the slack last week about this issue. Do you still see this issue now?

**Comment by tbarnes-us** [comment]
There's been no response for months. I'm assuming that this issue has been resolved.
