### ISSUE TITLE
Would like to be able to specify the UID for the container in helm chart v3.4.0

### ISSUE THREAD

**Issue by naveensgowda** [oracle/weblogic-kubernetes-operator#3122]
Would like to be able to specify the UID for the container. We are using older version of Weblogic Operator (3.0.0) and now we are planning to use the latest one. We have **USER 1000** specified in the docker image in v3.0.0, whereas with latest images numeric user is not specifed and we have **USER oracle** in the docker image (in v3.4.0, v3.3.0).

We are using our own container management orchestration system and it has more restrictive policy. Since numeric user is not provided deploying Weblogic Operator fails with below error,
Error: container has runAsNonRoot and image has non-numeric user (oracle), cannot verify user is non-root

In order to over come this we have either specify USER 1000 in docker image or include below in the deployment yaml spec (_operator-dep.tpl),
  securityContext:
    runAsUser: 1000
	
It would be nice have an option where we can do this in the official helm chart (weblogic-operator-3.4.0) itself. If not good to have always it could be configurable based one some flag (like we provide cpuLimits, memoryLimits currently).

![WO](https://user-images.githubusercontent.com/105410975/171358852-1e85d7d6-bbbc-4c96-80b0-632c1a006a30.jpg)

**Comment by ankedia** [comment]
Hi @naveensgowda , I have created an Oracle internal JIRA OWLS-99772 to track this issue/requirement. We'll let you know once this option is added to the operator's helm chart.
