### ISSUE TITLE
Create domain script does not check that a NodePort defined in the input files is already in use

### ISSUE THREAD

**Issue by mriccell** [oracle/weblogic-kubernetes-operator#316]
This is a usability issue noted by Antonio from CERN.  Create domain script does not check that a NodePort defined in the input files is already in use.
      - It means that the script will fail just at the Kubernetes services creation time.
       - It means that also the directory on the shared volume is already created. Probably it would be good to validate NodePort and catch the conflict before.

**Comment by tbarnes-us** [comment]
This looks quite old. Feel free to re-open if/when needed.
