### ISSUE TITLE
Issue deploying OIG on AKS

### ISSUE THREAD

**Issue by gwbatte** [oracle/weblogic-kubernetes-operator#3161]
**SOURCE:** [](https://docs.oracle.com/en/middleware/fusion-middleware/12.2.1.4/ikedg/installing-and-configuring-oracle-identity-governance.html#GUID-14196492-4391-4547-B395-5E2AE19A93B3
)

**ISSUE**
Setting up on AKS using Azure Storage Account / Fileshare "NFS" receive the following error

MountVolume.SetUp failed for volume "rcu-credentials-volume" : object "oigns"/"oig-rcu-credentials" not registered
MountVolume.SetUp failed for volume "create-fmw-infra-sample-domain-job-cm-volume" : object "oigns"/"governancedomain-create-fmw-infra-sample-domain-job-cm" not registered
MountVolume.SetUp failed for volume "fmw-infra-credentials-volume" : object "oigns"/"oig-domain-credentials" not registered

Files are being created on NFS Fileshare.

![image](https://user-images.githubusercontent.com/67064136/173249934-b6361722-ce30-4aa4-acd1-17127bece028.png)

![image](https://user-images.githubusercontent.com/67064136/173249971-627bf27e-eae0-4e0c-8440-8a599b8671eb.png)

**Input parameters being used**
export version="create-weblogic-sample-domain-inputs-v1"
export adminPort="7001"
export adminServerName="AdminServer"
export domainUID="governancedomain"
export domainHome="/u01/oracle/user_projects/domains/governancedomain"
export serverStartPolicy="IF_NEEDED"
export clusterName="oim_cluster"
export configuredManagedServerCount="2"
export initialManagedServerReplicas="2"
export managedServerNameBase="oim_server"
export managedServerPort="14000"
export image="<redacted>/oig:12.2.1.4-jdk8-ol7-220420.0828"  
export imagePullPolicy="Always"
export imagePullSecretName="orclcred"
export productionModeEnabled="true"
export weblogicCredentialsSecretName="oig-domain-credentials"
export includeServerOutInPodLog="true"
export logHome="/u01/oracle/user_projects/domains/logs/oimcluster"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="true"
export namespace="oigns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="governancedomain-domain-pvc"
export domainPVMountPath="/u01/oracle/user_projects"
export createDomainScriptsMountPath="/u01/weblogic"
export createDomainScriptName="create-domain-job.sh"
export createDomainFilesDir="wlst"
export rcuSchemaPrefix="IGDEDG"
export rcuDatabaseURL="<redacted>:1521/orclpdb1"
export rcuCredentialsSecret="oig-rcu-credentials"
export frontEndHost="<redacted>"
export frontEndPort="443"

**Comment by gwbatte** [comment]
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    44m                default-scheduler  Successfully assigned oigns/governancedomain-create-fmw-infra-sample-domain-job-b5sxp to aks-<>-19717952-vmss00000m
  Normal   Pulling      44m                kubelet            Pulling image "<>.azurecr.io/oig:12.2.1.4-jdk8-ol7-220420.0828"
  Normal   Pulled       44m                kubelet            Successfully pulled image "<>.azurecr.io/oig:12.2.1.4-jdk8-ol7-220420.0828" in 662.110444ms
  Normal   Created      44m                kubelet            Created container create-fmw-infra-sample-domain-job
  Normal   Started      44m                kubelet            Started container create-fmw-infra-sample-domain-job
  Warning  FailedMount  38m (x2 over 38m)  kubelet            MountVolume.SetUp failed for volume "rcu-credentials-volume" : object "oigns"/"oig-rcu-credentials" not registered
  Warning  FailedMount  38m (x2 over 38m)  kubelet            MountVolume.SetUp failed for volume "create-fmw-infra-sample-domain-job-cm-volume" : object "oigns"/"governancedomain-create-fmw-infra-sample-domain-job-cm" not registered
  Warning  FailedMount  38m (x2 over 38m)  kubelet            MountVolume.SetUp failed for volume "fmw-infra-credentials-volume" : object "oigns"/"oig-domain-credentials" not registered

**Comment by galiacheng** [comment]
Hello @gwbatte which AKS version are you using?

**Comment by lay-le** [comment]
This seems to be Kubernetes bug on CronJob (version 1.22, 1.23), it was fixed in 1.23.6. Please take a look at https://github.com/kubernetes/kubernetes/issues/105204 for more info.

**Comment by tbarnes-us** [comment]
There's been no response for months, so I'm assuming this Issue was resolved.
