### ISSUE TITLE
Thoughts on supporting dynamic persistent volumes

### ISSUE THREAD

**Issue by bryantidd** [oracle/weblogic-kubernetes-operator#32]
I have made edits to the input and template yaml files and the create shell scripts to support my own custom provisioner and storage class (AWS EFS based).

I added the following values to the inputs:
`#`expecting dynamic or static
persistenceVolumeType: dynamic
`#`expecting size - for dynamic 1Mi is sufficient 
persistenceVolumeSize: 1Mi 

I added the following to shell scripts:
`#` To check for value and set sane default if unavailable
`function validateVolumeType {
  if [ -z $persistenceVolumeType ]; then
    persistenceVolumeType=static
    echo "Defaulting the input parameter persistenceVolumeType to be static"
  fi
}`
`function validateVolumeSize {
  if [ -z $persistenceSize ]; then
    persistenceSize=1Mi
    echo "Defaulting the input parameter persistenceSize to be 1Mi"
  fi
}
`

`#` To check for Bound status of PVC 
`function checkPvcState {

    echo "Checking if the persistent volume claim ${1:?} is ${2:?} in namespace ${namespace}"
    pvc_state=`kubectl -n ${namespace}  get pvc $1 -o jsonpath='{$..status.phase}'`
    attempts=0
    while [ ! "$pvc_state" = "$2" ] && [ ! $attempts -eq 10 ]; do
        attempts=$((attempts + 1))
        sleep 1
        pvc_state=`kubectl -n ${namespace}  get pvc $1 -o jsonpath='{$..status.phase}'`
    done
    if [ "$pvc_state" != "$2" ]; then
        fail "The persistent volume claim state should be $2 but is $pvc_state"
    fi
}`

I also added if statements around pc related sections of the shell scripts to skip them based on the value of persistenceVolumeType. As in the following excerpt:
`  if [ "${persistenceVolumeType}" = "static" ]; then
    pvInput="${scriptDir}/internal/persistent-volume-template.yaml"
    pvOutput="${scriptDir}/persistent-volume.yaml"
    if [ ! -f ${pvInput} ]; then
      validationError "The template file ${pvInput} for generating a persistent volume was not found"
    fi
  fi`
from the function initialize.
I hope this helps. I like not having to worry about creating the persistent volumes. 

It may also be helpful to add a few while loops (as much as I hate them) to check for creation of resources, similar to the checkPvcState function, with the attempts limit adjustable, etc.

**Comment by LorenKonkus** [comment]
Thanks for the suggestion - we'll investigate adding this.

**Comment by bryantidd** [comment]
I am successfully using the NFS options available in the develop branch as of June 12th with Amazon AWS EFS based persistent storage for a Kubernetes cluster deployed in Amazon AWS. 

I would like to suggest an option to provide persistent storage by either using the provided methods in the input and bash scripts, or by providing an input for substitute pvc & pv template files in the input yaml

Being that the CNCF has taken up Rook as a storage solution. Would you all consider it for persistent storage management? It would allow for attracting away other details for cloud and on-premise storage.

**Comment by moreaut** [comment]
Hi Bryan,

The most current version of the operator (2.0, i.e. the master branch) lets you create your own kubernetes volumes by hand and tell the operator to mount them into the server pods.

Does this address your issue?

Thanks, -Tom

**Comment by tbarnes-us** [comment]
Assigning this issue to Ryan for triage.  My assumption is that we can close it, but I'm not 100% sure.

**Comment by rjeberhard** [comment]
I believe we have this. Bryan, obviously please let us know if you still need something here.
