### ISSUE TITLE
Operator not able to start Admin server - nodemanager start file not found

### ISSUE THREAD

**Issue by karan-kapoor90** [oracle/weblogic-kubernetes-operator#320]
I've managed to setup the operator and have setup a weblogic domain called dev-domain as:
```
$ kubectl get domains -n dev-domain
NAME         AGE
dev-domain   31m
```

The admin server pod is not able to start up:
```
$ kubectl get pods -n dev-domain
NAME                                             READY     STATUS             RESTARTS   AGE
dev-domain-admin-server                          0/1       CrashLoopBackOff   9          21m
dev-domain-dev-cluster-traefik-8c8fc74f9-ffct5   1/1       Running            0          32m
```

The error in the pod's description is:
```
Error: failed to start container "weblogic-server": Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/shared/domain/dev-domain/servers/admin-server/nodemgr_home/startServer.sh\": stat /shared/domain/dev-domain/servers/admin-server/nodemgr_home/startServer.sh: no such file or directory": unknown
```
The location up to /admin-server is present in the shared location that is mentioned in the error, but the `nodemgr_home/startServer.sh` file really does not exist in the location. Seems like some kind of an issue with the way the weblogic image is getting built.

**Comment by alai8** [comment]
Is it possible that your weblogic operator image is older than the create-weblogic-domain.sh script that was used to create the weblogic domain?

**Comment by karan-kapoor90** [comment]
Possible.. I'll check that. Could you point me to the best (most up to date) resource for building a weblogic docker image?

**Comment by karan-kapoor90** [comment]
I pulled a fresh weblogic image from the docker store instead of building one. Could the problem still exist?

**Comment by karan-kapoor90** [comment]
So I created a new container using the store/oracle/weblogic:12.2.1.3 image using the command:
```
docker run --name weblogic -p 7001:7001 -it store/oracle/weblogic:12.2.1.3
```

And then I looked inside the container to see if there was a startServer.sh script in there, but there's nothing that looks like that in there..
```
$ pwd
/u01/oracle/user_projects/domains/base_domain/servers/AdminServer
[oracle@9a49deb291b5 AdminServer]$ ll
total 0
drwxr-x--- 3 oracle oracle 25 Jun  1 06:20 cache
drwxr-x--- 5 oracle oracle 46 Jun  1 06:21 data
drwxr-x--- 3 oracle oracle 95 Jun  1 06:20 logs
drwxr-xr-x 2 oracle oracle 29 Jun  1 06:20 security
drwxr-x--- 4 oracle oracle 66 Jun  1 06:20 tmp
```

Is there a problem with the way the image is being built?

**Comment by alai8** [comment]
We have moved the startServer.sh script from .../nodemgr_home/startServer.sh to a config map recently. Since there is no nodemgr_home in your dev-domain I am assuming that it is built using a recently pull. However, since the weblogic operator in your environment is still creating pods that use the startServer.sh script from .../nodemgr_home/ I suspect that your weblogic operator image hasn't been built recently. Could you please try rebuilding the docker image for the weblogic operator (not weblogic server)? 

The admin server pod created by the operator should have the following:

    Command:
      /weblogic-operator/scripts/startServer.sh

**Comment by karan-kapoor90** [comment]
Ok. I'll rebuild the operator and report back what I find.

**Comment by rjeberhard** [comment]
Karan,

The image won't have the start script because the script comes from a ConfigMap that is mounted in the Pod's file system.

> So I created a new container using the store/oracle/weblogic:12.2.1.3 image using the command:
>
> docker run --name weblogic -p 7001:7001 -it store/oracle/weblogic:12.2.1.3
>
> And then I looked inside the container to see if there was a startServer.sh script in there, but there's > nothing that looks like that in there..

> $ pwd
> /u01/oracle/user_projects/domains/base_domain/servers/AdminServer
[oracle@9a49deb291b5 AdminServer]$ ll
> total 0
> drwxr-x--- 3 oracle oracle 25 Jun  1 06:20 cache
> drwxr-x--- 5 oracle oracle 46 Jun  1 06:21 data
> drwxr-x--- 3 oracle oracle 95 Jun  1 06:20 logs
> drwxr-xr-x 2 oracle oracle 29 Jun  1 06:20 security
> drwxr-x--- 4 oracle oracle 66 Jun  1 06:20 tmp

**Comment by karan-kapoor90** [comment]
Rebuilding the operator worked. Thank you @rjeberhard
