### ISSUE TITLE
Feature Request: add the possibility to configure resources for a sidecar container

### ISSUE THREAD

**Issue by arnabold** [oracle/weblogic-kubernetes-operator#3303]
This feature request is about the configuration of "resources" (limits and request) for a specific container in a multi-container pod. The specific use case concerns the usage of the monitoring-exporter as a sidecar. Usually a monitoring-exporter container consumes less cpu than a weblogic-server container.

**Comment by alai8** [comment]
Thanks. I've filed internal Oracle JIRA OWLS-101705 to track the issue.

**Comment by russgold** [comment]
This is now in main
