### ISSUE TITLE
WebLogic Admin Console doesn't allow login via Voyager LoadBalancer  

### ISSUE THREAD

**Issue by bryantidd** [oracle/weblogic-kubernetes-operator#333]
I have deployed a WebLogic domain with the develop codebase for the operator and Voyager as LoadBalancer. The cluster becomes available. I add the admin-server service as a backend to a host in the voyager ingress. I can access the "console/login/LoginForm.jsp" page, but the credentials that I provided in the secret mounted and used in domain creation do not allow access.

Any hints or trouble shooting ideas? I am seeing a 302 for the login form, then a 307 for the javascript that collects the username and password.

**Comment by alai8** [comment]
Hi, could you give us more details on what you did to "add the admin-server service as a backend to a host in the voyager ingress"? Thanks!

**Comment by moreaut** [comment]
Hi Bryan,

Could you try again using the latest (2.0) version of the weblogic operator (the master branch)?

Thanks, -Tom

**Comment by alai8** [comment]
Please re-open if you are still seeing this issue with version 2.0 of the WebLogic operator. Thanks.
