### ISSUE TITLE
Issues within kubernetes/internal/generate-security-policy.sh

### ISSUE THREAD

**Issue by gstrzalka** [oracle/weblogic-kubernetes-operator#34]
While installing operator (./create-weblogic-operator.sh -i create-operator-inputs.yaml) got following issues:
1. *if* test in line 47:

> /home/ubuntu/wls-operator/git/weblogic-kubernetes-operator/kubernetes/internal/generate-security-policy.sh: 47: [: -o: unexpected operator

looks like wrong comparison operator is used:
`if [ "$1" == "-o" ] ; then`
following seems to be more correct:
`if [ "$1" = "-o" ] ; then`

2. I found no mention of shell version to be used with scripts, on my ubuntu 16.04 I have dash version 0.5.8-2.1ubuntu2 configured as */bin/sh*, seems like it has problems with line 191 substitution operation in _kubernetes/internal/generate-security-policy.sh_, current version:

`for i in ${TARGET_NAMESPACES//,/ }`
maybe worth to use more secure one, e.g.:
`for i in $(echo $TARGET_NAMESPACES | sed "s/,/ /g")`

**Comment by markxnelson** [comment]
@gstrzalka can you confirm the fix is working for you? can we close this now? thanks

**Comment by gstrzalka** [comment]
Is ok, closing this one
