### ISSUE TITLE
weblogic-kubernetes-operator started managed servers with coherence enabled do not form a cluster.

### ISSUE THREAD

**Issue by chpatel3** [oracle/weblogic-kubernetes-operator#341]
When weblogic kubernetes operator starts managed servers, it creates kubernetes service object with service type=ClusterIP that causes the incorrect WKA list as shown below causes multiple coherence enabled managed servers(CacheTier) NOT to form a cluster.

WellKnownAddressList(
10.106.99.26
10.244.1.3
)

MasterMemberSet(
ThisMember=Member(Id=1, Timestamp=2018-06-19 18:22:54.308, Address=10.244.1.3:58536, MachineId=30238, Location=machine:wdtdomain-managed-server1,process:5
00,member:managed-server1, Role=CacheTier)
OldestMember=Member(Id=1, Timestamp=2018-06-19 18:22:54.308, Address=10.244.1.3:58536, MachineId=30238, Location=machine:wdtdomain-managed-server1,process
:500,member:managed-server1, Role=CacheTier)
ActualMemberSet=MemberSet(Size=1
Member(Id=1, Timestamp=2018-06-19 18:22:54.308, Address=10.244.1.3:58536, MachineId=30238, Location=machine:wdtdomain-managed-server1,process:500,member
:managed-server1, Role=CacheTier)
)
MemberId|ServiceJoined|MemberState|Version
1|2018-06-19 18:22:54.308|JOINED|12.2.1.3.0
RecycleMillis=1200000
RecycleSet=MemberSet(Size=0
)
)

Here, 10.244.1.3 is the Pod IP of the managed-server1, while 10.106.99.26 is the service IP of managed-server2 rather than actual pod IP of managed-server2, causing the mananged-server1 and managed-server2 not to form a cluster.

Not sure weblogic-kubernetes-operator provides the way to create headless service object for managed server as for coherence cluster to be well formed on kubernetes, Headless Service object needs to be created.

Plese see below kubernetes doc for headless service.
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

As per the above kubernetes doc, headless-service can be used when no load-balancing is required among the pod instances with selectors. I can only see single instance of each managed server running on kubernetes. And do not expect operator will be running multiple pods of a single managed-server(e.g managed-server1), so I do think a service object with type=ClusterIP needed for a managed server running on kubernetes.

So weblogic-kubernetes-operator must provide a way or an option for managed server to be created with headless service or create headless service by default for each managed server instance so that servers involving in caching tier can form the cluster when running on kubernetes.

**Comment by rjeberhard** [comment]
@chpatel3 Please test against the issue-341 branch.  Note: you cannot specify clusterIP="None" for type="NodePort" services.  Therefore, admin servers typically wouldn't be able to join Coherence clusters.  I'm assuming this is okay.

**Comment by chpatel3** [comment]
Thanks Ryan! 
Yes, admin server is fine with NodePort as it exposing the port to access the console.
I will test with branch issue-341 and update here with the result.

**Comment by chpatel3** [comment]
@rjeberhard Just tested with issue-341 branch and verified managed server instances are created with headless service.

service/wdtdomain-managed-server1                     ClusterIP   None             <none>        8001/TCP          1h        weblogic.createdByOperator=true
,weblogic.domainUID=wdtdomain,weblogic.serverName=managed-server1
service/wdtdomain-managed-server2                     ClusterIP   None             <none>        8002/TCP          1h        weblogic.createdByOperator=true
,weblogic.domainUID=wdtdomain,weblogic.serverName=managed-server2

And with that, I see correct WKA list is generated in managed server logs and coherence clustering works among managed server instances.

WellKnownAddressList(
  10.244.1.57
  10.244.2.162
  )

MasterMemberSet(
  ThisMember=Member(Id=2, Timestamp=2018-06-26 14:46:34.725, Address=10.244.1.57:56809, MachineId=30239, Location=machine:wdtdomain-managed-server2,process:1564,member:managed-server2, Role=CacheTier)
  OldestMember=Member(Id=1, Timestamp=2018-06-26 14:44:33.63, Address=10.244.2.162:45179, MachineId=30238, Location=machine:wdtdomain-managed-server1,process:454,member:managed-server1, Role=CacheTier)
  ActualMemberSet=MemberSet(Size=2
    Member(Id=1, Timestamp=2018-06-26 14:44:33.63, Address=10.244.2.162:45179, MachineId=30238, Location=machine:wdtdomain-managed-server1,process:454,member:managed-server1, Role=CacheTier)
    Member(Id=2, Timestamp=2018-06-26 14:46:34.725, Address=10.244.1.57:56809, MachineId=30239, Location=machine:wdtdomain-managed-server2,process:1564,member:managed-server2, Role=CacheTier)
    )
  MemberId|ServiceJoined|MemberState|Version
    1|2018-06-26 14:44:33.63|JOINED|12.2.1.3.0,
    2|2018-06-26 14:46:34.725|JOINED|12.2.1.3.0
  RecycleMillis=1200000
  RecycleSet=MemberSet(Size=0
    )
  )

TcpRing{Connections=[1]}
IpMonitor{Addresses=1, Timeout=15s}
>
