### ISSUE TITLE
Error with create-weblogic-domain.sh: error: unable to recognize "/vagrant/weblogic-domains/domain1/domain-custom-resource.yaml": no matches for weblogic.oracle/, Kind=Domain

### ISSUE THREAD

**Issue by shaunxa** [oracle/weblogic-kubernetes-operator#344]
[vagrant@master kubernetes]$ ./create-weblogic-domain.sh -i create-weblogic-domain-inputs.yaml -o /vagrant
Input parameters being used
export version="create-weblogic-domain-inputs-v1"
export adminPort="7001"
export adminServerName="admin-server"
export domainName="base_domain"
export domainUID="domain1"
export clusterType="DYNAMIC"
export startupControl="AUTO"
export clusterName="cluster-1"
export configuredManagedServerCount="2"
export initialManagedServerReplicas="2"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export weblogicDomainStorageType="HOST_PATH"
export weblogicDomainStoragePath="/vagrant/domain1"
export weblogicDomainStorageReclaimPolicy="Retain"
export weblogicDomainStorageSize="10Gi"
export productionModeEnabled="true"
export weblogicCredentialsSecretName="domain1-weblogic-credentials"
export t3ChannelPort="30012"
export t3PublicAddress="kubernetes"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="default"
export loadBalancer="TRAEFIK"
export loadBalancerAppPrepath="/"
export loadBalancerWebPort="30305"
export loadBalancerDashboardPort="30315"
export javaOptions="-Dweblogic.StdoutDebugEnabled=false"

Generating /vagrant/weblogic-domains/domain1/weblogic-domain-pv.yaml
Generating /vagrant/weblogic-domains/domain1/weblogic-domain-pvc.yaml
Generating /vagrant/weblogic-domains/domain1/create-weblogic-domain-job.yaml
Generating /vagrant/weblogic-domains/domain1/domain-custom-resource.yaml
sed: cannot rename /vagrant/weblogic-domains/domain1/sedP5UQWX: Operation not permitted
Generating /vagrant/weblogic-domains/domain1/weblogic-domain-traefik-cluster-1.yaml
Generating /vagrant/weblogic-domains/domain1/weblogic-domain-traefik-security-cluster-1.yaml
Checking to see if the secret domain1-weblogic-credentials exists in namespace default
Checking if the persistent volume domain1-weblogic-domain-pv exists
The persistent volume domain1-weblogic-domain-pv already exists
Checking if the persistent volume claim domain1-weblogic-domain-pvc in namespace default exists
The persistent volume claim domain1-weblogic-domain-pvc already exists in namespace default
Checking if object type job with name domain1-create-weblogic-domain-job exists
Deleting domain1-create-weblogic-domain-job using /vagrant/weblogic-domains/domain1/create-weblogic-domain-job.yaml
configmap "domain1-create-weblogic-domain-job-cm" deleted
job "domain1-create-weblogic-domain-job" deleted
Creating the domain by creating the job /vagrant/weblogic-domains/domain1/create-weblogic-domain-job.yaml
configmap "domain1-create-weblogic-domain-job-cm" created
job "domain1-create-weblogic-domain-job" created
Waiting for the job to complete...
status on iteration 1 of 20
pod domain1-create-weblogic-domain-job-lhftq status is Running
status on iteration 2 of 20
pod domain1-create-weblogic-domain-job-lhftq status is Running
status on iteration 3 of 20
pod domain1-create-weblogic-domain-job-lhftq status is Completed
Setting up traefik security
clusterrole "domain1-cluster-1-traefik" created
clusterrolebinding "domain1-cluster-1-traefik" created
Checking the cluster role domain1-cluster-1-traefik was created
Checking the cluster role binding domain1-cluster-1-traefik was created
Deploying traefik
serviceaccount "domain1-cluster-1-traefik" created
deployment "domain1-cluster-1-traefik" created
configmap "domain1-cluster-1-traefik-cm" created
service "domain1-cluster-1-traefik" created
service "domain1-cluster-1-traefik-dashboard" created
Checking traefik deployment
Checking the traefik service account
Checking traefik service
Creating the domain custom resource using /vagrant/weblogic-domains/domain1/domain-custom-resource.yaml
error: unable to recognize "/vagrant/weblogic-domains/domain1/domain-custom-resource.yaml": no matches for weblogic.oracle/, Kind=Domain
Checking the domain custom resource was created
the server doesn't have a resource type "domain"
[ERROR] The domain custom resource domain1 was not found
[vagrant@master kubernetes]$

**Comment by shaunxa** [comment]
It is not available in api-versions
==================================
[vagrant@master weblogic-kubernetes-operator]$ kubectl api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
[vagrant@master weblogic-kubernetes-operator]$

**Comment by rjeberhard** [comment]
Hi @shaunxa, 

The CRD that defines the custom resource is created when the operator starts.  Do you have the operator running?  You need to do this before running the create domain script.

**Comment by shaunxa** [comment]
@rjeberhard, thank you for your advise. I will check and update the outcome. Thanks.

**Comment by moreaut** [comment]
Hi @shaunxa,

Did Ryan's advice solve your issue?  If not, could you try the most current version of the operator (2.0, i.e. the master branch).

Thanks, -Tom

**Comment by shaunxa** [comment]
Tom, thank your for your follow up.

I changed the environment and I am using the latest operator 2.0. I have no such issue now. I close it now. Thanks.

Cheers,
Shaun

**Comment by moreaut** [comment]
Thanks!
