### ISSUE TITLE
Managed Server pods not starting

### ISSUE THREAD

**Issue by karan-kapoor90** [oracle/weblogic-kubernetes-operator#345]
The admin server pod is up and running however no Managed server pods are created. I'm running on OCI on 3 instances - not provisioned using the terraform scripts but created directly from the OCI UI. 
The operator is running and the custom domain resource also says the following:

```
Name:         dev-domain
Namespace:    dev-domain
Labels:       weblogic.domainName=dev-domain
              weblogic.domainUID=dev-domain
              weblogic.resourceVersion=domain-v1
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"weblogic.oracle/v1","kind":"Domain","metadata":{"annotations":{},"labels":{"weblogic.domainName":"dev-domain","weblogic.domainUID":"dev-...
API Version:  weblogic.oracle/v1
Kind:         Domain
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-07-07T15:48:09Z
  Generation:          0
  Resource Version:    27951
  Self Link:           /apis/weblogic.oracle/v1/namespaces/dev-domain/domains/dev-domain
  UID:                 25ed332e-81fd-11e8-90c5-020017013c05
Spec:
  Admin Secret:
    Name:   weblogic-credentials
  As Name:  admin-server
  As Port:  7001
  Cluster Startup:
    Cluster Name:   cluster-1
    Desired State:  RUNNING
    Env:
      Name:     JAVA_OPTIONS
      Value:    -Dweblogic.StdoutDebugEnabled=false
      Name:     USER_MEM_ARGS
      Value:    -Xms64m -Xmx256m
    Replicas:   2
  Domain Name:  dev-domain
  Domain UID:   dev-domain
  Export T 3 Channels:
    T3Channel
  Image:              store/oracle/weblogic:12.2.1.3
  Image Pull Policy:  IfNotPresent
  Replicas:           1
  Server Startup:
    Desired State:  RUNNING
    Env:
      Name:         JAVA_OPTIONS
      Value:        -Dweblogic.StdoutDebugEnabled=false
      Name:         USER_MEM_ARGS
      Value:        -Xms64m -Xmx256m
    Node Port:      30701
    Server Name:    admin-server
  Startup Control:  AUTO
Status:
  Conditions:
    Last Transition Time:  2018-07-07T15:54:06.083Z
    Reason:                ServersReady
    Status:                True
    Type:                  Available
  Servers:
    Server Name:  admin-server
    State:
  Start Time:     2018-07-07T15:54:06.083Z
Events:           <none>
```

The domain creation job had also completed successfully without any errors. Not able to figure out why the managed server pods are not getting created. The only odd thing seems to be the Connection Timeout for getting the Admin server health in the operator log even though the Admin Server is up and running, and the 403 Forbidden error in the operator logs associated with the error.

What could be happening?

**Comment by karan-kapoor90** [comment]
[operator.log](https://github.com/oracle/weblogic-kubernetes-operator/files/2172913/operator.log)

**Comment by karan-kapoor90** [comment]
I tried with creating both kinds of clusters, dynamic as well as Configured and both had the same issue with the same error in the operator logs.

**Comment by karan-kapoor90** [comment]
[fine-operator.log](https://github.com/oracle/weblogic-kubernetes-operator/files/2172965/fine-operator.log)

I increased the operators logging level to FINE. Not sure that the problem is though

**Comment by karan-kapoor90** [comment]
I looked after a while and the Managed servers had started and they were in a CrashLoopBackoff.. looking through the logs I found the following in the managed server logs:

```
A MultiException has 6 exceptions.  They are:
1. weblogic.security.SecurityInitializationException: Authentication denied: Boot identity not valid. The user name or password or both from the boot identity file (boot.properties) is not valid. The boot identity may have been changed since the boot identity file was created. Please edit and update the boot identity file with the proper values of username and password. The first time the updated boot identity file is used to start the server, these new values are encrypted.
2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.security.SecurityService
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.jndi.internal.RemoteNamingService errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.jndi.internal.RemoteNamingService
5. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.deployment.DeploymentRegistrationService errors were found
6. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.deployment.DeploymentRegistrationService
```

Shouldn't have happened because I didn't do anything custom! I did the standard steps to setup a weblogic cluster

**Comment by karan-kapoor90** [comment]
#326 is the same issue... Additionally in my case, it was roughly an hour before managed server creation seemed to start after the admin server was created.

**Comment by marinakog** [comment]
is it possible that the ${domainPVSPath} dir was not cleaned up before domain creation? do you use NFS ? you can try to delete and shutdown everything, and clean domainPVSPath, unmount and mount again dirs in the client nodes. (see https://blogs.oracle.com/weblogicserver/how-to-run-weblogic-clusters-on-the-oracle-cloud-infrastructure-container-engine-for-kubernetes )
ssh -i ${sshKeyPath} -o CheckHostIP=no opc@${masterPubIp}
sudo su -
echo "login as root to ${masterPubIp}"
rm -rf ${domainPVSPath}
mkdir -m 777 -p ${domainPVSPath}
sudo chown -R opc:opc ${domainPVSPath}
systemctl restart nfs

**Comment by moreaut** [comment]
Hi Karan,

Did Marina's suggestion fix your problem?

Can this issue be closed?

Thanks, -Tom

**Comment by alai8** [comment]
Please reopen issue if you are still seeing the problem with the latest version of the WebLogic operator (2.0)

**Comment by satyendrakarn** [comment]
I too am facing the same problem. In order to shutdown all the servers, I have set serverStartPolicy: "NEVER" for the domain and again to bring all the servers up I have set it to IF_NEEDED. On restart, only the admin server came up. I tried recreating the domain, still managed server didn't start.
I have also tried deleting the NFS mounts from all the nodes but no luck. Can you help?

**Comment by alai8** [comment]
Were the manage server pods created? If so could you upload the pod log? Otherwise, we would probably need to look at the operator log to see if it provides any clues. Thanks

**Comment by satyendrakarn** [comment]
Exposed node port was already in use by another service. Issue is resolved now. Thanks.
