### ISSUE TITLE
weblogic operator is not starting the domains (PODS)

### ISSUE THREAD

**Issue by send2jayanth** [oracle/weblogic-kubernetes-operator#3522]
Hello Team,

I am configuring weblogic on k8s using below link.

https://oracle.github.io/weblogic-kubernetes-operator/quickstart/

Domain has been created successfully  &   **kubectl get pods -n sample-domain1-ns** is not returning any pods. While checking ,  receiving below error in the operator logs.  Please guide me how to proceed further.

`{"timestamp":"2022-10-18T11:24:24.184910053Z","thread":13,"fiber":"fiber-276-child-1","namespace":"sample-domain1-ns","domainUID":"","level":"SEVERE","class":"oracle.kubernetes.operator.Main$NullCompletionCallback","method":"onThrowable","timeInMillis":1666092264184,"message":"Exception thrown","exception":"\njava.lang.NullPointerException: Cannot invoke \"io.kubernetes.client.openapi.models.V1beta1PodDisruptionBudgetList.getItems()\" because \"list\" is null\n\tat oracle.kubernetes.operator.DomainResourcesValidation.addPodDisruptionBudgetList(DomainResourcesValidation.java:115)\n\tat oracle.kubernetes.operator.DomainResourcesValidation$1.lambda$getPodDisruptionBudgetListProcessing$3(DomainResourcesValidation.java:62)\n\tat oracle.kubernetes.operator.NamespacedResources$ListResponseStep.lambda$onSuccess$0(NamespacedResources.java:241)\n\tat java.base/java.util.ArrayList.forEach(Unknown Source)\n\tat oracle.kubernetes.operator.NamespacedResources$ListResponseStep.onSuccess(NamespacedResources.java:241)\n\tat oracle.kubernetes.operator.steps.DefaultResponseStep.onFailure(DefaultResponseStep.java:32)\n\tat oracle.kubernetes.operator.helpers.ResponseStep.fromCallResponse(ResponseStep.java:90)\n\tat oracle.kubernetes.operator.helpers.ResponseStep.lambda$getActionForCallResponse$0(ResponseStep.java:81)\n\tat java.base/java.util.Optional.map(Unknown Source)\n\tat oracle.kubernetes.operator.helpers.ResponseStep.getActionForCallResponse(ResponseStep.java:81)\n\tat oracle.kubernetes.operator.helpers.ResponseStep.apply(ResponseStep.java:66)\n\tat oracle.kubernetes.operator.work.Fiber.doRunInternal(Fiber.java:452)\n\tat oracle.kubernetes.operator.work.Fiber.doRun(Fiber.java:376)\n\tat oracle.kubernetes.operator.work.Fiber.run(Fiber.java:307)\n\tat oracle.kubernetes.operator.work.ThreadLocalContainerResolver.lambda$wrapExecutor$1(ThreadLocalContainerResolver.java:81)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n","code":"","headers":{},"body":""}`

Thanks
Jay

**Comment by rjeberhard** [comment]
Are you testing against Kubernetes 1.25? If so, then this version of Kubernetes is not yet supported. It will be supported in the next release.

If not, then please respond with some more details about the Kubernetes environment that you are using.

**Comment by send2jayanth** [comment]
Thanks a lot Ryan for your prompt response .

Yes, I tried with K8S 1.25. Now I have downgraded to 1.23 & it works fine.
