### ISSUE TITLE
Operator fails when changing namespace from default

### ISSUE THREAD

**Issue by jeffellin** [oracle/weblogic-kubernetes-operator#375]
In the input section of the `create-weblogic-domain-inputs.yaml` their is a section for namespace.  If I change the value to something other than default the scripts fail.  This is because the template for the persistent volume does not contain a namespace.  The Job API assumes that the specified volume and claim are all in the same namespace. 

Fix is to add namespace to the PersistentVolume template

I will attach PR

**Comment by marinakog** [comment]
Hi @jeffellin could you please submit the error you are getting? we do create pv in default namespace but it does not break anything in the test environment. all our tests use custom name spaces for operator and domain. Could you please double check that your PV directory is create and has write permission , for example in the create-weblogic-domain-inputs :weblogicDomainStoragePath: /scratch/external-domain-home/pv001, mkdir -m 777 -p /scratch/external-domain-home/pv001"

**Comment by jeffellin** [comment]
@marinakog I am not able to reproduce the problem anymore :( . I even tried a new K cluster to try a clean setup,  So we are good for now.  Thanks
