### ISSUE TITLE
Question - CRD document too big.

### ISSUE THREAD

**Issue by p13x** [oracle/weblogic-kubernetes-operator#3984]
When I'm trying to update CRD document(20k lines) by command 'Kubectl -apply' I'm getting an error that document is too big. Workaround is to delete CRD document before can be created. A side affect of deleting the CRD is that all domain using the CRD will be deleted. Is there a way to apply a big CRD document?

**Comment by jshum2479** [comment]
How come you need to update the operator CRD ?   This looks like k8s is adding the `kubectl.kubernetes.io/last-applied-configuration`  which has previous config info,  for large CRD which can cause problems,  there is a `kubectl replace` command that you can use.

**Comment by rjeberhard** [comment]
Yes, as @jshum2479 said, @p13x you need to use `kubectl create` or `kubectl replace` directly and not use `kubectl apply`. The `apply` operation tries to preserve a copy of the originally applied version of the resource for later threeway merges, but this is unnecessary for CRD's and, as you noticed, makes the document too large.

If you use `kubectl replace` then there will not be any cascading deletion of existing resources.
