### ISSUE TITLE
Provide an easy way to remove a domain

### ISSUE THREAD

**Issue by markxnelson** [oracle/weblogic-kubernetes-operator#41]
Provide a script that will remove a domain and all of the associated resources, e.g. load balancer, ingress.  

Should not actually delete the domain directory, etc. on the PV.  Just remove the domain from the cluster.

**Comment by tbarnes-us** [comment]
Change is checked in.   Updates to readmes forthcoming in a future check-in.   See description of pull #131 for usage, script location, etc.
