### ISSUE TITLE
Solution for Windows:  sysctl -w vm.max_map_count=262144 

### ISSUE THREAD

**Issue by vasyaShum** [oracle/weblogic-kubernetes-operator#4172]
Solution for Windows:

I've been stuck with this problem for days, the solution is to run the following commands in cmd.exe (try Powershell or Bash if cmd doesn't work)

1) `wsl -d docker-desktop`
2) `sysctl -w vm.max_map_count=262144`

**Comment by rjeberhard** [comment]
Hi @vasyaShum... thanks for this. I'm confused though. What problem were you stuck with?

**Comment by vasyaShum** [comment]
I've posted the Windows solution that worked for me so that other users can be helped.

How to change settings on Windows for Docker.
