### ISSUE TITLE
Solution for Windows:  vm.max_map_count=262144  (Docker compose)

### ISSUE THREAD

**Issue by vasyaShum** [oracle/weblogic-kubernetes-operator#4173]
Solution for Windows:

I've been stuck with this problem for days, the solution is to run the following commands in cmd.exe (try Powershell or Bash if cmd doesn't work)

1) `wsl -d docker-desktop`
2) `sysctl -w vm.max_map_count=262144`

**Comment by jshum2479** [comment]
I don't understand the problem.  Is this a problem running docker desktop in windows?   This project is for weblogic kubernetes operator and is not related to docker desktop.
