### ISSUE TITLE
Is it possible for the wko introspector auxiliary image config version diff/merge to use the memory instead of the /tmp?

### ISSUE THREAD

**Issue by good92** [oracle/weblogic-kubernetes-operator#4295]
cat /tmp/decrypted_merged_model.json

https://docs.fluidattacks.com/criteria/requirements/036 Do not deploy temporary files
https://cwe.mitre.org/data/definitions/377.html CWE-377: Insecure Temporary File

from https://docs.fluidattacks.com/criteria/compliance/cwe

**Comment by robertpatrick** [comment]
@good92 We are trying to understand your exact concerns of this temporary file inside a short-lived container to help us figure out what might be possible.  In general, the model is something that the user has provided via a container image so most of what is in there should not be sensitive.  Is your concern simply the credentials that were pulled from the Secrets?

**Comment by good92** [comment]
Yes, my concern is that we can extract the secrets of the Weblogic installation from the file, whereas k8s secrets, secret management tools have been used. 

I saw that the introspector is ephemeral - short lived, but you have enough time to get the file,
you only need the authorization to access the Kubernetes cluster, to the namespace, to the pod
 and to be able to launch a shell on it.

I used a bash lsof to see the opened files when trying to understand previously why I was not able to deploy the new version.

I know that it is not easy to fix this, a little sorry to raise this. But I think you have to fix that.

**Comment by robertpatrick** [comment]
@good92 You do realize that Kubernetes Secrets are directly accessible in the introspector pod even if the decrypted merged model was removed, right?  

Kubernetes Secrets assume that the pods that use them are secure.   For example, by limiting kubectl access to the pod to only the Kubernetes administrator.  If a bad actor can kubectl Exec into the pod, that breaks the assumption.  For that matter, Kubernetes Secrets, by default, are not encrypted and the data is only Base64 encoded so with kubectl access to your secrets, I can decode your credentials unless you have taken steps to set up encryption.  Even then, they will be accessible in decrypted form in any pod using them.  

As such, I’m not seeing much value in addressing the short-lived temporary file given that the contents of the secrets will still be accessible.  Thoughts?

**Comment by good92** [comment]
ok, I agree but I will discuss it with colleagues.
