### ISSUE TITLE
project version 4.1.0-SNAPSHOT  in 4.0.6 release

### ISSUE THREAD

**Issue by xxhoffmann** [oracle/weblogic-kubernetes-operator#4296]
Hi
If I pull 4.0.6 release, the pom.xml refers to 4.1.0-SNAPSHOT.

Is that per design?

**Comment by rjeberhard** [comment]
@xxhoffmann, how did you attempt to the pull the 4.0.6 release? The 4.1.0-SNAPSHOT is from the `main` branch which is the development line for our next release, 4.1.0.

You can follow the documentation, here: https://oracle.github.io/weblogic-kubernetes-operator/quickstart/install/

The most basic installation of 4.0.6 is these steps:
```
kubectl create ns weblogic-operator
helm repo add weblogic-operator https://oracle.github.io/weblogic-kubernetes-operator/charts --force-update
 helm install weblogic-operator weblogic-operator/weblogic-operator --namespace weblogic-operator --version 4.0.6
```

**Comment by rjeberhard** [comment]
Discussed with the customer. The `main` branch is the open development line for the upcoming 4.1.0 release. The `release/4.0` branch is the open development line for the upcoming 4.0.7 release. The source for the 4.0.6 release can be found at the `v4.0.6` tag, which is a tag on the `release/4.0` branch. The source can also be found in a zip file attached to the GitHub release.
