### ISSUE TITLE
Domain resource can't be created successfully on Azure kubernetes Service

### ISSUE THREAD

**Issue by backwind1233** [oracle/weblogic-kubernetes-operator#4309]
[weblogic-kubernetes-operator:4.1.0](https://github.com/oracle/weblogic-kubernetes-operator/releases/tag/v4.1.0) just released.
I followed this [domain-on-pv-sample](https://oracle.github.io/weblogic-kubernetes-operator/samples/domains/domain-home-on-pv/sample/) step by step and try to create domain.

It **worked** when I run the sample with local minikube, 
but when I tried to run the sample on AKS, and it failed in the last step -- the step when I run the command `kubectl apply -f /tmp/sample/domain-resource.yaml`, I tried it for several times, but all failed.

![image](https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/b430aeeb-a56d-4699-ba48-c5becfb8cd29)

It showed `Job has reached the specified backoff limit`.
I run the command `kubectl get job <job-name> -o yaml > job.yaml` to check the value of `backoffLimit`, and it is `0`.
<img width="303" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/9d48b138-ef44-45c6-9868-e3ec29f26abf">

Could anyone tell what should I do if I want create domain with [weblogic-kubernetes-operator:4.1.0](https://github.com/oracle/weblogic-kubernetes-operator/releases/tag/v4.1.0) on AKS?

[Attached](https://github.com/oracle/weblogic-kubernetes-operator/files/12110882/eventlogfile.txt) is event log file.

**Comment by backwind1233** [comment]
Hello @ankedia, could you help to take a look at this issue?

**Comment by rjeberhard** [comment]
I see that you've already lengthened the timeout of the introspection job. Given that the timeout (activeDeadlineSeconds) is set at 10 minutes, introspection is probably not failing due to a timeout. Can you check the status of the introspection job as described here?: https://oracle.github.io/weblogic-kubernetes-operator/managing-domains/debugging/#check-the-introspector-job. 

Likely, we will find that the introspection job is failing for some reason that we can assist with.

**Comment by backwind1233** [comment]
Thank you @ankedia , here are the logs.
- [job-describe-log.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/12114782/job-describe-log.txt) is the output of `kubectl -n sample-domain1-ns describe job/sample-domain1-introspector`

- [job-events-log.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/12114783/job-events-log.txt) is the event log.
- [job-introspector-log.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/12114784/job-introspector-log.txt) is the output of `kubectl -n sample-domain1-ns logs pod/sample-domain1-introspector-lhc2k` output.

**Comment by ankedia** [comment]
It looks like introspector job pod is waiting to iniatilize. It's possible that the init container `operator-aux-container1` is failing. How do you build the domain creation image? Is it built on a different chipset or OS? Can you run the below command to get the init container logs of the intospector job pod?

**Comment by ankedia** [comment]
Run the following command to get the logs -> 
`kubectl logs <introspector-pod-name> -n <namespace> -c operator-aux-container1`

**Comment by backwind1233** [comment]
> It looks like introspector job pod is waiting to iniatilize. It's possible that the init container `operator-aux-container1` is failing. How do you build the domain creation image? Is it built on a different chipset or OS? Can you run the below command to get the init container logs of the intospector job pod?

Yes, I build the domain creation image.

> Is it built on a different chipset or OS?
Yes, I build it on my Mac OS with M1 .

**Comment by backwind1233** [comment]
> Run the following command to get the logs -> `kubectl logs <introspector-pod-name> -n <namespace> -c operator-aux-container1`

Yes, here is the result.

```
exec /weblogic-operator/scripts/auxImage.sh: exec format error
```

<img width="1092" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/2998bc08-73ba-4be6-87b8-8b30b32fd468">

**Comment by ankedia** [comment]
Ok. It looks like your domain creation image was built on ARM processor but the container runtime environment is different (for e.g. AMD). 

You can try setting the env variable before building the image ->
`export DEFAULT_DOCKER_PLATFORM=linux/amd6`

To confirm the image architecture, you can run this command ->
```
docker image inspect phx.ocir.io/weblogick8s/wdt-domain-image:WLS-v1  | grep -i architecture
        "Architecture": "amd64",
```
Looping in @jshum2479 and @robertpatrick for other suggestions.

**Comment by ankedia** [comment]
You can try setting the following environment variable before building the domain creation image on your Mac or build image on a Linux VM.
`export DEFAULT_DOCKER_PLATFORM=linux/amd64`

**Comment by backwind1233** [comment]
> Ok. It looks like your domain creation image was built on ARM processor but the container runtime environment is different (for e.g. AMD).
> 
> You can try setting the env variable before building the image -> `export DEFAULT_DOCKER_PLATFORM=linux/amd64`
> 
> To confirm the image architecture, you can run this command ->
> 
> ```
> docker image inspect phx.ocir.io/weblogick8s/wdt-domain-image:WLS-v1  | grep -i architecture
>         "Architecture": "amd64",
> ```
> 
> Looping in @jshum2479 and @robertpatrick for other suggestions.

Yes, maybe that's the reason.

**Comment by backwind1233** [comment]
> You can try setting the following environment variable before building the domain creation image on your Mac or build the image on a Linux VM. `export DEFAULT_DOCKER_PLATFORM=linux/amd64`

Ok, I will try that, thank you.

**Comment by backwind1233** [comment]
I used this command `export DEFAULT_DOCKER_PLATFORM=linux/amd64` to build the image on my Mac M1,
also check the architecture with 
```
docker image inspect  wlsgzhcontainer.azurecr.io/wdt-domain-image:WLS-v2| grep -i architecture

"Architecture": "arm64",
```
It is "amd64", but the job still failed.
<img width="1722" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/9a994df3-9e1e-4484-b1ad-b6bbcfc15724">

I will try to build the image on a virtual machine.

**Comment by backwind1233** [comment]
Hi @ankedia, could you run the domain creation sample with AKS successfully? Could you have a try, perhaps I made some silly mistakes.

**Comment by ankedia** [comment]
@backwind1233 I don't have access to an AKS environment to run the domain creation sample. From the `docker image inspect` command output that you have provided above, the image is still using `arm64` architecture and **not** `amd64`.  Have you tried to build the image on a virtual machine? I'll check with my colleagues tomorrow about why architecture is still `arm64` after you set `DEFAULT_DOCKER_PLATFORM` env variable to `linux/amd64`.

**Comment by backwind1233** [comment]
> 

Thank you @ankedia , I am tring to build the image on VM, 

I got an error when I try to build the image

```
Please set the JAVA_HOME environment variable to match the location of your Java installation. Java 8 or newer is required.
```

but I do set the JAVA_HOME
```
azureroot@buildvmimageonubuntu:/tmp/sample/wdt-artifacts/wdt-model-files/WLS-v1$ echo $JAVA_HOME
/home/azureroot/.sdkman/candidates/java/17.0.7-oracle

```
<img width="825" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/b7f25c56-a4fe-42bc-8def-7c1077c6e27b">

I am tring to fix it.

**Comment by backwind1233** [comment]
Hello @ankedia , I think you are right, it's the DOCKER_PLATFORM issue.

I build the image on a virtual machine, the architecture of the new image is "amd64".
Now it works as expected on AKS.

<img width="1400" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/403eda7e-6af3-4868-8453-7a6e856f8a40">

<img width="1057" alt="image" src="https://github.com/oracle/weblogic-kubernetes-operator/assets/4465723/01290b59-2ccc-4c81-8496-62573b01be58">
