### ISSUE TITLE
Couldn't create a domain by following steps in WLS on AKS Domain on PV sample

### ISSUE THREAD

**Issue by vanajamukkara** [oracle/weblogic-kubernetes-operator#4352]
Hi, I am trying to run the AKS sample by following the steps in sample doc - https://oracle.github.io/weblogic-kubernetes-operator/samples/azure-kubernetes-service/domain-on-pv/
I see these errors.
```
./create-domain-on-aks.sh -i my-create-domain-on-aks-inputs.yaml -o ~/azure -u ${TIMESTAMP}
Input parameters being used
export version="create-domain-on-aks-inputs-v1"
export dockerEmail="docker-email"
export dockerPassword="docker-password"
export dockerUserName="docker-user-name"
export azureLocation="eastus"
export namePrefix="vanaja "
export azureFileShareSecretNameSuffix="azure-secret"
export azureKubernetesNodeCount="2"
export azureKubernetesNodeVMSize="Standard_DS2_v2"
export azureKubernetesNodepoolNamePrefix="pool1"
javaOptions=-Dweblogic.StdoutDebugEnabled=false -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=50.0
export imagePullSecretNameSuffix="regcred"
export azureFileCsiNfsClassName="azurefile-csi-nfs"
export azureStorageShareNameSuffix="weblogic"
export serverPodMemoryRequest="1.5Gi"
export serverPodCpuRequest="250m"
export serverPodMemoryLimit="1.5Gi"
export serverPodCpuLimit="250m"
export persistentVolumeClaimNameSuffix="azurefile"
export weblogicAccountPassword="weblogic-account-password"
export weblogicDockerImage="container-registry.oracle.com/middleware/weblogic:12.2.1.4"
export weblogicUserName="weblogic-user-name"

Generating /home/vmukkara/azure/weblogic-on-aks/azure-csi-nfs.yaml
Generating /home/vmukkara/azure/weblogic-on-aks/pvc.yaml
Generating /home/vmukkara/azure/weblogic-on-aks/domain1.yaml
cp: cannot stat '/scratch/vmukkara/owls111303/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-on-pv/create-domain-inputs.yaml': No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
sed: can't read /home/vmukkara/azure/weblogic-on-aks/domain1.yaml: No such file or directory
Domain parameters being used

Generating /home/vmukkara/azure/weblogic-on-aks/admin-lb.yaml
Generating /home/vmukkara/azure/weblogic-on-aks/cluster-lb.yaml

The following files were generated:
  /home/vmukkara/azure/weblogic-on-aks/azure-csi-nfs.yaml
  /home/vmukkara/azure/weblogic-on-aks/pvc.yaml
  /home/vmukkara/azure/weblogic-on-aks/admin-lb.yaml
  /home/vmukkara/azure/weblogic-on-aks/cluster-lb.yaml
  /home/vmukkara/azure/weblogic-on-aks/domain1.yaml

Completed
```
[vmukkara@vmukkara-1 create-weblogic-domain-on-azure-kubernetes-service]$ ls -ltr ~/azure/weblogic-on-aks/
total 24
-rw-r--r-- 1 vmukkara dba 5013 Aug 21 22:00 create-domain-on-aks-inputs.yaml
-rw-r--r-- 1 vmukkara dba  365 Aug 21 22:00 azure-csi-nfs.yaml
-rw-r--r-- 1 vmukkara dba  381 Aug 21 22:00 pvc.yaml
-rw-r--r-- 1 vmukkara dba  433 Aug 21 22:00 admin-lb.yaml
-rw-r--r-- 1 vmukkara dba  434 Aug 21 22:00 cluster-lb.yaml

Also doc https://oracle.github.io/weblogic-kubernetes-operator/samples/azure-kubernetes-service/domain-on-pv/ says this under `Create WebLogic Domain` -
Copy the contents of the [WLS domain on AKS resource YAML file](https://raw.githubusercontent.com/oracle/weblogic-kubernetes-operator/release/4.1/kubernetes/samples/samples/azure-kubernetes-service/scripts/create-weblogic-domain/domain-on-pv/domain-resources/WLS/domain-on-pv-AKS-v1.yaml) that is included in the sample source to a file called ~/azure/weblogic-on-aks/domain-resource.yaml or similar. with a broken link for [WLS domain on AKS resource YAML file](https://raw.githubusercontent.com/oracle/weblogic-kubernetes-operator/release/4.1/kubernetes/samples/samples/azure-kubernetes-service/scripts/create-weblogic-domain/domain-on-pv/domain-resources/WLS/domain-on-pv-AKS-v1.yaml). So no way to get the working domain resource yaml.

Ed Zhihao is going to look into this. Entering this issue to keep track of it.

**Comment by backwind1233** [comment]
## Updates 
To make this sample work, the automation script in the sample needs some modifications. I’m still working on it.

**Comment by backwind1233** [comment]
The [PR](https://github.com/oracle/weblogic-kubernetes-operator/pull/4366) is used to address this issue.

I also create a github [workflow](https://github.com/azure-javaee/weblogic-kubernetes-operator/actions/runs/6105883744/attempts/1) used to verify the automation scripts `create-domain-on-aks.sh`

**Comment by robertpatrick** [comment]
Since there is no nmew activity, I assume this issue was resolved by the PR.
