### ISSUE TITLE
OWSM Policies - Caching

### ISSUE THREAD

**Issue by sebmichiels** [oracle/weblogic-kubernetes-operator#4362]
Hello,

Once my managed servers are up, I'm adding policies in the OWSM of Fusion Middleware.

It's working fine. I'm able to see my policies in EM and also in the Policy Manager Validator of each managed server.

Unfortunately, the cache is not refreshed when I execute a SOAP request on my managed server. I always have the issue : 
<WSM-07620> <Agent cannot enforce policies due to either failure in retrieving polices or error in validations,  detail= "WSM-02017 The document "XXXX" does not exist in the repository.

I have to restart the domain and everything works correctly. 

Furthemore, I cannot refresh the cache manually in the configuration of the OWSM. When I click on the button to refresh, the status of the managed server are set to failed. (At the end, it's not a big deal but maybe it's linked to my issue)

Is it a bug related to the fact that the managed servers are on different pods than the admin server and a kind of "coherence" is not working. 

Can you please advice? Because I really want to avoid this restart when the policies are updated.

**Comment by sebmichiels** [comment]
Is it linked to the fact that the Multitenancy is not yet supported for OWSM?

**Comment by sebmichiels** [comment]
Everything is working if the same service is deployed on the admin server. By the way, I'm using a dynamic cluster.

**Comment by rjeberhard** [comment]
@ddsharpe, do you know who might be able to help @sebmichiels with OWSM? @sebmichiels, the engineers watching these issues are mostly knowledgable about WebLogic and OWSM is a service that comes with the layered Fusion Middleware products.

**Comment by ddsharpe** [comment]
@rjeberhard @sebmichiels I posted a message to the WSM team to see if they can help.

**Comment by rjeberhard** [comment]
@sebmichiels, we spoke to the OWSM team and they confirmed that a restart should not be required to update the OWSM cache. They would like to review your environment and assist with the issue. Can you please open an SR with Oracle Support against OWSM?

**Comment by sebmichiels** [comment]
Thanks a lot for your time. I will do it!
