### ISSUE TITLE
Fixing FAILED_NOT_RESTARTABLE

### ISSUE THREAD

**Issue by rakha29101995** [oracle/weblogic-kubernetes-operator#4367]
I have issue in weblogic, when server start I do force shutdown and then now the server cannot up and have message FAILED_NOT_RESTARTABLE. i've been try for restart service weblogic but still have some error. any advice?

**Comment by rjeberhard** [comment]
What version of the operator are you using? The liveness probe should be failing if the server is in FAILED_NOT_RESTARTABLE state. We have also recently updated the liveness probe to fail anytime that the server process is missing. 

As a workaround, you can also always delete the pod for the server instance and that pod will be recreated.

**Comment by robertpatrick** [comment]
@rakha29101995 Is this still an issue?
