### ISSUE TITLE
Weblogic operator 4.1.1 and 4.1.2 mount issues 

### ISSUE THREAD

**Issue by zukko78** [oracle/weblogic-kubernetes-operator#4368]
Hello,

We had a problem with operator versions 4.1.1 and 4.1.2 when mounting the following template:
Domain Configuration Manifest:
 
   volumeMounts:  
      - mountPath: /opt/dtv/DeviceProfileService/
        name: dps-config-dps-crbc-domain1
      - mountPath: /opt/dtv/DeviceProfileService/business_policy_rules/
        name: dps-config-br-dps-crbc-domain1
      - mountPath: /opt/dtv/DPSUI/
        name: dps-config-ui-dps-crbc-domain1
    volumes:
      - configMap:
          name: dps-config-br-dps-crbc-domain1
        name: dps-config-br-dps-crbc-domain1
      - configMap:
          name: dps-config-ui-dps-crbc-domain1
        name: dps-config-ui-dps-crbc-domain1
      - configMap:
          name: dps-config-dps-crbc-domain1
        name: dps-config-dps-crbc-domain1

error in operator logs:
{"timestamp":"2023-09-07T20:26:43.014359494Z","thread":52,"fiber":"","namespace":"","domainUID":"","level":"FINE","class":"oracle.kubernetes.operator.http.rest.ResponseDebugLoggingFilter","method":"filter","timeInMillis":1694118403014,"message":"response body={\"apiVersion\":\"admission.k8s.io/v1\",\"kind\":\"AdmissionReview\",\"response\":{\"uid\":\"1e2563d6-d621-40a7-8d96-22d8c4b329c4\",\"allowed\":false,\"status\":{\"message\":\"The mount path \\u0027/opt/dtv/DeviceProfileService/\\u0027 in entry \\u0027dps-config-dps-crbc-domain1\\u0027 and the mount path \\u0027/opt/dtv/DeviceProfileService/business_policy_rules/\\u0027 in entry \\u0027dps-config-br-dps-crbc-domain1\\u0027 are overlapping.\"}}}","exception":"","code":"","headers":{},"body":""}

Failed to save resource: {"error":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"weblogic.validating.webhook\" denied the request: The mount path '/opt/dtv/DeviceProfileService/' in entry 'dps-config-dps-crbc-domain1' and the mount path '/opt/dtv/DeviceProfileService/business_policy_rules/' in entry 'dps-config-br-dps-crbc-domain1' are overlapping.","code":400},"messages":["admission webhook \"weblogic.validating.webhook\" denied the request: The mount path '/opt/dtv/DeviceProfileService/' in entry 'dps-config-dps-crbc-domain1' and the mount path '/opt/dtv/DeviceProfileService/business_policy_rules/' in entry 'dps-config-br-dps-crbc-domain1' are overlapping."],"isUsedForNotification":false}

The same configuration is successfully working on operator 4.0.6

**Comment by rjeberhard** [comment]
Fixed in version 4.1.3.
