### ISSUE TITLE
wdt-and-wit-utility.sh used wrong url and filename in function install_wit 

### ISSUE THREAD

**Issue by yaozg** [oracle/weblogic-kubernetes-operator#4385]
From v3.4.5 function wdt-and-wit-utility.sh used wrong url and filename in function install_wit 

All WDT should use WIT in funciton install_wit.
The URL https://github.com/oracle/weblogic-deploy-tooling/releases/download/releas also should change to 
https://github.com/oracle/weblogic-image-tool/releases/download/releas

function install_wit {

  WIT_INSTALL_ZIP_FILE="${WIT_INSTALL_ZIP_FILE:-imagetool.zip}"

  echo @@ " Info: WDT_INSTALL_ZIP_URL is '$WDT_INSTALL_ZIP_URL'"
  if [ -z ${WDT_INSTALL_ZIP_URL} ]; then
    echo @@ "WDT_INSTALL_ZIP_URL is not set"
    if [ "$WDT_VERSION" == "LATEST" ]; then
      WDT_INSTALL_ZIP_URL=${WDT_INSTALL_ZIP_URL:-"https://github.com/oracle/weblogic-deploy-tooling/releases/latest/download/$WDT_INSTALL_ZIP_FILE"}
    else
      WDT_INSTALL_ZIP_URL=${WDT_INSTALL_ZIP_URL:-"https://github.com/oracle/weblogic-deploy-tooling/releases/download/release-$WDT_VERSION/$WDT_INSTALL_ZIP_FILE"}
    fi
  fi

**Comment by xiancao** [comment]
@ddsharpe ^^^

**Comment by rjeberhard** [comment]
Fixed in release/3.4 branch. The updated script is in the branch now and will also be in the next 3.4 bug-fix release.
