### ISSUE TITLE
Can I run oracle forms using the operator?

### ISSUE THREAD

**Issue by pjelar** [oracle/weblogic-kubernetes-operator#4835]
I'm wondering if it's possible to pass fmw files in an auxiliary container to a weblogic domain and start fmrweb?

**Comment by alai8** [comment]
Quoting from Oracle Forms team: "Unfortunately, we (the Forms team) have not done enough testing with the utility to know if can be used or if it will work.  It may be possible to make it work, but we currently do not know (yet)."
