### ISSUE TITLE
Error pulling weblogic:12.2.1.3 before creating a domain

### ISSUE THREAD

**Issue by cmolinah** [oracle/weblogic-kubernetes-operator#51]
I'm following this guide to create a domain: https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/creating-domain.md (I have also checked the associated video in youtube).

I'm having troubles with step "Pull the WebLogic Server image"

I executed:

```
kubectl create secret docker-registry docker-domain1 -n domain1 --docker-server=index.docker.io/v1/ --docker-username=cmolinah --docker-password=************** --docker-email=******@mail.com

docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: cmolinah
Password:
Login Succeeded
docker pull store/oracle/weblogic:12.2.1.3
Error response from daemon: pull access denied for store/oracle/weblogic, repository does not exist or may require 'docker login'
```

Is the documentation correct?

**Comment by sharmasourabh** [comment]
[quikstart doc](https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/quickstart.md) should also be updated.
