### ISSUE TITLE
Managed server pods not migrating to healthy k8s worker nodes 

### ISSUE THREAD

**Issue by bhaveshpatel826** [oracle/weblogic-kubernetes-operator#530]
We have configured weblogic cluster on kubernetes cluster using weblogic operator, we were able to complete the deployment successfully, the scaling up/down of the managed server works fine when done using "kubectl edit domain -n namespace", as we have 3 nodes cluster when one of the worker nodes is unhealthy the pods running on that worker nodes doesn't migrate to another healthy worker node in the kubernetes cluster. We also noticed that whenever we turnoff a worker node on purpose the scaling using edit domain also doesn't work, then we have to re-do the entire weblogic operator and domain creation again.

Kubernetes cluster info:-
Multimaster setup:- 3 master nodes and 3 worker nodes
version:-  1.11.3

weblogic docker image version = 12.2.1.3
weblogic operator image version = latest

**Comment by moreaut** [comment]
Can you try this again with the latest version (2.0) of the operator (master branch)?

Thanks, -Tom

**Comment by vkraemer** [comment]
Hi,

I have a couple questions about the 'details' of this issue:

1. How long had the worker node been unhealthy when you checked to see if the pods had migrated?

2. Was there space on the other nodes to accept the pod when it would have migrated?

3. How did you turn off the node when you encountered the problem scaling?  Did you drain pods off the node?

Thanks

**Comment by vkraemer** [comment]
Hi,

I have been working on recreating the configuration described in this issue.

I noticed that the admin server and domain are created on a minion node... not the master. When you 'turn off a worker node on purpose' did you turn off the node worker that did not host the domain content and was not hosting the WLS admin server for the domain?  If that node disappears things will be pretty broken.

Also,

Can you include steps to recreate your configuration... or attach the various yamls that are used to create any PV/PVC objects and the domain?

**Comment by vkraemer** [comment]
This will need to be assigned to someone that has access to the resources necessary to form a multi-node cluster for further testing.

**Comment by creativefre** [comment]
Operator version: 2.1
We also tested this on a multi-node environment. When disabling a worker machine (lnx-stage03), the managed servers do not migrate to the other healthy node (lnx-stage02).
![image](https://user-images.githubusercontent.com/23296871/57850664-be42ba80-77de-11e9-9c4b-129805180dc1.png)

This is the log of a managed server in pending state.
![image](https://user-images.githubusercontent.com/23296871/57850759-0cf05480-77df-11e9-8d16-c6aa7214c3be.png)
We waited for 15 minutes but nothing happens.

After we started the worker node (lnx-stage03) again, the pods begin to recreate them self's on the same worker node (lnx-stage03)
![image2019-5-16_13-36-17](https://user-images.githubusercontent.com/23296871/57851125-1928e180-77e0-11e9-88fe-c7635b8e2c2d.png)

After the restart of the worker node they work fine as before.

Can you guys look into this, to fix this issue?

**Comment by rjeberhard** [comment]
Looks like this will need to be handled as a feature request as Kubernetes presently delays rescheduling nodes to avoid split brain behavior.  

https://github.com/kubernetes/kubernetes/issues/12140

Will experiment with pod eviction and pod disruption budge configuration.
