### ISSUE TITLE
Build fails because default value for weblogicOperatorImageName doesn't match unit test

### ISSUE THREAD

**Issue by haj** [oracle/weblogic-kubernetes-operator#592]
Building using Wercker fails because the default value for weblogicOperatorImageName in create-weblogic-operator-inputs.yaml doesn't match the expected value in the unit tests. 

The unit test expects:
weblogicOperatorImageName="weblogic-kubernetes-operator:1.1" 

The default value in create-weblogic-operator-inputs.yaml:
weblogicOperatorImageName="oracle/weblogic-kubernetes-operator:1.1"

Two issues as I see it: 
1. The image name shouldn't need to be prefixed with "oracle" since the repository will be read from the environment variables set in Wercker

2. Why is the image version hardcoded in the unit tests?

3. In the Wercker file IMAGE_TAG_OPERATOR is being overwritten by branch name: 
export IMAGE_TAG_OPERATOR="${WERCKER_GIT_BRANCH//[_\/]/-}"

I managed to build it successfully by removing oracle as a prefix from the weblogicOperatorImageName, 

<img width="737" alt="screenshot 2018-12-08 at 21 16 54" src="https://user-images.githubusercontent.com/452958/49688647-afb8ee80-fb2e-11e8-91a3-4ffdea3d14eb.png">

**Comment by russgold** [comment]
Can you see if it is working for you using the 'develop' branch? I think we have fixed this.

**Comment by moreaut** [comment]
Are you still seeing this problem?  Can we close this issue?

Thanks, -Tom

**Comment by haj** [comment]
You can close this issue, although I didn't test the dev branch nor release
2 yet.

Thanks,
Hassan

Den tir. 8. jan. 2019 kl. 16.12 skrev Tom Moreau <notifications@github.com>:

**Comment by moreaut** [comment]
Thanks Hassan.  Please file an issue if you run into problems in 2.0.
