### ISSUE TITLE
mvn clean install command fails

### ISSUE THREAD

**Issue by srbollin** [oracle/weblogic-kubernetes-operator#662]
Build fails on below error.

[INFO] 
[INFO] --- fmt-maven-plugin:2.4.0:check (default) @ operator-integration-tests ---
[warn] Source directory '/pipeline/source/integration-tests/src/main/java' does not exist, ignoring.
[debug] Using Google style
[INFO] Processed 10 files (0 non-complying).
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ operator-integration-tests ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /pipeline/source/integration-tests/target/operator-integration-tests-1.1.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ operator-integration-tests ---
[INFO] Installing /pipeline/source/integration-tests/target/operator-integration-tests-1.1.jar to /pipeline/cache/.m2/oracle/kubernetes/operator-integration-tests/1.1/operator-integration-tests-1.1.jar
[INFO] Installing /pipeline/source/integration-tests/pom.xml to /pipeline/cache/.m2/oracle/kubernetes/operator-integration-tests/1.1/operator-integration-tests-1.1.pom
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building installation-tests 1.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ installation-tests ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ installation-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /pipeline/source/kubernetes/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ installation-tests ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ installation-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /pipeline/source/kubernetes/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ installation-tests ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 79 source files to /pipeline/source/kubernetes/target/test-classes
[WARNING] /pipeline/source/kubernetes/src/test/java/oracle/kubernetes/operator/utils/KubernetesArtifactUtils.java: Some input files use or override a deprecated API.
[WARNING] /pipeline/source/kubernetes/src/test/java/oracle/kubernetes/operator/utils/KubernetesArtifactUtils.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ installation-tests ---
[INFO] Surefire report directory: /pipeline/source/kubernetes/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running oracle.kubernetes.operator.utils.CreateOperatorInputsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec
Running oracle.kubernetes.operator.create.CreateOperatorUsageTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.148 sec
Running oracle.kubernetes.operator.create.CreateOperatorGeneratedFilesDebugEnabledTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.536 sec
Running oracle.kubernetes.operator.create.CreateOperatorInputsValidationTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.111 sec
Running oracle.kubernetes.operator.create.CreateDomainUsageTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.044 sec
Running oracle.kubernetes.operator.create.CreateOperatorGeneratedFilesExtRestCustomTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.115 sec
Running oracle.kubernetes.operator.create.CreateDomainGeneratedFilesVoyagerTest
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.383 sec
Running oracle.kubernetes.operator.create.CreateDomainInputsFileTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.33 sec
Running oracle.kubernetes.operator.create.CreateDomainGeneratedFilesOptionalFeaturesEnabledTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.204 sec
Running oracle.kubernetes.operator.create.CreateDomainInputsValidationTest
Tests run: 69, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.956 sec
Running oracle.kubernetes.operator.create.CreateOperatorGeneratedFilesOptionalFeaturesEnabledTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.133 sec
Running oracle.kubernetes.operator.create.CreateOperatorInputsFileTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.258 sec <<< FAILURE!
defaultInputsFile_hasCorrectContents(oracle.kubernetes.operator.create.CreateOperatorInputsFileTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: 
!!oracle.kubernetes.operator.utils.CreateOperatorInputs
elkIntegrationEnabled: 'false'
externalDebugHttpPort: '30999'
externalOperatorCert: ''
externalOperatorKey: ''
externalRestHttpsPort: '31001'
externalRestOption: NONE
externalSans: ''
internalDebugHttpPort: '30999'
javaLoggingLevel: INFO
namespace: weblogic-operator
remoteDebugNodePortEnabled: 'false'
serviceAccount: weblogic-operator
targetNamespaces: default
version: create-weblogic-operator-inputs-v1
weblogicOperatorImage: weblogic-kubernetes-operator:1.1
weblogicOperatorImagePullPolicy: IfNotPresent
weblogicOperatorImagePullSecretName: ''

     but: 
was
!!oracle.kubernetes.operator.utils.CreateOperatorInputs
elkIntegrationEnabled: 'false'
externalDebugHttpPort: '30999'
externalOperatorCert: ''
externalOperatorKey: ''
externalRestHttpsPort: '31001'
externalRestOption: NONE
externalSans: ''
internalDebugHttpPort: '30999'
javaLoggingLevel: INFO
namespace: weblogic-operator
remoteDebugNodePortEnabled: 'false'
serviceAccount: weblogic-operator
targetNamespaces: default
version: create-weblogic-operator-inputs-v1
weblogicOperatorImage: oracle/weblogic-kubernetes-operator:1.1
weblogicOperatorImagePullPolicy: IfNotPresent
weblogicOperatorImagePullSecretName: ''

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at oracle.kubernetes.operator.create.CreateOperatorInputsFileTest.defaultInputsFile_hasCorrectContents(CreateOperatorInputsFileTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running oracle.kubernetes.operator.create.CreateOperatorGeneratedFilesOptionalFeaturesDisabledTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 sec
Running oracle.kubernetes.operator.create.CreateDomainGeneratedFilesOptionalFeaturesDisabledTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.188 sec
Running oracle.kubernetes.operator.helm.HelmDomainValuesTest
Tests run: 119, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec
Running oracle.kubernetes.operator.helm.HelmOperatorValuesTest
Tests run: 58, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec

Results :

Failed tests:   defaultInputsFile_hasCorrectContents(oracle.kubernetes.operator.create.CreateOperatorInputsFileTest): (..)

Tests run: 416, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] weblogic-kubernetes-operator ....................... SUCCESS [  2.341 s]
[INFO] operator-model ..................................... SUCCESS [  8.211 s]
[INFO] operator-swagger ................................... SUCCESS [  0.687 s]
[INFO] operator-runtime ................................... SUCCESS [ 27.423 s]
[INFO] operator-integration-tests ......................... SUCCESS [  0.746 s]
[INFO] installation-tests ................................. FAILURE [ 10.899 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.484 s
[INFO] Finished at: 2018-12-17T12:44:04Z
[INFO] Final Memory: 67M/1839M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project installation-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /pipeline/source/kubernetes/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :installation-tests

**Comment by bollinenisravan** [comment]
I used the master branch when it failed. But got this fixed by changing the weblogicOperatorImage value to weblogic-kubernetes-operator:1.1. Removed "oracle/" part from the file.

**Comment by simon-meng-cn** [comment]
The build failure reason is the value for weblogicOperatorImageName in create-weblogic-operator-inputs.yaml doesn't match the expected value in the unit tests. See CreateOperatorInputsFileTest.java.

To fix it, you can change values in the two files to make them match.
