### ISSUE TITLE
adminserver environment and setup scripts - BLOCKER

### ISSUE THREAD

**Issue by bryantidd** [oracle/weblogic-kubernetes-operator#69]
It looks like it tries to use a directory to mount the secret to for the weblogic credentials based on /var/run/secrets-$DomainUid, instead of the secretsMountPath from create-domain-job-inputs.yaml.

Also, the domain creation script in the configmap seems to leave the domain name as base_doamin, even after writing the domain. when I exec to the adminserver pod and check the env it lists the DOMAIN_PATH correctly after sourcing the /shared/domain/widomain/bin/setDomainEnv.sh file, but the DOMAIN_NAME is always base_doamin. When I connect and check the name and read the domain via wlst.sh it seems correct. Thoughts???

**Comment by moreaut** [comment]
I'm not finding any code in the weblogic operator git repository that sets the pod's DOMAIN_NAME environment variable to base_domain.  I'm guessing this is coming from the weblogic docker image itself - i.e. store/oracle/weblogic:12.2.1.3

**Comment by moreaut** [comment]
On secretsMountPath, there's a comment in https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/creating-domain.md that says that it should not be modified:

secretsMountPath | Path for mounting secrets.  This parameter should not be modified. |

On the other hand, when I tested it, I noticed that it MUST be set to /var/run/secrets-<domainUID>

I don't see much benefit in letting customers control this in-pod pathname.  Instead, I think we should probably just pick a fixed pathname, just like we do for the operator's config map and secrets.

**Comment by bryantidd** [comment]
If you decide to force the secrets mount path based on convention (/var/run/secrets-${domainUID}), then I would suggest taking the secretsMountPath out of the yaml...since when ever you need it you could compute it.

In my version of the yaml file it just reads:
# Path for mounting secrets
secretsMountPath: /var/run/secrets-domain1 - so if you don't use domain1 for your domainID you're kind of out of luck.

**Comment by bryantidd** [comment]
DOMAIN_NAME is set to base_domain in the create domain process from the wls.jar domain template I think. It usually gets set to the real name when you read and write the domain from the file system. For some reason the environment variable doesn’t seem to get set though. Maybe someone else can verify what I am seeing by running env in a domain and rerun env after sourcing the setDomainEnv.sh file.

**Comment by moreaut** [comment]
I'm working on a fix for the DOMAIN_NAME issue.

Basically, the wls image supports several environment variables (e.g. DOMAIN_NAME) that the container can override.  I need to fix the weblogic operator to set these environment variables on
the pod it creates for the wls server.  The variables are: DOMAIN_NAME, DOMAIN_HOME, ADMIN_NAME (the name of the admin server), and ADMIN_PORT.

**Comment by moreaut** [comment]
I'm going to work on a fix for the secretsMountPath problem too.

I'm going to choose a fixed file or computable name in the pod for the secrets for the domain
credential, and I'm going to remove support for secretsMountPath from create-domain-job-inputs.yaml.

**Comment by bryantidd** [comment]
Sounds like a good plan. Thanks.

**Comment by moreaut** [comment]
Both issues are fixed:

1) the DOMAIN_NAME, DOMAIN_HOME, ADMIN_NAME and ADMIN_PORT env vars are properly set in the weblogic server pods.

2) the ADMIN_USERNAME and ADMIN_PASSWWORD env vars are set to empty strings in the weblogic server pods.

3) secretsVolumeMount has been removed from create-operator-inputs.yaml.  The secrets are mounted in the domain job and weblogic server pods under the fixed pathname '/weblogic-operator/secrets'.  NOTE: this change is not backwards compatible - you'll need to recreate your domains.
