### ISSUE TITLE
"docker build -t weblogic-kubernetes-operator:some-tag --no-cache=true ." Fails.

### ISSUE THREAD

**Issue by srbollin** [oracle/weblogic-kubernetes-operator#692]
Please update the documentation to include the build args in the docker build command to avoid below issue.

[root@llg00cpv weblogic-kubernetes-operator]# docker build -t weblogic-kubernetes-operator:srbollin --build-arg VERSION=1.1 --no-cache=true .
Sending build context to Docker daemon 97.46MB
Step 1/12 : FROM store/oracle/serverjre:8
---> 719e41f3e37b
Step 2/12 : MAINTAINER Ryan Eberhard ryan.eberhard@oracle.com
---> Running in d61d788eefd0
Removing intermediate container d61d788eefd0
---> 8b343ba8766b
Step 3/12 : RUN mkdir /operator
---> Running in ec1e30fe5613
Removing intermediate container ec1e30fe5613
---> 23eac5aee04c
Step 4/12 : RUN mkdir /operator/lib
---> Running in de784b672224
Removing intermediate container de784b672224
---> 319270ee33aa
Step 5/12 : ENV PATH=$PATH:/operator
---> Running in 06de21ae1606
Removing intermediate container 06de21ae1606
---> a4bff0fef608
Step 6/12 : ARG VERSION
---> Running in 3e9765bff3b5
Removing intermediate container 3e9765bff3b5
---> e82d6edf99b7
Step 7/12 : COPY src/scripts/* /operator/
---> 3694603b2bdc
Step 8/12 : COPY operator/target/weblogic-kubernetes-operator-$VERSION.jar /operator/weblogic-kubernetes-operator.jar
---> bc42724f80d6
Step 9/12 : COPY operator/target/lib/*.jar /operator/lib/
---> 59eb217c228b
Step 10/12 : HEALTHCHECK --interval=1m --timeout=10s CMD /operator/livenessProbe.sh
---> Running in 089e25e4dfe2
Removing intermediate container 089e25e4dfe2
---> 706635c10b41
Step 11/12 : WORKDIR /operator/
Removing intermediate container 1371330b3c19
---> 664b853fc859
Step 12/12 : CMD ["/operator/operator.sh"]
---> Running in e239b333767a
Removing intermediate container e239b333767a
---> 80aeee9de609
Successfully built 80aeee9de609
Successfully tagged weblogic-kubernetes-operator:srbollin
[root@llg00cpv weblogic-kubernetes-operator]#

Without passing argument, encountered below issue.

[root@llg00cpv weblogic-kubernetes-operator]# docker build -t weblogic-kubernetes-operator:srbollin --no-cache=true .
Sending build context to Docker daemon 97.46MB
Step 1/12 : FROM store/oracle/serverjre:8
---> 719e41f3e37b
Step 2/12 : MAINTAINER Ryan Eberhard ryan.eberhard@oracle.com
---> Running in de2b32a3eda4
Removing intermediate container de2b32a3eda4
---> 6baa9ecf0326
Step 3/12 : RUN mkdir /operator
---> Running in 9ca7c1c2a940
Removing intermediate container 9ca7c1c2a940
---> e38edf2162d2
Step 4/12 : RUN mkdir /operator/lib
---> Running in 422bbe6027a9
Removing intermediate container 422bbe6027a9
---> fdb2c2957def
Step 5/12 : ENV PATH=$PATH:/operator
---> Running in 39c134e82efe
Removing intermediate container 39c134e82efe
---> e48fb56f3a5b
Step 6/12 : ARG VERSION
---> Running in 51f0640218d7
Removing intermediate container 51f0640218d7
---> e6273d7ef46a
Step 7/12 : COPY src/scripts/* /operator/
---> 17a571a0e770
Step 8/12 : COPY operator/target/weblogic-kubernetes-operator-$VERSION.jar /operator/weblogic-kubernetes-operator.jar
COPY failed: stat /scratch/docker/tmp/docker-builder148281544/operator/target/weblogic-kubernetes-operator-.jar: no such file or directory
[root@llg00cpv weblogic-kubernetes-operator]#

**Comment by bollinenisravan** [comment]
I got that command from 1.1 docs.

**Comment by simon-meng-cn** [comment]
The command is in https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/v1.1/installation.md

**Comment by alai8** [comment]
As of release 2.0-rc2, the "Build docker image" section has been moved to https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/developer.md and it has been updated with the buiid-arg in the example as suggested. Thanks
