### ISSUE TITLE
2.0-rc1 Operator:  Clusters only support default channel

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-kubernetes-operator#726]
Code inspection reveals that the 2.0 operator likely isn't generating services for cluster admin channel, SSL channel, or custom channels -- at least for dynamic clusters.   The work-around is to use the default channel.

**Comment by rjeberhard** [comment]
Internal tracking: OWLS-70864

**Comment by tbarnes-us** [comment]
Fixed in pending release 2.0.1 by @jgrundback
