### ISSUE TITLE
2.0 rc1 Operator: ListenAddress and log directories may be incorrect

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-kubernetes-operator#727]
The Operator may fail to override the listen addresses and log directories in a Domain Home, and so leave them at their locations specified in the original Domain Home configuration when it starts WL pods.    This is usually not a significant issue for log directories, but can be for listen addresses.   A server will not start if its listen address is incorrect.

One work-around is to configure unset/blank listen addresses in the original Domain Home.   This risks some problems with JTA HA - stalled transactions after a crash or network failure - but is fine for ad hoc testing.   Another work-around is to configure the exact required listen addresses in the original Domain Home, in the form `DOMAIN_UID-SERVER_NAME`, all in lower case, with underscores (_) converted to dashes (-).

One symptom for this problem are 'situational config' error messages or warnings in the WebLogic Server logging (echoed to the pod logs by default).

Pull https://github.com/oracle/weblogic-kubernetes-operator/pull/716 looks like it works around the issue.

**Comment by tbarnes-us** [comment]
Pull https://github.com/oracle/weblogic-kubernetes-operator/pull/716 looks like it works around the issue.

**Comment by rjeberhard** [comment]
Internal tracking: OWLS-70905
