### ISSUE TITLE
Invalid parameter syntax given for create-domain.sh in documentation

### ISSUE THREAD

**Issue by bollinenisravan** [oracle/weblogic-kubernetes-operator#731]
the script is not allowing "-v" option and also it says "-u" & "-p" options are mandatory. Not sure if it has something to do with my code. Please guide.

In quickstart.md , Section 5.b below line. Requests us to run below command to create the domain.

"$ ./create-domain.sh -i my-inputs.yaml -o /some/output/directory -e -v"

After passing both username and password to the script, it now fails with below error.

**Error from server (BadRequest): error when creating "/scratch/output/uidomain/weblogic-domains/uidomain/domain.yaml": the API version in the data (weblogic.oracle/v2) does not match the expected API version (weblogic.oracle/v1)**
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
Error from server (NotFound): domains.weblogic.oracle "uidomain" not found
[ERROR] The domain resource uidomain was not found
[root@llg00cpv domain-home-in-image]#

**Comment by markxnelson** [comment]
@bollinenisravan I have created a PR to fix these issues.

**Comment by bollinenisravan** [comment]
@markxnelson Thanks for the quick turnaround. 

Also regarding passing option "-e" to create-domain.sh, it's worth noting users to use that option only if it is a single node. If it is a multi-node cluster, the image would not be available across worker nodes.


Just FYI, I have used below commands to delete the CRD resource.

[root@llg00cpv weblogic-kubernetes-operator]# kubectl get crd -o wide
NAME                      AGE
domains.weblogic.oracle   5d
[root@llg00cpv weblogic-kubernetes-operator]# kubectl delete crd domains.weblogic.oracle
customresourcedefinition "domains.weblogic.oracle" deleted
[root@llg00cpv weblogic-kubernetes-operator]#
