### ISSUE TITLE
While installing Operator 2.0 helm clint is not getting installed

### ISSUE THREAD

**Issue by charuni2018** [oracle/weblogic-kubernetes-operator#751]

**Comment by charuni2018** [comment]
Hello Team,

I am trying to install the WebLogic Operator 2.0. I have the PKS cluster with me where Tiller is already installed on one of the namespace. I was trying to install helm client locally on my system, i have placed the helm.exe under the .kube directory but when I execute its not getting installed and getting the error.

$ ./helm.exe init
$HELM_HOME has been configured at C:\Users\charuni_verma\.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!

What am I suppose to do I am confused here. Second clarification which I need is  I got the docker images of WL Operator 2.0, weblogic 12.2.1.3 but after that I am getting issue while patching the docker images as how to execute it.
Please assist.

**Comment by moreaut** [comment]
I'm trying to find out if anyone on the team knows how to address your helm installation issue.
Have you checked the helm documentation?  https://github.com/helm/helm

Please provide more details on weblogic image patching issue you're running into.

Thanks, -Tom

**Comment by moreaut** [comment]
It looks like you might have successfully installed helm, i.e. that helm is just telling you that tiller is already installed.

What happens if you do a 'helm.exe --client-only'?

Also, how about 'helm.exe list'?

Thanks, -Tom

**Comment by charuni2018** [comment]
with helm I am seeing the below error. I am also checking with my internal team on the access.
$ ./helm.exe list
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system"

For WL image its not the error. Its on the understanding on the execution steps 
I managed to pull the WL docker image 12.2.1.3 from the docker hub. after that on my local system I have created the domain.properties file with the username and pwd  and build it

# docker run -d -p 7001:7001 -p 9002:9002 -v domain.properties:/u01/oracle/properties/domain.properties store/oracle/weblogic:12.2.1.3
c22d5090c189220dc25c96ea2c3dbbd5afbe53b07918455c428c8c8774102b12

# docker logs c22d5090c189220dc25c96ea2c3dbbd5afbe53b07918455c428c8c8774102b12
awk: warning: command line argument `/u01/oracle/properties/domain.properties' is a directory: skipped
The domain username is blank.  The Admin username must be set in the properties file.

Anything which I am doing wrong.

**Comment by moreaut** [comment]
It looks like helm is working but tiller may not have been granted enough permissions to do 'helm list'.  Have you tried installing the operator helm chart?  Did it work?  Tiller will need to be granted enough permission to read and write both the operator and domain namespaces you choose, as well as permission to create global cluster roles and cluster role bindings.

**Comment by moreaut** [comment]
Check out the sample to create a domain home in image at github oracle/docker-images/samples/OracleWebLogic/samples/12213-domain-home-in-image.
The documentation will help you set up your docker build.

The sample pulls your weblogic image and creates your domain home on top of the weblogic to create a domain home image during the docker build.  I highly suggest you use this to create your image.

It looks like what you are doing is creating a weblogic image, but waiting to create the domain when you run a container using the weblogic image.  What the operator manages is a domain home in an image.

Pertaining to your docker run message, you are attempting to mount the domain.properties. mount the directory that contains the domain.properties and your shell script can access it in the named location. However, this again does not create an image that can be used by the operator

**Comment by charuni2018** [comment]
I managed to get the helm client installed and it is working.
