### ISSUE TITLE
repository docker.io/oracle/weblogic not found: does not exist or no pull access

### ISSUE THREAD

**Issue by shaunxa** [oracle/weblogic-kubernetes-operator#752]
Hi All,

I followed the quick start procedure and I encountered an error at the step below. The error message shows it tried to pull a wrong repository docker.io/oracle/weblogic. Please kindly help. Thanks.

Cheers,
Shaun

---
[opc@centos7-1 domain-home-in-image]$ ./create-domain.sh -i my-domain-inputs.yaml -o my-domain-outputs.yaml -u weblogic -p welcome1 -e
...
BUILD_ARG= --build-arg CUSTOM_DOMAIN_NAME=sample-domain1 --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_NAME=admin-server --build-arg CUSTOM_ADMIN_PORT=7001 --build-arg CUSTOM_MANAGED_SERVER_PORT=8001 --build-arg CUSTOM_DEBUG_PORT=8453
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   610    0   610    0     0    445      0 --:--:--  0:00:01 --:--:--   446
100  933k  100  933k    0     0   479k      0  0:00:01  0:00:01 --:--:--  479k
docker build      --build-arg CUSTOM_DOMAIN_NAME=sample-domain1 --build-arg CUSTOM_ADMIN_HOST=wlsadmin --build-arg CUSTOM_ADMIN_NAME=admin-server --build-arg CUSTOM_ADMIN_PORT=7001 --build-arg CUSTOM_MANAGED_SERVER_PORT=8001 --build-arg CUSTOM_DEBUG_PORT=8453     --build-arg WDT_MODEL=simple-topology.yaml     --build-arg WDT_VARIABLE=properties/docker-build/domain.properties     --build-arg WDT_ARCHIVE=archive.zip     --force-rm=true          -f /home/opc/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image-wdt/Dockerfile     -t 12213-domain-home-in-image-wdt     /home/opc/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image-wdt
Sending build context to Docker daemon 1.006 MB
Step 1/28 : FROM oracle/weblogic:12213-patch-wls-for-k8s
Trying to pull repository docker.io/oracle/weblogic ...
repository docker.io/oracle/weblogic not found: does not exist or no pull access
Error response from daemon: no such id: 12213-domain-home-in-image-wdt:latest
[ERROR] Create domain sample-domain1 failed.

[opc@centos7-1 domain-home-in-image]$ docker pull docker.io/oracle/weblogic
Using default tag: latest
Trying to pull repository docker.io/oracle/weblogic ...
repository docker.io/oracle/weblogic not found: does not exist or no pull access

**Comment by moreaut** [comment]
Hi Shaun,

Did you set up a secret to access the docker store?

https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/weblogic-docker-images.md

kubectl create secret docker-registry SECRET_NAME
  -n NAMESPACE
  --docker-server=index.docker.io/v1/
  --docker-username=YOUR_USERNAME
  --docker-password=YOUR_PASSWORD
  --docker-email=YOUR_EMAIL

Thanks, -Tom

**Comment by shaunxa** [comment]
Tom, thank you for your help.

I realized that I missed some steps of building the images oracle/serverjre:8, oracle/weblogic:12.2.1.3-developer and oracle/weblogic:12213-patch-wls-for-k8s.
The issue was resolved after building the images.

Cheers,
Shaun
