### ISSUE TITLE
Questions I'm thinking about on the WebLogic Operator

### ISSUE THREAD

**Issue by bryantidd** [oracle/weblogic-kubernetes-operator#76]
One concern is the necessity to have a unique domainUID...is this required only among those resources managed by a particular weblogic-operator?

How will HA work for the operator? Is it just down to the replication set, etc.? 

What are the primary resources that must be considered when tuning the operator and it's required resources for relative load levels?

How many namespaces and domains should a deployment of weblogic operator be responsible for managing?

Has any work on using alternate ingress controller classes been done yet? Big vote for HAProxy here...maybe others...need a nice way to proxy tcp not just http and https for T3, etc.

**Comment by markxnelson** [comment]
hi @bryantidd 
The domainUID is meant to be unique in the world.  We plan to use it when we start supporting HA across clouds, etc., where we would have different instances of the operator collaborating to do things like propagating config changes from active to passive copies of the domain. 
It is still early days in thinking through all of the HA/DR scenarios, but we have some ideas. 
We don't have any particular tuning guidelines yet, but we anecdotally think a single operator could manage hundreds of domains. 
We have done a little bit of playing around with nginx ingress controller.  I believe we are planning to do HAProxy first now though.

**Comment by markxnelson** [comment]
Also should support cloud ingress providers - maybe expose a parameter for ingress annotation and create the ingress for the cloud provider's ingress instead of traefik/etc.

**Comment by tbarnes-us** [comment]
This Issue has gotten pretty old!  Assuming it should be closed.

FWIW I think the current WKO behavior now only requires a unique domain-uid within a namespace (which means the same operator can manage duplicate domain-uids if they are in different namespaces). But we still recommend making it 'world unique'. Also, note that having a unique domain-uid does not remove the universal WL requirement that each different WL domain must have a different name if they directly communicate with each other, or if there is a mutual WL client or WL server that communicates with both domains.

For future questions of this nature please feel free to use WKO's public #operator slack channel at oracle-weblogic.slack.com (sign-up here: https://weblogic-slack-inviter.herokuapp.com/). The slack channel is closely monitored, and tends to get a quicker response in comparison to filing an Issue.
