### ISSUE TITLE
Quickstart needs to be updated for rc1

### ISSUE THREAD

**Issue by namanshenoy** [oracle/weblogic-kubernetes-operator#772]
Current quick start does not work with latest version.

**Comment by moreaut** [comment]
Can you please try the 2.0-rc2 branch?

And, if you jave problems in the quick start, please provide more details.

Thanks, -Tom

**Comment by moreaut** [comment]
Thanks for the clarification.

It's more than a fix to the readme - you modified the product too (i.e. the operator helm chart's values.yaml).

**Comment by alai8** [comment]
Could you check if https://github.com/oracle/weblogic-kubernetes-operator/pull/776 has addressed the issue? Thanks

**Comment by alai8** [comment]
The quick start guide for 2.0-rc2 has been updated with the correct image name for the operator rc2 image specified in the helm install command example:

```
$ helm install kubernetes/charts/weblogic-operator \
  --name sample-weblogic-operator \
  --namespace sample-weblogic-operator-ns \
  --set image=oracle/weblogic-kubernetes-operator:2.0-rc2 \
  --set serviceAccount=sample-weblogic-operator-sa \
  --set "domainNamespaces={}" \
  --wait
```
