### ISSUE TITLE
Provide support for adding Init Containers to generated server instance pods.

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#788]
Several customers have described use cases that would be simplified if they could have [Init Containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/).

Very similarly to volumes and volumeMounts support, the operator should support allowing the customer to inject init containers at domain, cluster, or server instance scope.

**Comment by tbarnes-us** [comment]
If any of the init container use cases involve modifying configuration, then there's also the need for an 'introspector scope'.

**Comment by bryantidd** [comment]
Use case that is the primary driver for me is preparing volumes that will be used later by server instances. 
I am sure that there are many more. Possibly in the case that you have to create a domain, then complete a non-dynamic change that requires a restart.

**Comment by bryantidd** [comment]
Would very much like an update on this one!

**Comment by rjeberhard** [comment]
@bryantidd, I'm working on finalizing this now (took it over from Mark).  What do you think about specifying InitContainers for the introspector job pod?  We don't presently have a section in the domain resource for the introspector job pod and, instead, we treat it similarly to the administration server.  However, @tbarnes-us correctly points out that if the InitContainer will change configuration then this needs to happen before the configuration introspection.
