### ISSUE TITLE
Sample support for dynamic PV provisioning

### ISSUE THREAD

**Issue by rjeberhard** [oracle/weblogic-kubernetes-operator#789]
Our domain creation samples assume that the customer will create a PV and then create a PVC.  It's a common use case; however, especially on cloud providers, that the PVC is created first and then that the PV is created dynamically based on a storage driver.  For instance, Oracle's OCI describes dynamically creating PV's [here](https://docs.cloud.oracle.com/iaas/Content/ContEng/Tasks/contengcreatingpersistentvolumeclaim.htm).

We should upgrade our samples to allow for PVC with dynamic provisioning of PV's.

**Comment by bryantidd** [comment]
If appropriate, would a community samples page be supported. We could submit samples using the PVC and other cloud providers,or would that complicate this project in ways unnecessarily?

**Comment by bryantidd** [comment]
Maybe just point folks to the storage class and Dynamic PV sections of Kubernetes documentation would be best after your sample.

**Comment by bryantidd** [comment]
https://kubernetes.io/docs/concepts/storage/storage-classes/
https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/
https://github.com/kubernetes-incubator/external-storage

**Comment by mriccell** [comment]
@bryantidd this is a great suggestion!  We are discussing what is the best way to implement community samples, as soon as we have a process we will document it so that you can contribute!

**Comment by bryantidd** [comment]
@mriccell Thanks, I think that will be a great way for the project to flourish.

**Comment by tbarnes-us** [comment]
@rjeberhard : Please triage this issue.
