### ISSUE TITLE
"image" parameter in create-operator-inputs.yaml

### ISSUE THREAD

**Issue by trobert57** [oracle/weblogic-kubernetes-operator#85]
For me it was unclear how to name the image parameter in the configuration file. The default points to container-registry.oracle.com. I had built my image within the kubernetes master. I could not find out how to use that. After pushing that image into my local docker-registry, the create-weblogic-operator.sh script finished successfully.

**Comment by rjeberhard** [comment]
Hi, Thomas.  Thanks for the report.  We had a "chicken-and-egg" problem in that we couldn't get permission to push the image from the master build to container-registry until after the project was fully public.  So, in the meantime, you have to build the image locally and push or load it to your registry of choice.  We'll take another look at the documentation to clarify this.
