### ISSUE TITLE
WLS domain needs to be deleted if secret is wrong

### ISSUE THREAD

**Issue by mgueury** [oracle/weblogic-kubernetes-operator#864]
Version 2.0

Step by step
-------------
Follow the tutorial:

https://github.com/nagypeter/weblogic-operator-tutorial/blob/master/tutorials/domain-home-in-image.md

In part 4: Deploy WebLogic domain
Do an error in the creation of the ocirsecret like a bad password or a bad username
```
kubectl create secret docker-registry ocirsecret \
  -n sample-domain1-ns \
  --docker-server=YOUR_HOME_REGION_CODE.ocir.io \
  --docker-username='YOUR_TENANCY_NAME/YOUR_OCIR_USERNAME' \
  --docker-password='YOUR_OCIR_AUTH_TOKEN' \
  --docker-email='YOUR_EMAIL'
```

then create the domain.
Nothing happens.

Until there, it is expected:
```
kubectl describe pods -n sample-domain1-ns
  Type     Reason     Age   From                   Message
  ----     ------     ----  ----                   -------
  Normal   Scheduled  0s    default-scheduler      Successfully assigned sample-domain1-ns/sample-domain1-introspect-domain-job-zrcwm to 130.61.34.43
  Normal   Pulling    0s    kubelet, 130.61.34.43  pulling image "fra.ocir.io/oraseemeabeneluxall/eblogic-operator-tutorial:latest"
  Warning  Failed     0s    kubelet, 130.61.34.43  Failed to pull image "fra.ocir.io/oraseemeabeneluxall/eblogic-operator-tutorial:latest": rpc error: code = Unknown desc = Get https://fra.ocir.io/v2/oraseemeabeneluxall/eblogic-operator-tutorial/manifests/latest: unknown: Unauthorized
  Warning  Failed     0s    kubelet, 130.61.34.43  Error: ErrImagePull
  Normal   BackOff    0s    kubelet, 130.61.34.43  Back-off pulling image "fra.ocir.io/oraseemeabeneluxall/eblogic-operator-tutorial:latest"
  Warning  Failed     0s    kubelet, 130.61.34.43  Error: ImagePullBackOff
```

```
kubectl delete secret ocirsecret -n sample-domain1-ns
```

Correct the ocirsecret. Nothing happens. (Bug)

**Comment by mgueury** [comment]
Then if you do:

```
kubectl apply -f domain.yaml
```
Nothing happens too. 

Work-around
--------------
The only way to get it working is to delete the domain and recreate it again

```
kubectl delete -f domain.yaml
kubectl apply -f domain.yaml
```

**Comment by markxnelson** [comment]
This is normal k8s behavior, since it could not pull the image a number of times it gave up and put the pod into ImagePullBackOff state.  It will not keep retrying indefinitely.

**Comment by rjeberhard** [comment]
This link defines the default Kubernetes behavior, which we have not changed: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy

I'd be open to making the backoff limit tunable, but ultimately, Kubernetes also gives up on any given Pod or Job, so that required action of deleting a resource, such as the domain, and recreating it to retry is standard.
