### ISSUE TITLE
Headers on XML Files

### ISSUE THREAD

**Issue by RobDolinORCL** [oracle/weblogic-kubernetes-operator#869]
Are the headers on XML files like /swagger/pom.xml correct?  They seem to suggest the files are unreleased and proprietary but the files look like they're being provided in a repository that is licensed under the Universal Permissive License.

https://github.com/oracle/weblogic-kubernetes-operator/blob/9233a080fbc5a7a96364e46e221b5c41e9e2d838/swagger/pom.xml#L1-L2

**Comment by markxnelson** [comment]
Thanks Rob, we will remove those incorrect headers.

**Comment by rjeberhard** [comment]
Yes, thanks @RobDolinORCL.  I appreciate the bug.  We missed removing these headers.
