### ISSUE TITLE
create-domain-job.sh doesn't start any servers

### ISSUE THREAD

**Issue by trobert57** [oracle/weblogic-kubernetes-operator#87]
Running ./create-domain-job.sh -i create-domain-job-inputs.yaml runs successfully, but doesn't start any wls server. How can I find out, what is going wrong?
My domain namespace is wls1domain (the one that the operator should manage).
kubectl get pods -n wls1domain
NAME                                         READY     STATUS    RESTARTS   AGE
domain1-cluster-1-traefik-6b75757549-w49wr   1/1       Running   0          1h

kubectl get pods -n weblogic-operator
NAME                                 READY     STATUS    RESTARTS   AGE
weblogic-operator-766c9f495f-fvqjj   1/1       Running   0          9h

But looking at the last line of the operator log files, it seems no longer running (?):
kubectl logs weblogic-operator-766c9f495f-fvqjj -n weblogic-operator
...
{"exception":"\njava.lang.NumberFormatException: For input string: \"8+\"\n\tat java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)\n\tat java.lang.Integer.parseInt(Integer.java:580)\n\tat java.lang.Integer.parseInt(Integer.java:615)\n\tat oracle.kubernetes.operator.helpers.HealthCheckHelper.verifyK8sVersion(HealthCheckHelper.java:251)\n\tat oracle.kubernetes.operator.helpers.HealthCheckHelper.performNonSecurityChecks(HealthCheckHelper.java:170)\n\tat oracle.kubernetes.operator.Main.main(Main.java:150)\n","headers":{},"code":"","method":"main","level":"WARNING","thread":1,"timeInMillis":1517052358865,"message":"Exception thrown: {0}","body":"","class":"oracle.kubernetes.operator.Main","timestamp":"01-27-2018T11:25:58.865+0000"}
{"exception":"","headers":{},"code":"","method":"main","level":"INFO","thread":1,"timeInMillis":1517052358867,"message":"The Oracle WebLogic Server Operator for Kubernetes is shutting down","body":"","class":"oracle.kubernetes.operator.Main","timestamp":"01-27-2018T11:25:58.867+0000"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+2.0.1.el7", GitCommit:"538ac53c74231a70b7ceca01b8f8d09a735b4ffb", GitTreeState:"\"git", BuildDate:"2017-12-14T22:28:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

I am lost in finding out where to look, what I might have been doing wrong. Could it be my k8s version  #(v1.8.4+2.0.1.el7)??

**Comment by trobert57** [comment]
I would assume, the error is in HealthCheckHelper.java:251. 
The current code is: 
        String minor_string = info.getMinor();
        // It will check if it is a number.
        // If not it will remove the last part of the string in order to have just a number
        while( ! minor_string.chars().allMatch( Character::isDigit )) {
          minor_string = minor_string.substring(0, minor_string.length() -1);
        }
        Integer minor = Integer.parseInt(info.getMinor());

The last line (251) should read:
      Integer minor = Integer.parseInt(minor_string);
shouldn't it??

**Comment by markxnelson** [comment]
looks like @rjeberhard has already fixed this.

**Comment by rjeberhard** [comment]
Yes, I had to fix this as part of porting over our integration tests.
