### ISSUE TITLE
Oracle Container Registry Access

### ISSUE THREAD

**Issue by kaslin** [oracle/weblogic-kubernetes-operator#89]
The installation step:
./create-weblogic-operator.sh –i /path/to/create-operator-inputs.yaml

Is failing due to a missing authentication for the Oracle Container Registry.  "Registering for access to the Oracle Container Registry" is mentioned as a step in the Installation section of the readme, but not is not mentioned in installation.md.  Is this a step the installation guide is missing?

  4m		1m		5	kubelet, k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com	spec.containers{weblogic-operator}	Warning		FaileFailed to pull image "container-registry.oracle.com/middleware/weblogic-kubernetes-operator:latest": rpc error: code = 2 desc = Error response from daemon: {"message":"Get https://container-registry.oracle.com/v2/middleware/weblogic-kubernetes-operator/manifests/latest: unauthorized: authentication required"}

The only mention of Oracle Container Registry in installation.md is in weblogic-operator.yaml:
      # Update the imagePullSecrets with the name of your Kubernetes secret containing
      # your credentials for the Docker Store/Oracle Container Registry.
      imagePullSecrets:
      - name: ocr-secret

Is the user meant to create these secrets before trying to deploy the weblogic operator?

**Comment by markxnelson** [comment]
You are right the documentation is not clear enough. I will update it. You need to set the image in the inputs file to match the one you just built.

**Comment by kaslin** [comment]
How am I supposed to refer to the locally built image?

Even though docker image ls shows this:
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
weblogic-kubernetes-operator   developer           47e8937b3f35        2 hours ago         302MB

Neither the image id nor repository name seems to work:
  4m		1m		5	kubelet, k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com	spec.containers{weblogic-operator}	Warning		FaileFailed to pull image "47e8937b3f35": rpc error: code = 2 desc = Error response from daemon: {"message":"repository 47e8937b3f35 not found: does not exist or no pull access"}
  46m		4m		13	kubelet, k8s-worker-ad1-0.k8sworkerad1.k8sbmcs.oraclevcn.com	spec.containers{weblogic-operator}	Warning		FaileFailed to pull image "weblogic-kubernetes-operator": rpc error: code = 2 desc = Error response from daemon: {"message":"repository weblogic-kubernetes-operator not found: does not exist or no pull access"}

**Comment by kaslin** [comment]
I put it on my master. Which is silly now that you mention it, but it wasn't clear in the instructions.

**Comment by markxnelson** [comment]
If you have more than one worker, or you built it somewhere else, then you need to get that docker image onto all of the workers. 

You can either retag it and push it to a repo like docker.io or quay.io, or you can `docker save weblogic-kubernetes-operator:developer > k.tar` then scp it and `docker load <k.tar` on the workers

**Comment by markxnelson** [comment]
have a look at the developer instructions too if you get a chance, i think some of the answers are probably there, but we probably need to move them into the user instructions too.  as i said in the other issue, as soon as we get the oracle approval to publish the docker image into container registry, none of this manual building stuff will be needed any more. sorry for the inconvenience.  we had a chicken and egg problem, cant get approval to load the image into OCR or docker store until the repo was public, so as much as we wanted to have it done first, to avoid these exact issues, we had no choice

**Comment by kaslin** [comment]
I understand the need to put it on the Kubernetes workers. But without thinking through it and just following the instructions, 
"Next, upload your image to your Kubernetes server as follows:"
and
"# on the Kubernetes server"
Sound like they are referring to the master.

**Comment by markxnelson** [comment]
I added a PR to update the doc to say each worker
