### ISSUE TITLE
GID annotated PersistentVolume

### ISSUE THREAD

**Issue by qvdang** [oracle/weblogic-kubernetes-operator#931]
I followed the instructions on this page (https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/persistent-volumes.md) to set up a PersistentVolume for the WLS domain log directory when runing the Operator sample(https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/quickstart.md).  If I annotated(https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control) the PV using 

pv.beta.kubernetes.io/gid: "1234"
#other gid values worked too; I've tried "20", "6789" etc and they all worked.

then I didn't have to set the permissions of the HostPath's path directory to 777.

**Comment by TheFrogPad** [comment]
See PR #1054
