### ISSUE TITLE
not able to install ingress

### ISSUE THREAD

**Issue by rkaler** [oracle/weblogic-kubernetes-operator#965]
command used:

helm install ingress-per-domain --name soa-ingress --namespace rkoim --values ingress-per-domain/values.yaml
Error Message :
Error: error validating "": error validating data: found invalid field annotations for v1beta1.IngressSpec

Values.xml

sh-4.2$ cat ingress-per-domain/values.yaml 

type: TRAEFIK

wlsDomain:
  domainUID: soainfra
  clusterName: soa_cluster
  managedServerPort: 8001

traefik:
  hostname: adc00wvh.us.oracle.com

sh-4.2$ cat ingress-per-domain/templates/traefik-ingress.yaml 

{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik
  namespace: {{ .Release.Namespace }}
  labels:
    weblogic.resourceVersion: domain-v2
spec:
  annotations:
    kubernetes.io/ingress.class: traefik
  rules:
  - host: '{{ .Values.traefik.hostname }}'
    http:
      paths:
      - path:
        backend:
          serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.clusterName | lower | replace "_" "-" }}'
          servicePort: {{ .Values.wlsDomain.managedServerPort }}
{{- end }}

**Comment by rjeberhard** [comment]
@lilyhe123, I believe we just fixed this with PR #951, correct?

**Comment by lilyhe123** [comment]
Not sure. Usually the misplaced annotation doesn't cause any validation error, at least on bare-metal environment. But you can try the fix anyway. @rkaler

**Comment by rkaler** [comment]
Tried on the latest build as well. I am getting the same exception. I tried to install the traefik-operator  again with the new build and then tried to install ingress-per-domain again..  but it fails with the same exception

**Comment by lilyhe123** [comment]
@rkaler can you add `--dry-run --debug` when running `helm install` as below and past the output? So I can see the generated Ingress resource.
```
helm install --dry-run --debug ingress-per-domain --name soa-ingress --namespace rkoim --values ingress-per-domain/values.yaml
```

**Comment by rkaler** [comment]
@lilyhe123 

It gives the sample exception even with the debug logs

sh-4.2$ helm install --dry-run --debug ingress-per-domain --name soa-ingress --namespace rkoim --values ingress-per-domain/values.yaml
[debug] Created tunnel using local port: '50560'

[debug] SERVER: "127.0.0.1:50560"

[debug] Original chart version: ""
[debug] CHART PATH: /scratch/rkaler/weblogic-kubernetes-operator/kubernetes/samples/charts/ingress-per-domain

Error: error validating "": error validating data: found invalid field annotations for v1beta1.IngressSpec

**Comment by lilyhe123** [comment]
Per our IM, the k8s version you used is v1.9.2 which is an old version the operator doesn't support. See doc https://oracle.github.io/weblogic-kubernetes-operator/userguide/introduction/introduction/#prerequisites. Pls upgrade to k8s 1.10 at least and rerun.
