### ISSUE TITLE
weblogic-kubernetes-operator and weblogic versions

### ISSUE THREAD

**Issue by cchaplin** [oracle/weblogic-kubernetes-operator#966]
Is weblogic kubernetes operator dependent on weblogic version? My question is, can I use weblogic kubernetes operator with weblogic 10.3.6 ?

**Comment by rjeberhard** [comment]
Hi, @cchaplin. The operator only works with WebLogic 12.2.1.3: https://github.com/oracle/weblogic-kubernetes-operator/blob/master/site/user-guide.md#prerequisites
