### ISSUE TITLE
Failed to create service account weblogic-operator

### ISSUE THREAD

**Issue by markxnelson** [oracle/weblogic-kubernetes-operator#99]
Create operator script fails with this message: 

hecking to see if the service account weblogic-operator already exists
Error: unknown shorthand flag: 'n' in -n
Usage:
  kubectl get [(-o|--output=)json|yaml|wide|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...] (TYPE [NAME | -l label] | TYPE/NAME ...) [flags] [flags]

Examples:
# List all pods in ps output

**Comment by amyles** [comment]
Hi 
I'm using this version of kubectl:

> amyles@braan:~/k8s-wls-operator/weblogic-kubernetes-operator/kubernetes$ kubectl versionClient >Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", >GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
>Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", >GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

**Comment by amyles** [comment]
Also:

> amyles@braan:~/k8s-wls-operator/weblogic-kubernetes-operator/kubernetes$ docker version Client:
>  Version:	17.12.0-ce
>  API version:	1.35
>  Go version:	go1.9.2
>  Git commit:	c97c6d6
>  Built:	Wed Dec 27 20:11:19 2017
>  OS/Arch:	linux/amd64
> 
> Server:
>  Engine:
>   Version:	17.12.0-ce
>   API version:	1.35 (minimum version 1.12)
>   Go version:	go1.9.2
>   Git commit:	c97c6d6
>   Built:	Wed Dec 27 20:09:53 2017
>   OS/Arch:	linux/amd64
>   Experimental:	false
>

**Comment by amyles** [comment]
Full output of the command attached. 
[create-op-output.txt](https://github.com/oracle/weblogic-kubernetes-operator/files/1724024/create-op-output.txt)

**Comment by rjeberhard** [comment]
I see this in the output:

/home/amyles/k8s-wls-operator/weblogic-kubernetes-operator/kubernetes/internal/generate-security-policy.sh: 191: /home/amyles/k8s-wls-operator/weblogic-kubernetes-operator/kubernetes/internal/generate-security-policy.sh: Bad substitution

Line 191 of generate-security-policy.sh is:

  for i in ${TARGET_NAMESPACES//,/ }

Your TARGET_NAMESPACES value is just "default", so for some reason this expression is failing in your Linux since there is no comma.

**Comment by alai8** [comment]
[Commit 141d1f0](https://github.com/oracle/weblogic-kubernetes-operator/commit/141d1f02ca7f09565c2543cc9467ca77ac8c2641) addresses the 'Bad substitution' issue.

Please also make sure that you are using one of the supported Kubernetes versions listed in the [README.md](https://github.com/oracle/weblogic-kubernetes-operator/blob/master/README.md)

> The Oracle WebLogic Server Kubernetes Operator has the following requirements:
>     Kubernetes 1.7.5+, 1.8.0+, 1.9.0+, 1.10.0 (check with kubectl version).
