### ISSUE TITLE
Documents the steps needed to update the application running in a domain

### ISSUE THREAD

**Issue by flistell** [oracle/weblogic-kubernetes-operator#992]
One of more interesting things about K8S is the possibility to update an application without any service interruption. 
It's a primary use case for many customers.
It's not clear in the docs how this can be achieved when using domain-into-image paradigm.

**Comment by maggiehe00** [comment]
Public doc of "Run a WebLogic CI/CD Sample on Kubernetes Using Operator 2.0" will be published soon. Are you internal Oracle?

**Comment by maggiehe00** [comment]
I can see you are... :) so you can take a look at this wiki : http://aseng-wiki.us.oracle.com/asengwiki/pages/viewpage.action?pageId=5252470824#RunaWebLogicCI/CDSampleonKubernetesUsingOperator2.0-CI/CDProcess

**Comment by mriccell** [comment]
@flistell please take a look at the CI/CD documentation at https://oracle.github.io/weblogic-kubernetes-operator/userguide/cicd/

**Comment by mriccell** [comment]
I will close this comment due to lack of response.

**Comment by flistell** [comment]
https://oracle.github.io/weblogic-kubernetes-operator/userguide/cicd/ is a great document. Thank you.
