### ISSUE TITLE
how to deploy P6 on this platform?

### ISSUE THREAD

**Issue by wtdragon** [oracle/weblogic-kubernetes-operator#995]
I want to deploy P6 to this platform, is there any sugesstions?

**Comment by markxnelson** [comment]
P6 is a managed service, you would not deploy it on your own WebLogic, you just subscribe to the service.  Can you give more details of what you mean by your question please?

**Comment by wtdragon** [comment]
there's one P6 EPPM 18.8 need to be deployed.
with the  install guide, i must have one wls12c environment.
then install P6 EPPM 18.8.
after that deploy p6 and p6 connector .
yes, i think finally it's deployed only services, but where i should install P6 EPPM 18.8 and how the port assign with the two services?
I tried in the running node install P6 EPPM 18.8, it's can't be done.

**Comment by rjeberhard** [comment]
@markxnelson @wtdragon, here is the documentation on installing P6: https://docs.oracle.com/cd/E90747_01/helpmain.htm?toc.htm?91798.htm.

This documentation assumes an on-premise installation.  

The operator team is close to generally supporting layered products and we've been working with many upper stack teams (e.g. BI, SOA) to provide images and support at their product level.  I'm not aware that we've connected with P6.  Let me reach out and see if I can find a contact.

**Comment by wtdragon** [comment]
@rjeberhard 
get it.
I read this document and deployed one P6 EPPM 18.8 in an centos7 server,
and also setup successful on wls12c domain on a kubernetes  environment.

![image](https://user-images.githubusercontent.com/1210629/55298846-91228e80-5462-11e9-80ef-89952b741301.png)

![image](https://user-images.githubusercontent.com/1210629/55298938-0f7f3080-5463-11e9-8a20-a3f5b1ce82d3.png)

I am trying to copy the already can be used  war file deploy on the "k8sed" wls. I'll leave a message if it's can be done.

Thanks.

**Comment by wtdragon** [comment]
I copied the full worked P6 folder into the running  docker contrainer.
p6procloudconnect.war can be deployed.
p6.ear can't.
after deploy p6.ear the wls pod crashed, then deployed p6procloudconnect erased,
I used PVC to save data, looks like it's only save persistent wls data, deployed things lost.

Thanks.
